### ISSUE TITLE
Traffic shape not working

### ISSUE THREAD

**Issue by mrjedi** [facebook/augmented-traffic-control#100]
Hello,

I am using my ubuntu linux as a router, with two network cards eth0, eth1, and eth1 connecting to the Internet with PPPOE. The firewall is set to be NAT (using MASQUERADE).

The traffic isn't shaped on my device connecting to the linux server, is there any special configuration needed for this case?

Thanks!

**Comment by chantra** [comment]
Hi @mrjedi 
did you swap the values of --atcd-wan and --atcd-lan ? They default to eth0 and eth1 respectively. In your case, they should be swapped, so you should start atcd with a command like:
```
atcd --atcd-wan eth1 --atcd-lan eth0
```

**Comment by mrjedi** [comment]
HI @chantra 

Thanks you for quick reply.

I tried both

atcd --atcd-wan eth1 --atcd-lan eth0 and

atcd --atcd-wan ppp0 --atcd-lan eth0 ,

But my device still remains the same internet speed.

**Comment by chantra** [comment]
ok, could you give me more details about your setup.

Can you make a gist ( https://gist.github.com/ ) with the output of:
```
ip route
iptables  -nvt mangle -L
for i in qdisc class filter; do for j in eth0 eth1; do c="tc $i show dev $j"; echo $c; $c; done; done
```

Along with the content from `/var/log/messages` that get generated when a device shape its traffic.

**Comment by mrjedi** [comment]
Thanks,

This is the gist:

https://gist.github.com/a9b6112589643112175c.git

For /var/log/messages, I don't see the file on my linux router.

**Comment by chantra** [comment]
Hi
So you have to use ppp0 as wan and eth0 as lan.
For the logs, grep for Shaping in your logs to find the log file.
From the output you sent, traffic for localhost was being shaped using eth0 and eth1. You need to trigger the shaping from the device that you want to be shaped, not from the router. There is no way the router knows which to shape without initiating the query from the device or explicitly telling it.

**Comment by mrjedi** [comment]
Hi chantra,

I got it worked! Using ppp0 as WAN, and triggering the shaping from the device.

Thank you very much for your help.

**Comment by chantra** [comment]
@mrjedi 
Nice to hear. Thanks for letting me know.
