### ISSUE TITLE
required help when setting ATC over VM (lubuntu)

### ISSUE THREAD

**Issue by ankit-ankuagrawal** [facebook/augmented-traffic-control#101]
hello everyone, newbie to this, required ur help

following are the things done till now
1) host machine: windows 7
2) installed virtual box over it
3) using lubuntu 64 bit as guest VM

having doubt is:
ATC requires 2 interface one for lan and other wifi, but guest VM cant have wifi interface? then how to proceed?

or moving in wrong direction pls help out

**Comment by agargiulo** [comment]
The second interface doesn't need to be WiFi, just a second interface.

**Comment by ankit-ankuagrawal** [comment]
@agargiulo  ty for the response 
then how wifi hotspot will be created, so that the devices should get connect ?
should make any dummy 2nd interface will work?

**Comment by agargiulo** [comment]
ATC is just sitting on the routing device (in this case, your lubuntu box it seems) and shapes traffic between the two interfaces. If you then want clients to connect via WiFi, that's a separate thing, not related to ATC at all. I'm not 100% certain, maybe @chantra could provide more insight here, but if you want WiFi, you can have ATC on the routing box, then have the wireless access point use the ATC box as its default gateway. This is all very dependent on how your network is configured of course.

**Comment by chantra** [comment]
Hi @ankit-ankuagrawal 
The idea here is that you want to set:
1) an Access point in the windows VM
2) create a second interface for your VM and connect it to the WIFI network adapter in bridge mode
3) Have your VM set as a router (ip forwarding and also natting in this case)
4) Have the VM provide dhcp service on the second adapter (for the wifi basically)
5) set ATCon that VM.

**Comment by agargiulo** [comment]
:+1:

**Comment by chantra** [comment]
Hi @ankit-ankuagrawal 

I hope those indications are enough to get you going. I will close this issue for now. Feel free to jump on freenode's #atcd irc channel if you have any questions. We will be able to help you in a more interactive way.
