### ISSUE TITLE
Shaping with two interfaces on same subnet

### ISSUE THREAD

**Issue by biosed** [facebook/augmented-traffic-control#104]
Perhaps not an issue but my misunderstanding.
I have Linux box with two interfaces:
eth0 10.104.102.6 255.255.254.0 gw 10.104.102.1
eth1 10.104.102.7 255.255.254.0 

I have enabled forwarding and when I set the gateway on a device I want to shape to 10.104.102.7 I can access external sites but shaping doesn't seem to apply, I am presuming this is happening because eth1 is using the default gateway and the traffic in no going out over eth0?

Can I shape traffic when both interfaces are on the same subnet?

**Comment by chantra** [comment]
@biosed 
Shaping only applied upon forwarding and leaving interfaces eth0 and eth1.
The fact that you have the interface IP local to your host, the traffic will not be forwarded but delivered locally. Preventing 2 things to happen:
- Tagging packets when forwarding them
- shaping those packets when they leave the host (assuming they would have been tagged, they will never go out of eth1 anyway).

To have a valid set up, your traffic needs to go through the host running ATC. You cannot shape traffic from the ATC host itself.
