### ISSUE TITLE
i have a problem!

### ISSUE THREAD

**Issue by kimjungyeon** [facebook/augmented-traffic-control#105]
this is my log
when i run this code, "atcd --atcd-wan eth0 --atcd-lan eth1"
this problem bother me

ERROR:sparts.tasks:Error creating task, AtcdNBServerTask
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sparts/vtask.py", line 313, in init
    t.initTask()
  File "/usr/local/lib/python2.7/dist-packages/sparts/tasks/thrift.py", line 146, in initTask
    self.server.prepare()
  File "/usr/local/lib/python2.7/dist-packages/thrift/server/TNonblockingServer.py", line 254, in prepare
    self.socket.listen()
  File "/usr/local/lib/python2.7/dist-packages/thrift/transport/TSocket.py", line 173, in listen
    self.handle.bind(res[4])
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use
INFO:AtcdVService.AtcdLinuxShaper:Calling initialize_shaping_system
INFO:AtcdVService.AtcdLinuxShaper:Running /sbin/iptables -t mangle -F FORWARD
INFO:AtcdVService.AtcdLinuxShaper:deleting root QDisc on eth1
INFO:AtcdVService.AtcdLinuxShaper:setting root qdisc on eth1
INFO:AtcdVService.AtcdLinuxShaper:deleting root QDisc on eth0
INFO:AtcdVService.AtcdLinuxShaper:setting root qdisc on eth0
INFO:AtcdVService.AtcdLinuxShaper:Restoring shaped connection from DB
INFO:AtcdVService.AtcdLinuxShaper:Request startShaping TrafficControl(device=TrafficControlledDevice(controllingIP='172.4.29.250', controlledIP='172.4.29.250'), timeout=83862.76753091812, settings=TrafficControlSetting(down=Shaping(loss=Loss(percentage=0.0, correlation=0.0), delay=Delay(delay=0, jitter=0, correlation=0.0), rate=None, iptables_options=[], corruption=Corruption(percentage=0.0, correlation=0.0), reorder=Reorder(percentage=0.0, correlation=0.0, gap=0)), up=Shaping(loss=Loss(percentage=0.0, correlation=0.0), delay=Delay(delay=0, jitter=0, correlation=0.0), rate=None, iptables_options=[], corruption=Corruption(percentage=0.0, correlation=0.0), reorder=Reorder(percentage=0.0, correlation=0.0, gap=0))))
INFO:AtcdVService.AtcdLinuxShaper:Shaping ip 172.4.29.250 on interface eth0
INFO:AtcdVService.AtcdLinuxShaper:create new HTB class on IFID eth0, classid 1:2,parent 1:0, rate 4194303kbits
INFO:AtcdVService.AtcdLinuxShaper:create new Netem qdisc on IFID eth0, parent 1:2, loss 0.0%, delay 0
INFO:AtcdVService.AtcdLinuxShaper:create new FW filter on IFID eth0, classid 1:2, handle 2, rate: Nonekbits
INFO:AtcdVService.AtcdLinuxShaper:Running /sbin/iptables -t mangle -A FORWARD -d 172.4.29.250 -i eth0  -j MARK --set-mark 2
INFO:AtcdVService.AtcdLinuxShaper:Shaping ip 172.4.29.250 on interface eth1
INFO:AtcdVService.AtcdLinuxShaper:create new HTB class on IFID eth1, classid 1:2,parent 1:0, rate 4194303kbits
INFO:AtcdVService.AtcdLinuxShaper:create new Netem qdisc on IFID eth1, parent 1:2, loss 0.0%, delay 0
INFO:AtcdVService.AtcdLinuxShaper:create new FW filter on IFID eth1, classid 1:2, handle 2, rate: Nonekbits
INFO:AtcdVService.AtcdLinuxShaper:Running /sbin/iptables -t mangle -A FORWARD -s 172.4.29.250 -i eth1  -j MARK --set-mark 2
ERROR:AtcdVService:Unexpected Exception during init
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sparts/vservice.py", line 268, in _runloop
    instance._createTasks()
  File "/usr/local/lib/python2.7/dist-packages/sparts/vservice.py", line 167, in _createTasks
    self.tasks.init()
  File "/usr/local/lib/python2.7/dist-packages/sparts/vtask.py", line 332, in init
    len(exceptions))
Exception: Unable to start service (1 task start errors)
INFO:AtcdVService:Received graceful shutdown request
DEBUG:AtcdVService:VService Active.  Awaiting graceful shutdown.
INFO:AtcdVService:Waiting for tasks to shutdown gracefully...
DEBUG:AtcdVService:Waiting for <atcd.AtcdDeviceTimeoutTask.AtcdDeviceTimeoutTask object at 0x7f3b35517c50> to stop...
DEBUG:AtcdVService:Waiting for <atcd.backends.linux.AtcdLinuxShaper object at 0x7f3b35506a50> to stop...
DEBUG:AtcdVService:Waiting for <atcd.AtcdDBQueueTask.AtcdDBQueueTask object at 0x7f3b35506b90> to stop...
DEBUG:AtcdVService:Waiting for <atcd.AtcdThriftHandlerTask.AtcdNBServerTask object at 0x7f3b35506c50> to stop...
INFO:AtcdVService:Instance shut down gracefully

**Comment by kimjungyeon** [comment]
this is my networks
lan ap1 --------nic1(eth1)/nic(eth0)--------wan ap2(many mobile devices at this ap)
<---------------------------------------------------(data flow)

**Comment by kimjungyeon** [comment]
and my iptables like this
#iptables --table nat --append POSTROUTING --out-interface eth1 -j MASQUERADE
&&
#iptables --append FORWARD --in-interface eth0 -j ACCEPT

**Comment by zfjagann** [comment]
It looks like it's failing to bind to the thrift port:

    error: [Errno 98] Address already in use

Are you already running an ATC server? Or is something else listening on the thrift port?

(atcd uses port `9090`)[https://github.com/facebook/augmented-traffic-control/blob/master/atc/atcd/atcd/AtcdThriftHandlerTask.py#L100]

**Comment by kimjungyeon** [comment]
yeep! i did it! although there is so many ploblem in my finger.... thank you so much zfjagann!
