### ISSUE TITLE
atc_thift make breaks pip

### ISSUE THREAD

**Issue by yiannisy** [facebook/augmented-traffic-control#107]
When I update and make atc_thrift pip breaks. atc_thirft/atc_thirft/__init__.py doesn't contain a __version__ ='X.X.X' line which prevents pip from installing the package.

Is this intentional, is there a better way to update the interface and reinstall?

Error message below : 
vm:/tmp/augmented-traffic-control/atc/atc_thrift$ pip install .
Unpacking /tmp/augmented-traffic-control/atc/atc_thrift
  Running setup.py (path:/tmp/pip-0EQ6wv-build/setup.py) egg_info for package from file:///tmp/augmented-traffic-control/atc/atc_thrift
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-0EQ6wv-build/setup.py", line 26, in <module>
        version = get_version('atc_thrift')
      File "/tmp/pip-0EQ6wv-build/setup.py", line 24, in get_version
        return re.search("__version__ = ['\"]([^'\"]+)['\"]", init_py).group(1)
    AttributeError: 'NoneType' object has no attribute 'group'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-0EQ6wv-build/setup.py", line 26, in <module>

    version = get_version('atc_thrift')

  File "/tmp/pip-0EQ6wv-build/setup.py", line 24, in get_version

    return re.search("__version__ = ['\"]([^'\"]+)['\"]", init_py).group(1)

AttributeError: 'NoneType' object has no attribute 'group'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-0EQ6wv-build
Storing debug log for failure in /tmp/tmpbLjUvA

**Comment by chantra** [comment]
Hi @yiannisy 
Could you give more details about your setup? What OS/os version, what python version do you use?

Don't you have the file atc/atc_thrift/atc_thrift/__init__.py on disk? this is where `get_version` find the version to use.

**Comment by chantra** [comment]
@yiannisi do you have any update? Thanks

**Comment by yiannisy** [comment]
Hi @chantra ,

I am using python 2.7.6, Ubuntu 14.04 LTS.  I do have the atc_thrift/atc_thrift/__init.py__ file. When downloaded from github it has the __version__ attribute. After I run "make"  on atc_thrift, the __init.py__ is still there but without the __version__ attribute.

To replicate : 
1. git clone https://github.com/facebook/augmented-traffic-control.git
2. cd "......./atc_thrift/
3. cat atc_thrift/__init__.py
__all__ = ['ttypes', 'constants', 'Atcd']
__version__ = '0.1.1'
4. make
5. cat atc_thrift/__init__.py
__all__ = ['ttypes', 'constants', 'Atcd']

**Comment by chantra** [comment]
oh.... ok, well **don't** run make for now. make is only used to recompile the thrift files (which we ship as part of atc_thrift python package).

Basically for now just run 
```
pip install .
```

**Comment by yiannisy** [comment]
I am doing some changes on the service and have to recompile thrift. I have to manually append \__version\__ to make it work. It's an easy workaround, so this is mostly an FYI.

**Comment by chantra** [comment]
Thanks for letting us know @yiannisy 
I will fix it in a bit when I get some spare time, it is rather trivial.

I am happy to see the changes you want to incorporate. PR are welcome :)

**Comment by yiannisy** [comment]
Thanks. I'll keep you posted on changes!
