### ISSUE TITLE
Support python 3

### ISSUE THREAD

**Issue by chantra** [facebook/augmented-traffic-control#108]
It would be nice to support python 3. So far thrift was preventing us to do so as it was only python2 compatible. https://thriftpy.readthedocs.org/ seems to be a nice alternative that may solve this issue.

**Comment by facebook-github-bot-7** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by chantra** [comment]
I will close this as we are moving toward a golang implementation of atc
