### ISSUE TITLE
How to set iperf's server ip?

### ISSUE THREAD

**Issue by SummerHaze** [facebook/augmented-traffic-control#110]
Hi, it's me again~(submit the #103 issue)

I tried to use iperf to perform the test, but the environment confused me.
The whole network situation's like:
![image](https://cloud.githubusercontent.com/assets/5780674/7610047/1771b26a-f9ac-11e4-9305-bbf7529738ea.png)
So I use the iphone/pc as my iperf client and the console pc as iperf server.
But now I'm not sure whether 192.168.2.1.or 10.18.251.34 the server ip, cause neither one makes the bandwidth changing with settings on atcd web demo( server use udp,no packet lossing situation ).

Any help？
Thank you.

**Comment by chantra** [comment]
@summerhaze the server should be running  at least *1* hop away from atc, not in atc.

**Comment by zfjagann** [comment]
@SummerHaze: as @chantra mentioned, running iperf on the same machine as ATC will give improper network results. You should try to run the iperf server from another machine outside your ATC-managed subnet. Either another machine below your company's firewall, or from somewhere on the internet ([AWS](http://aws.amazon.com/) or [GCE](https://cloud.google.com/compute/) are pretty good for this).

On [iperf](https://staff.science.uva.nl/j.blom/gigaport/tools/man/iperf.html) or [iperf3](https://code.google.com/p/iperf/wiki/ManPage) you can set the bind address using the `-B` argument and the bind port using the `-p` argument.
