### ISSUE TITLE
support ipv6

### ISSUE THREAD

**Issue by chantra** [facebook/augmented-traffic-control#115]
Currently, atcd only supports ipv4. Add support for ipv6.

Once atcd support ipv6, the UI/API will also need to be modified.

**Comment by chantra** [comment]
@zfjagann and I had a chat IRL on how we could tackle this. We will update this task with a draft.

**Comment by facebook-github-bot-7** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by chantra** [comment]
Let's get this rolling soon.

**Comment by chantra** [comment]
This is happening in the golang branch
