### ISSUE TITLE
Provide instructions for a no-additional-equiptment setup

### ISSUE THREAD

**Issue by jrabek** [facebook/augmented-traffic-control#122]
Augmented traffic control is a great project.  Currently though new users of the project will need to set up a router with a box behind it to run ATC on before they can check it out.  I think it would be immensely helpful to new users to have instructions for a setup that does not require any additional equipment.  The same instructions could serve as a basis for running automated tests in a/the cloud following a build.

The basic setup I was thinking would be interesting/useful would be to have a Vagrantfile plus other scripts that would create a separate virtualbox test instance that would use the ATC virtualbox instance as a gateway.  A new user could then play with running apps in the test instance and play with changing the traffic conditioning profile used.  Automated tests could also be run on the test instance and the traffic shaping profile used could be changed on the fly during the running of the test.

The test instance would have two network interfaces, one that could be accessed from the host OS, and another that is on a private network with the ATC instance.  This could be done with network namespaces (http://man7.org/linux/man-pages/man8/ip-netns.8.html) or perhaps with docker.

This is a feature request and we can discuss here or on IRC.

Thanks!

**Comment by chantra** [comment]
Hi @jrabek,

there is already a chef recipe to deploy atc clients under `chef/atcclient`

Does that work?

We have also helped people in the past to set a VM as a router by sharing the host's wifi connector to the  guest. The setup can be pretty much setup dependent though but we could definitely provide some instruction to get people bootstrapped.

**Comment by jrabek** [comment]
Oh, I completely skipped that directory.  Sorry about that.  That looks very much what I am thinking of.  Thanks for pointing it out.  I'll try playing with that tomorrow.

Regarding getting people bootstrapped, I think just mentioning the atcclient dir in the main README in a quick start section would be useful.  I imagine a lot of people want to try out ATC and not have to A) setup a physical router and linux box to run ATC, or B) Figure out how to configure vagrant/docker/netns to route packets appropriately.

We are looking to use ATC for both live device testing, but also fully automated testing that we can run after every build.  For the live device testing we will definitely set up a physical access point and put ATC behind it, but for the automated testing we want to do something more along the lines of what atcclient is doing.

Thanks again for the prompt answers!
