### ISSUE TITLE
DHCP and Network Traffic Routing configuration

### ISSUE THREAD

**Issue by sgoklani** [facebook/augmented-traffic-control#127]
Hi - i'm setting up ATC as per the following details:

- OS - Ubuntu 14.04 on x86 server (no virtualization)
- Hostname - 'piano'
- Network interfaces - eth0 (192.168.1.0 network) as Internet facing, eth1 (10.10.10.0 network) for DHCP

Till the point of DHCP configuration, it looks to work fine ... the DHCP server on Ubuntu is allocating IP addresses (say 10.10.10.2) to my other machine when i connect (wired) it directly to piano's eth1.

I now need to see all Internet traffic originated from 10.10.10.2 routed to 192.168.1.0 network ... which is not happening right now. Help needed! Many thanks in advance.

Below are the contents of some key files on 'piano' for reference:

/etc/network/interfaces
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet static
address 192.168.1.2
netmask 255.255.255.0
broadcast 192.168.1.255
gateway 192.168.1.1
dns-nameservers 192.168.1.1

auto eth1
iface eth1 inet static
address 10.10.10.1
netmask 255.255.255.0
broadcast 10.10.10.255

/etc/dhcp/dhcpd.conf
ddns-update-style none;
option domain-name "example.org";
option domain-name-servers ns1.example.org, ns2.example.org;
default-lease-time 600;
max-lease-time 7200;
authoritative;
log-facility local7;
subnet 10.10.10.0 netmask 255.255.255.0 {
interface eth1;
range 10.10.10.2 10.10.10.254;
option subnet-mask 255.255.255.0;
option broadcast-address 10.10.10.255;
option routers 10.10.10.1;
}

/etc/default/isc-dhcp-server
INTERFACES="eth1"

/var/log/syslog
-- snip
Jun 10 16:21:45 piano dhcpd: Internet Systems Consortium DHCP Server 4.2.4
Jun 10 16:21:45 piano dhcpd: Copyright 2004-2012 Internet Systems Consortium.
Jun 10 16:21:45 piano dhcpd: All rights reserved.
Jun 10 16:21:45 piano dhcpd: For info, please visit https://www.isc.org/software/dhcp/
Jun 10 16:21:45 piano avahi-daemon[1105]: Server startup complete. Host name is piano.local. Local service cookie is 999834421.
Jun 10 16:21:45 piano dhcpd: Internet Systems Consortium DHCP Server 4.2.4
Jun 10 16:21:45 piano dhcpd: Copyright 2004-2012 Internet Systems Consortium.
Jun 10 16:21:45 piano dhcpd: All rights reserved.
Jun 10 16:21:45 piano dhcpd: For info, please visit https://www.isc.org/software/dhcp/
Jun 10 16:21:45 piano dhcpd: Wrote 2 leases to leases file.
-- snip

-- finally fired the following commands on the command line
# iptables -A FORWARD -o eth0 -i eth1 -s 10.10.10.0/24 -m conntrack --ctstate NEW -j ACCEPT
# iptables -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
# iptables -t nat -F POSTROUTING
# iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
#
# cat /etc/resolv.conf
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 192.168.1.1

**Comment by sgoklani** [comment]
I see some parts of my message are terribly enlarged in font size. Regret the inconvenience.

**Comment by chantra** [comment]
Hi @sgoklani 
Have you enabled forwarding? e.g set:
net.ipv4.ip_forward = 1
in sysctl (/etc/sysctl.conf) and ran sysctl -p

**Comment by sgoklani** [comment]
Yes yes @chantra i had. Sorry forgot to mention.
I didn't do sysctl -p, but i'd rebooted the machine after all configuration.

**Comment by chantra** [comment]
> I now need to see all Internet traffic originated from 10.10.10.2 routed to 192.168.1.0 network ... which is not happening right now.

What do you mean? have you ran tcpdump on the gateway and see no traffic going through?

ok, a few things:
- can you ping 8.8.8.8 ? if so, then this is a DNS issue which is most likely due to the fact that you are not providing any (valid) dns server to the dhcp client. At least the line:
```
option domain-name-servers ns1.example.org, ns2.example.org;
```
Should be replaced by something valid. In your case,
```
option domain-name-servers 192.168.1.1;
```

should be enough. Restart you dhcp service, disconnect/reconnect the client and that should be better.

If that still fail, please runhttps://raw.githubusercontent.com/facebook/augmented-traffic-control/master/utils/dump_system_info.sh and paste the output into a gist: https://gist.github.com/

**Comment by sgoklani** [comment]
No @chantra i've not run tcpdump. Will do that, as well as your other suggestions, and let you know.

**Comment by sgoklani** [comment]
Ah ... the domain-name-servers definition. I changed and it worked.
Tried ATCD also ... works like charm.
Many thanks.

**Comment by chantra** [comment]
Glad to hear that.
