### ISSUE TITLE
ATC is not running.

### ISSUE THREAD

**Issue by PanWangJ** [facebook/augmented-traffic-control#130]
Hi, I've tried to set up the whole project to have a test on network traffic control. When it comes to Running ATC here:

**Running ATC**

Once in the repo, go to the chef/atc directory and run:

    vagrant up trusty

This will take some time before it completes, once the VM is provision, SSH into it:

    vagrant ssh trusty

You should now be able to access ATC at: http://localhost:8080/

I got **vagrant up trusty** and **vagrant ssh trusty** work, but when I tried t o access ATC by the address **http://localhost:8080** , it's not working. My browser just returned the error **Server not found**. I'm not sure what happened nor do I know how to fix it. Could anyone help me with this? Many thanks!

Ps. I'm wondering what's the difference between the first **Running ATC** which will start a web UI at **localhost:8000** and the second **Running ATC** I posted above?

**Comment by agargiulo** [comment]
Is Vagrant doing port magic to make things work on `localhost` @chantra? Or would you need to access the site from localhost inside the VM, I forget how it's setup, but I feel like Vagrant doesn't do that port forwarding.

**Comment by PanWangJ** [comment]
@agargiulo Thanks for the replying. Had worked on this problem for a couple of hours, I'm still confused and stuck here......

**Comment by chantra** [comment]
@PanWangJ 

As @agargiulo mentioned, vagrant is forwarding ports.

In the VM:
* atcd is listening on port 9000
* atcui is listening on port 8000

In the host:
* port 8080 is forwarded to the VM's port 8000

Hence, you can connect to atcui from the host by going to http://localhost:8080

To find out what may prevent the set up from working, can you check a few things:
# in the VM
* is atcui running and bound to port 8000, can you see it running using `ps` and that it is listening on port 8000 using `netstat -lpnt`

* can you actually connect to localhost:8000 maybe using elinks as in:
```
elinks http://localhost:8000
```

# In the Host
Is anything already bound to port 8080? did you get any error when running vragrant up?

**Comment by PanWangJ** [comment]
@chantra I've tried what you told me to do, the result:

**in the VM**
atcui is not bound to port 8000 as there is no sign of it running and listening on port 8000 at all.
cannot connect to localhost:8000 using elinks as well.

**in the Host**
I didn't find anything already bound to port 8080.

So I guess maybe there is something wrong with the **VM**? Actually in your post you said **atcd** is listening on port 9000 and **atcui** is listening on port 8000, my question is I didn't start the **atcd** and **atcui** in the VM, how could them be listening to those ports? I'm not quite sure about this, need your more help. 

Thanks!

**Comment by PanWangJ** [comment]
@chantra I forgot to mention that I did get error about missing plugins of **vagrant-berkshelf** and **vagrant-omnibus** when running vagrant up for the first time. Then I solved this problem and get no errors when running vagrant up again.

**Comment by chantra** [comment]
@PanWangJ  you will need to run 

```
vagrant up --provision trusty
```
in order to get vagrant to provision the vm via chef. Now that the VM exists, vagrant will not provision it when running `vagrant up`

**Comment by PanWangJ** [comment]
@chantra I tried the command `vagrant up --provision trusty` but it seems to be no difference? I still can't get ATC running. Is there anything that I missed? 

**The command log:**

pan@pan-Lenovo-Product:~/Downloads/atc/chef/atc$ vagrant up --provision trusty
Bringing machine 'trusty' up with 'virtualbox' provider...
==> trusty: Loading Berkshelf datafile...
==> trusty: Sharing cookbooks with VM
==> trusty: Checking if box 'chef/ubuntu-14.04' is up to date...
==> trusty: VirtualBox VM is already running.
pan@pan-Lenovo-Product:~/Downloads/atc/chef/atc$

**Comment by chantra** [comment]
Vagrant is telling you that the VM is already running. Turn it off first:
```
vagrant halt trusty
```

and then up

**Comment by PanWangJ** [comment]
@chantra I delete the already existed VM and using the command `vagrant up --provision trusty` to get a new VM. And it's all working now, I'm able to access localhost:8080. Problem solved!

Thanks a lot for your help!!!

**Comment by chantra** [comment]
You are welcome @PanWangJ
