### ISSUE TITLE
How to use ATC to control the network of our own application?

### ISSUE THREAD

**Issue by PanWangJ** [facebook/augmented-traffic-control#132]
I've managed to get ATC running in the VM and have access to **http://localhost:8080** from the host machine with the great help of @chantra (Thanks). Those profiles are already well imported and I can see changes taking place while select different profiles.

Then I tried to make everything else works. By that I mean I want to know how to use ATC to control my application's network. But I'm stuck here, in the deployment process I got to install ATC on my host machine as well as the VM. 

For my understanding, those profiles works on the VM, different profiles stand for different network conditions, thus by applying those profiles I can change the network condition of the VM (not sure if I'm right). But what I want is to control the network of other devices (My Android phone or iPhone etc). What should I do? What is the **Right Way** to work with ATC?  Actually I think I have some basic issues in understanding **ATC**. Please help me. Thanks!

**Comment by chantra** [comment]
ATC must be a router handling the traffic of your devices (Android phone...), like the gateway of your devices.
The devices will then connect to the atc ui and select the type of traffic shaping they want.
The vagrant set up is meant for testing/developing atc.

**Comment by PanWangJ** [comment]
@chantra I've looked around those closed issues and found out that issue 83 kind of answered my question, and I finally get ATC works. Thanks a lot! I think I should write down the process of me getting ATC to work in case anyone else encountered the same problem:

1. Install ATC on a **Linux** based OS by following the docs. (I didn't used the VM)
2. Make sure that the machine that ATC installed on has two **Network Cards**, by that I mean one card is connected to a cable and another one (normally a wireless chip) acts as a router. As for how to make the machine looks like a router, it's quite easy. Just create a WiFi hotspot, tutorials can be found on the internet.
3. Connect your device (laptops or phones) to the WiFi hotspot (namely the Machine that acts as a router and has ATC installed on). 
4. On your device, open the browser and open **ip_of_the_router:8000/atc_demo_ui**. Here, the ip address of the machine (router) can be get by open a terminal in the machine and type command `ifconfig`. Eg, my machine's ip address is **10.42.0.1**, then I should type **10.42.0.1:8000/atc_demo_ui** to access the control panel of ATC to control the internet connection of my device.
5. Play around with ATC with those pre-installed profiles or create your own profiles to enjoy the power of ATC.

Hope this will help. Thanks again! @chantra

**Comment by chantra** [comment]
:+1: 
@PanWangJ thanks for writing it down, it will surely help others going through the same process.
