### ISSUE TITLE
How to shape other devices' traffic with ATC?

### ISSUE THREAD

**Issue by PanWangJ** [facebook/augmented-traffic-control#134]
I've checked the document and found ATC employs a token-based authentication system to allow devices to securely shape others. I did follow the instruction about how to use this token-based authentication system, but I've got problems to make it work. 

It seems that the **validation time** of each token is set to **60s** by default, is it possible to change the time period and if so how? 

Another problem is that I failed to get the controlling device to control the traffic of the controlled device with the token. Here is my step:

1. My Desktop(**controlling device ip:10.42.0.1**) installed with Ubuntu set as the router with ATC running on it, and my laptop(**controlled device ip:10.42.0.115**) connected to the hotspot my desktop created. I've managed to shape my laptop's network when accessing the address `http://10.42.0.1:8000/atc_demo_ui`.
2. I followed the instruction of retrieving the token from my laptop by using command:  
```
curl -i -H 'Accept: application/json; indent=2' http://10.42.0.1:8000/api/v1/token/
``` 
3. Then I authorised the desktop with the command: 
```
curl -i -XPOST -d '@-' -H 'Content-Type: application/json; indent=2' http://10.42.0.1:8000/api/v1/auth/10.42.0.115/
{
    "token": whatever token
}
```

What should I do next? I've tried several ways trying to control the laptop's network but not working. Please help me, thanks.

**Comment by chantra** [comment]
@zfjagann can you help with this?

@PanWangJ at this stage, your desktop should be able to shape the controlled device  via the API under
http://10.42.0.1:8000/api/v1/shape/10.42.0.115/

If you are using master, you should be able to do that through the UI.

**Comment by PanWangJ** [comment]
@chantra Thank you, for some reason the desktop is not able to shape the traffic of the laptop yesterday. I've tried to do the shaping this morning again and it's working now. I have no idea what caused the problem, anyway the shaping is working now. As for the validation time of the token, still need your or @zfjagann 's help. Thanks again!

**Comment by chantra** [comment]
@PanWangJ 
The access token validity time is set in https://github.com/facebook/augmented-traffic-control/blob/master/atc/atcd/atcd/access_manager.py#L56

and is currently set to 60 seconds.

It would be pretty straightforward to hack a configureable timeout in https://github.com/facebook/augmented-traffic-control/blob/master/atc/atcd/atcd/AtcdThriftHandlerTask.py and pass this to `AccessManager` initialization.

I will open a separate issue for this. PRs are welcome :smile:

**Comment by PanWangJ** [comment]
Thanks you @chantra

**Comment by muthurajbharathi** [comment]
hi How can i specify IP address of  device needs to be shaped in a payload of all API's. what is the parameter name.

**Comment by zfjagann** [comment]
@muthurajbharathi please open a new issue with your question so we can respond to it independently of the discussion on this issue.
