### ISSUE TITLE
downlink bandwidth have not changed ，only 8kbps 

### ISSUE THREAD

**Issue by tienfeek** [facebook/augmented-traffic-control#135]
downlink bandwidth have not changed ，when downlink banwidth is 40-30000kbps ，  only about 8Kbs 。but uplink have changed， why？

**Comment by chantra** [comment]
Hi @tienfeek I am not really sure what your issue is.
You are saying that whatever downlink bandwidth setting you are changing, you always end up getting 8kbps?
But uplink changes are accurate?

https://github.com/facebook/augmented-traffic-control/issues/86#issuecomment-89889404 may help you.

**Comment by chantra** [comment]
@tienfeek We did not get any update from you side since you opened the issue. Hopefully, my previous comment will help fix your issue. I will close this issue for now. Feel free to open a new one if your issue is still not fix or try to catch us on freenode #atcd
