### ISSUE TITLE
Configureable Access token timeout

### ISSUE THREAD

**Issue by chantra** [facebook/augmented-traffic-control#136]
Currently, the access token validity is hardcoded to 60s. We could make this configurable at atcd start time and initialize `AccessManager` accordingly.

see https://github.com/facebook/augmented-traffic-control/issues/134#issuecomment-122023734 for context.

**Comment by zfjagann** [comment]
FYI the golang branch includes this now via the `-token-timeout` flag. 72e7a54068e28c51a818768dbd20dfe70f15823c

**Comment by chantra** [comment]
ok, given that we are moving to the golang implementation, it is not worth putting the effort in supporting the python version
