### ISSUE TITLE
Bandwidth modelling not happening as expected

### ISSUE THREAD

**Issue by kr-ashok** [facebook/augmented-traffic-control#143]
Hello,

I installed ATC on CentOS 7 laptop which has wireless(interface: wlp3s0) as well as ethernet NIC (interface: enp0s25). Interface "enp0s25" is connected to Internet and I have created a wireless AP on interface "wlp3s0". I have connected clients (mobile) to this AP. I started ATC as follows:

atcd --atcd-wan enp0s25 --atcd-lan wlp3s0 

For web gui:

cd atcui
python manage.py runserver 0.0.0.0:8000

Without any ATC profile, I get approx 10 Mbps down/up (speedtest shows this).
I created an ATC profile (using my mobile) with 2 Mbps on both downlink and uplink but after applying the profile my mobile shows approx 0.25 Mbps downlink and approx. 1.75 Mbps uplink. I expected this to be very close to the ATC profile.

Now, my doubt is ATC uses iptables but CentOS 7 uses firewalld and can this cause the above problem. Or, anything else I'm doing wrong here?
Highly appreciate your response.

Thanks

**Comment by chantra** [comment]
@kr-ashok could you try using `--atcd-dont-drop-packet` ?

this was added in b06f76f0c015aad945deed134ca69b78bafe1cfc . From the changelog you can see a bunch of similar issues along with some explanations.
Let me know if that helps.

**Comment by kr-ashok** [comment]
Hi Chantra,

Thanks for the suggestion. I will try this out and post my observation soon.

Thanks

**Comment by chantra** [comment]
Hi @kr-ashok do you have any updates on this?

**Comment by JohnnyWuMigme** [comment]
I had same problem as he described and the solution is working perfect for me. Thanks chantra!

**Comment by zfjagann** [comment]
Closing since the issue was resolved. Please reopen if you need any more help. Thanks!
