### ISSUE TITLE
Hosting environment for Facebook ATU

### ISSUE THREAD

**Issue by salmanchauhan** [facebook/augmented-traffic-control#145]
Hi Team,
I want to set up my test environment using Facebook ATU. My question  is 
1) Can I set up this environment on Virtual Linux OS where I have Host OS Mac and I want to control my WiFi Hotspot internet speed. I have created Hotspot on Linux sharing internet from Ethernet to WiFi.

2) If above case is not possible than do I need my Real Linux Machine to be directly connected with my router to control network speed.

Thanks in Advance !!!

**Comment by chantra** [comment]
Hi @salmanchauhan 

> 1) Can I set up this environment on Virtual Linux OS where I have Host OS Mac and I want to control my WiFi Hotspot internet speed. I have created Hotspot on Linux sharing internet from Ethernet to WiFi.

Yes you can but you are not going to get the best behaviour with that setup.

In any cases, what matters is that the traffic you want to shape get routed through the ATC box.


Does that answer your question?

**Comment by salmanchauhan** [comment]
Thanks @chantra Yes it answers my question. Can you suggest me what will be the best solution to implement this test environment to get best behaviour ?

**Comment by chantra** [comment]
@salmanchauhan 
The best behaviour will be using physical hardware. That being said, using a virtual box will be enough to get testing done and get a good grasp of your application behaviour.
