### ISSUE TITLE
Multiple users situation

### ISSUE THREAD

**Issue by zhangxiaang** [facebook/augmented-traffic-control#146]
if here are multiple users ， one of them changed the configuration(profiles) in the 'atc_demo_ui',will other users be affected? (there are in the same lan)?

if the mode of connectting is NAT , all devices will get shaped using the same shaping rules?

**Comment by chantra** [comment]
Hi @zhangxiaang 
It ATC sees all the users as coming from the same ip then yes, they will all be shaped with the same shaping rules.
ATC will apply shaping on a per IP basis so it needs to be able to see the users with individual IP. NAT should be applied after ATC, not before.
Does that answer your question?

**Comment by zhangxiaang** [comment]
yeap,i get it .  thank you very much!!!

**Comment by chantra** [comment]
Great!
