### ISSUE TITLE
ATC is not running

### ISSUE THREAD

**Issue by bobruub** [facebook/augmented-traffic-control#147]
HI all,

installed ATC as described in documentation but when I visit http://localhost:8000/atc_demo_ui/ it tells me that "ATC is not running"

I've started the daemon sudo ./dev/atc/venv/bin/atcd

I can see an open ports for 8000 (the gui which obviously works) and can see an open port on 9090. 

I can also telnet to both ports from the same machine.

Its running ubuntu 14 running in virtualbox.

Any idea what I'm missing here?

**Comment by chantra** [comment]
@bobuub so apparently the ui is not able to connect to atcd. Can you copy the logs from atcd to https://gist.github.com/ so we may get some insight on what may not work.
I assume you have tried reloading the webpage after you have started atcd so give a chance to the ui to reconnect.

If you use the web developer functionality of your web browser, do you get any javascript errors? Can you post those pls.

**Comment by bobruub** [comment]
I start ATCD thusly:
~/dev/atc/venv/bin$ sudo ./atcd
then the UI
python manage.py runserver 0.0.0.0:8000

as you suggested I tried to refresh the page but the same result :(

I see no error or warnings (apart from ATC not running) on the UI.
I also tried in a second browser (chrome) but same issues.

Not sure where logs are located, the syslog is below
Aug 21 14:55:08 tim-VirtualBox AtcdNBServerTask Server Started on 127.0.0.1:9090
Aug 21 14:55:08 tim-VirtualBox Calling initialize_shaping_system
Aug 21 14:55:08 tim-VirtualBox Running /sbin/iptables -t mangle -F FORWARD
Aug 21 14:55:08 tim-VirtualBox deleting root QDisc on eth1
Aug 21 14:55:08 tim-VirtualBox setting root qdisc on eth1
Aug 21 14:55:08 tim-VirtualBox deleting root QDisc on eth0
Aug 21 14:55:08 tim-VirtualBox setting root qdisc on eth0
Aug 21 14:55:08 tim-VirtualBox Restoring shaped connection from DB
Aug 21 14:55:08 tim-VirtualBox All tasks started
Aug 21 14:55:08 tim-VirtualBox VService Active.  Awaiting graceful shutdown.
Aug 21 14:55:08 tim-VirtualBox Request requestToken(127.0.0.1, 259200)

**Comment by bobruub** [comment]
QApologies, just found this in developer tools for firefox..

"You are using the in-browser JSX transformer. Be sure to precompile your JSX for production - http://facebook.github.io/react/docs/tooling-integration.html#jsx" JSXTransformer-0.13.3.js:314:1
"Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of ProfileList. See https://fb.me/react-warning-keys for more information." react-0.13.3.js:19588:7
TypeError: result.json is undefined atc_demo_ui:208:8
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.

**Comment by cachenbach** [comment]
@bobruub: could you please try: 
pip freeze | grep djangorestframework

If your see version 3.2.2: I was able to solve this issue with:
sudo pip uninstall djangorestframework
sudo pip install djangorestframework==3.1.2

**Comment by chantra** [comment]
@cachenbach you are saying that djangorestframework 3.2.X :s I will try to reproduce that,

**Comment by cachenbach** [comment]
@chantra yes, presumably 3.2.X. In may case it was 3.2.2

From http://www.django-rest-framework.org/topics/3.2-announcement/ :
"request.DATA was put on the deprecation path in 3.0. It has now been removed and its usage will result in an error. Use the more pythonic style of request.data instead."

I think that was the problem.

**Comment by chantra** [comment]
@cachenbach that seems to match. Running the UI using `python manage.py runserver 0.0.0.0:8000` spits out https://gist.github.com/chantra/16e788790ee03481ac7c

**Comment by bobruub** [comment]
thanks for the feedback.

I went back to teh previous version but still getting the same issue :(

tim@tim-VirtualBox:~$ pip freeze | grep djangorestframework
djangorestframework==3.1.2
tim@tim-VirtualBox:~$ 

[21/Aug/2015 22:16:26] "GET /api/v1/token/ HTTP/1.1" 200 77
[21/Aug/2015 22:16:28] "POST /api/v1/shape/ HTTP/1.1" 500 13372
[21/Aug/2015 22:16:29] "GET /api/v1/token/ HTTP/1.1" 200 77
[21/Aug/2015 22:16:30] "POST /api/v1/shape/ HTTP/1.1" 500 13372
[21/Aug/2015 22:16:31] "POST /api/v1/shape/ HTTP/1.1" 500 13372
[21/Aug/2015 22:16:31] "POST /api/v1/shape/ HTTP/1.1" 500 13372
[21/Aug/2015 22:16:32] "GET /api/v1/token/ HTTP/1.1" 200 77

**Comment by chantra** [comment]
@bobruub Can you just reprovision it all together from the new master?

**Comment by bobruub** [comment]
Hi all,

started from scratch, new virtualbox ubuntu, new install and now it works correctly :)

Thanks for the heads up. I've got some more questions on config but I will have a try to resolve them myself first.

**Comment by chantra** [comment]
Good to hear! Hopefully the READMEs will answer your questions, if not feel free to hop on IRC or open a new task.
