### ISSUE TITLE
how to route to ATC interface

### ISSUE THREAD

**Issue by bobruub** [facebook/augmented-traffic-control#150]
Hi all,

this is more of a networking issue but hoping someone here can advise.

I managed to get ATC running (thanks for the assist) but am not sure how to route to the gateway.

ifconfig:

tim@tim-VirtualBox:~$ ifconfig
eth0      Link encap:Ethernet  HWaddr 08:00:27:30:c8:32  
          inet addr:10.3.18.114  Bcast:10.3.18.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe30:c832/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:698790 errors:0 dropped:0 overruns:0 frame:0
          TX packets:385858 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:810829037 (810.8 MB)  TX bytes:30595418 (30.5 MB)

eth1      Link encap:Ethernet  HWaddr 08:00:27:fc:d9:4c  
          inet addr:10.3.18.116  Bcast:10.3.18.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fefc:d94c/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:21286 errors:0 dropped:0 overruns:0 frame:0
          TX packets:776 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:2125499 (2.1 MB)  TX bytes:95302 (95.3 KB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:52364 errors:0 dropped:0 overruns:0 frame:0
          TX packets:52364 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:6260308 (6.2 MB)  TX bytes:6260308 (6.2 MB)

I executed atc with the following command:

sudo ~/dev/atc/venv/bin/atcd --thrift-host 10.3.18.116 --thrift-port 9090 --atcd-lan eth0 --atcd-wan eth1 

I can telnet to port 10.3.18.116 on port 9090 so its listening OK.

On a windows server I was trying to route traffic to speedof.me (216.121.90.10)

route ADD -p 216.121.90.10 MASK 255.255.255.255 10.3.18.116 METRIC 1

When I try to tracert I get lots of Requests Timeouts.

Any

**Comment by chantra** [comment]
@bobruub if you take atc out of the picture, I assume it is not working either.
I would say the issue may be that you are not either:
- forwarding the traffic (`sysctl net.ipv4.ip_forward` returns a value of 0)
- natting the traffic and the next hop does not know how to send the traffic back to atc

**Comment by chantra** [comment]
@bobruub does that answer your question? I will be closing this issue for now. If you still need more assistance, please feel free to open a new ticket on get us on irc.
