### ISSUE TITLE
atc is not running

### ISSUE THREAD

**Issue by rrohana** [facebook/augmented-traffic-control#153]
Hi 
I successfully installed the tool. 
My wan is eth1 and lan eth0 -- so I lunched the tool as follow : 
      atcd --atcd-lan eth0 --atcd-wan  eth1                

And them run the WEBUI as none sudo user and  successfully logged in. 
But WEBUI shows in yellow " ATC  is not running " 
Thanks

**Comment by chantra** [comment]
There is currently an issue where the pip package of atc may will not work will latest django framework versions.
You have a couple of options here:
- get atc from master
- downgrade django-rest-framework to version 3.0

cc @zfjagann

**Comment by rrohana** [comment]
Thanks a lot man

**Comment by rrohana** [comment]
Hi
Your tool is working great. I Realized its per session. { I need to open the UI from the tested device } 
Is there anyway to make a global per subnet

**Comment by zfjagann** [comment]
Hi @rrohana

 :+1:  Glad you got it working!

In the ATC version currently on github you can only shape specific IPs and not subnets, but shaping subnets is in the TODO list for the next version of ATC which we're working on now.
