### ISSUE TITLE
Cannot shape settings for authorized ip address on atc demo ui

### ISSUE THREAD

**Issue by yershalom** [facebook/augmented-traffic-control#154]
Hi,

I'm trying to shape settings for authorized ip address on atc demo ui.
I'm running the atc with docker.
I can see the authorized addresses but there is no option for select before changing downlink limit for example.
Is there any other way at the web ui to select changes on authorized address?

**Comment by chantra** [comment]
Hi @yershalom 

Sorry for replying this late.... this issue went through the net.

This is correct, there were no UI element allowing to shape a given address. the api has the functionality.
@zfjagann you implemented that bit (token/list of addresses), what was missing to have this functional through the UI? Was the UI only allowing to get a temporary code?

**Comment by chantra** [comment]
@yershalom I guess this answers your question. I will close this issue for now.
We may consider in the future to implement this but for now, we want to keep the ui simple.
Patches are welcome though :)
