### ISSUE TITLE
Atc is not running

### ISSUE THREAD

**Issue by golgoth** [facebook/augmented-traffic-control#155]
Hy, I am having the same issue than a previous ticket here, with the yellow warning "ATC is not running".
I got an error in the browser's console : 

GET XHR  http://localhost:8000/api/v1/shape/
GET XHR  http://localhost:8000/api/v1/shape/
TypeError: result.json is undefined

So I downgraded django rest framework to 3.0 as previously said, and tried to install from source, but I'm still having the issue.

**Comment by chantra** [comment]
Hi,
Did you restart at cuisine after downgrading by any chance?

**Comment by golgoth** [comment]
What do you mean by "cuisine" ?
I rebooted several time, and also uninstalled all the packages to redo all
the steps, but I still get this error message.

Adrien Duffy--Coissard


*EA DICE Ops Master thesis internEngineering student at KTH - INSA de
LyonComputer sciences - 6th year - Distributed systems*

2015-10-09 17:04 GMT+02:00 chantra <notifications@github.com>:

**Comment by chantra** [comment]
autocorrect failed....
Did you restart `atcui` .....

I guess we are going do need some logs here. It feels like it is related to #147 though.

Can you run the atcui process from the command line and put the logs in a gist. Make sure to enable your virtualenv if you use one and then run:

```
python manage.py runserver 0.0.0.0:8000
```

**Comment by golgoth** [comment]
My machine is not fully set up yet, I just have eth0 and lo interfaces, so I launched it with 
```
sudo atcd --atcd-wan eth0 --atcd-lan lo
```
Should it be a problem ?
Yes, it seems related, but since it was solved in #147 by reinstalling Linux, maybe it's a problem that is still here ? Or something I do wrong...

Everything seems to be fine, and I guess something is working since if I shutdown atcd then in the notification box appear :
```
Could not fetch auth info: [object Object]
```
Maybe it is just a graphic problem with the "Atc is not running" displayed while it should not ?

Here is the gist :
https://gist.github.com/c546558e986116dc9bf3.git

**Comment by chantra** [comment]
Hi @golgoth 

First of all, the solution is not about reinstalling Linux. In #147 a VM was provisioned, so it was easier to just reprovision rather than fiddle around.

The command you are running will prevent shaping from working, but not the UI, so you should be able to request shaping, unshape .... but shaping will not take effect due to routing.

Your gist is not accessible, is it set to private?

**Comment by golgoth** [comment]
I updated the comment with the right link to gist:
https://gist.github.com/golgoth/c546558e986116dc9bf3
Well, I can create profiles, just that the yellow button is still here. I may not be able to work on that for a while, maybe I will eventually find out that shaping is working well !
I may also try to install it on another VM, that should work then !

**Comment by chantra** [comment]
from the gist, we can see that the ui is able to talk to the atcd daemon. Can you send the logs from running the UI with 
```
python manage.py runserver 0.0.0.0:8000
```

Also, can you send the output of
```
pip freeze
```

Tks

**Comment by chantra** [comment]
This task is pretty old and staled so I will close it for now. @golgoth please feel free to open a new task if you still need assistance.

**Comment by golgoth** [comment]
Yes, sorry but I was out of this for a while, the fact is that I tried on new linux VM and it worked the way it should have, and I tried but was not able to identify what could have gone wrong with the first machine ...
