### ISSUE TITLE
Unable to search the source code.

### ISSUE THREAD

**Issue by Nandini-Agg** [facebook/augmented-traffic-control#160]
Hey, I am facing some issue regarding source code. I am not able to search the source code of ATC from my system since it has already been deployed to my system.
Anybody please guide me to overcome this issue.

**Comment by agargiulo** [comment]
What are you trying to search for? How are you searching for it? And how are you deploying it?
Also, searching through the source code can be done by going to the search box at the top of this page, it will search only this repo by default.

**Comment by chantra** [comment]
you can also run something along:
```
python -c 'import atcd; print atcd'
```

That would give you a hint on where files are installed. But as @agargiulo mentioned, if you are only looking to search the codebase, you should just use github or clone the repo.

**Comment by zfjagann** [comment]
Closing this since the search issue seems to have been resolved. Please re-open the issue if you still have issues.
