### ISSUE TITLE
Cannot connect to atc from a remote machine

### ISSUE THREAD

**Issue by stream101** [facebook/augmented-traffic-control#161]
I follow the configuration steps in #132.  However, I couldn't be able to connect to atc (on the control machine) from a remote machine.

On the control machine, you can see the ip address of wlan is **10.42.0.1**. 
```
eth0      Link encap:Ethernet  HWaddr 38:60:77:4c:cd:6b
          inet addr:132.239.17.127  Bcast:132.239.17.255  Mask:255.255.255.0
          inet6 addr: fe80::3a60:77ff:fe4c:cd6b/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:232275 errors:0 dropped:5440 overruns:0 frame:0
          TX packets:50749 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:136186840 (136.1 MB)  TX bytes:8167263 (8.1 MB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:90509 errors:0 dropped:0 overruns:0 frame:0
          TX packets:90509 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:22499724 (22.4 MB)  TX bytes:22499724 (22.4 MB)

wlan0     Link encap:Ethernet  HWaddr ac:81:12:84:b6:af
          inet addr:10.42.0.1  Bcast:10.42.0.255  Mask:255.255.255.0
          inet6 addr: fe80::ae81:12ff:fe84:b6af/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:258059 errors:0 dropped:21 overruns:0 frame:0
          TX packets:19281 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:23294410 (23.2 MB)  TX bytes:10220298 (10.2 MB)
```

I set the control machine as the AP and use the other remote machine to connect to the hotspot. 

Now I can open the atc demo UI on the control machine at **0.0.0.0:8000/atc_demo_ui/**.

But on the remote machine, when I try to connect  **10.42.0.1/atc_demo_ui/**, the webpage cannot be loaded. I have no problem opening other webpages on the remote machine through the hotspot.

Please help me !! A lot of appreciation !!

**Comment by zfjagann** [comment]
On your remote box make sure you're on the same network as the wireless link on the ATC box.

Can you run the following commands and paste the output into [gist](https://gist.github.com/)? That would be helpful for helping diagnose what's wrong.

- `ip addr`
- `ip route list`
- `ip route get 10.42.0.1`

**Comment by stream101** [comment]
The remote machine is Mac. 
$ route get 10.42.0.1
```
route get  10.42.0.1
   route to: 10.42.0.1
destination: 10.42.0.1
  interface: en0
      flags: <UP,HOST,DONE,LLINFO,WASCLONED,IFSCOPE,IFREF,ROUTER>
 recvpipe  sendpipe  ssthresh  rtt,msec    rttvar  hopcount      mtu     expire
       0         0         0         0         0         0      1500      1190
```
Check ip address: 
$ ifconfig
```
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether 3c:15:c2:e4:b4:18
	inet6 fe80::3e15:c2ff:fee4:b418%en0 prefixlen 64 scopeid 0x4
	inet 10.42.0.100 netmask 0xffffff00 broadcast 10.42.0.255
	nd6 options=1<PERFORMNUD>
	media: autoselect
	status: active
```
I think the remote machine and control machine are in the same network, because I can use the control machine's hotspot to browse webpage. 

Any suggestions ?

**Comment by zfjagann** [comment]
What happens when you load `10.42.0.1/atc_demo_ui/` from a browser on the control machine (the machine running ATC)?

**Comment by zfjagann** [comment]
Hey @stream101 do you still need help with this?
Please let us know if there's something we can do to help you.

**Comment by stream101** [comment]
I didn't get it solved, but since I've closed the ATC service on my desktop, I couldn't try your suggestions. Thanks very much for your help though! @zfjagann
