### ISSUE TITLE
Replace qdisc instead of delete/create

### ISSUE THREAD

**Issue by zfjagann** [facebook/augmented-traffic-control#173]
We should replace the qdisc instead of calling successively delete/create. This causes extra noise in the logs and potentially failure on some types of interface (e.g. `veth`).

Waiting for [netlink#64](https://github.com/vishvananda/netlink/pull/64).

**Comment by chantra** [comment]
it was merged upstream. We should be able to go ahead with this one.

**Comment by chantra** [comment]
So I tried https://gist.github.com/chantra/19de76aea31414acd262 but while it works on the first start of atcd, it fails on the second.

To properly fix this I have the feeling this is going to take a lot of investigation which may not be worth it now.
Basically what happens is that some qdisc have no handle (like the pfifo_fast that comes default):
```
root@89a942020e54:/usr/src/myapp# ./bin/atcd -wan wan1 -lan lan1
2015/11/25 08:16:36 No config file loaded.
2015/11/25 08:16:36 Command: /sbin/iptables -t mangle -F FORWARD
2015/11/25 08:16:36 Command: /sbin/ip6tables -t mangle -F FORWARD
2015/11/25 08:16:36 warning: Could not delete root qdisc (wan1): no such file or directory
2015/11/25 08:16:36 Starting the thrift server on 127.0.0.1:9090
^Croot@89a942020e54:/usr/src/myapp# tc qdisc del dev wan1 root
root@89a942020e54:/usr/src/myapp# tc qdisc del dev wan1 root
RTNETLINK answers: No such file or directory
root@89a942020e54:/usr/src/myapp# tc qdisc show dev lan1
qdisc htb 1: root refcnt 2 r2q 10 default 0 direct_packets_stat 0 direct_qlen 1000
root@89a942020e54:/usr/src/myapp# tc qdisc show dev wan1
qdisc pfifo_fast 0: root refcnt 2 bands 3 priomap  1 2 2 2 1 2 0 0 1 1 1 1 1 1 1 1
```

When failing to delete, we are hitting the same issue then tc.

**Comment by chantra** [comment]
closing for now as it does not seem worth it until we really need it for some specific use cases.
