### ISSUE TITLE
`make` == `make test`

### ISSUE THREAD

**Issue by zfjagann** [facebook/augmented-traffic-control#193]
This is bad. `make` should be equivalent to `make tests` and `make bin` in that order.

**Comment by chantra** [comment]
I disagree. make should build the binaries, not the tests. When I get sources, I expect make to just build what I care about (e.g the binaries), make tests is more for developers.

**Comment by zfjagann** [comment]
Well either way, that's not what it does now.

https://github.com/facebook/augmented-traffic-control/blob/golang/Makefile#L30

**Comment by chantra** [comment]
I know, and this is what I am fixing in #192 . e.g `make` == `make bin` and tests are ran using `make tests`

**Comment by zfjagann** [comment]
I see now!
