### ISSUE TITLE
api wont work behind a proxy

### ISSUE THREAD

**Issue by chantra** [facebook/augmented-traffic-control#197]
https://github.com/facebook/augmented-traffic-control/blob/973c6bff1813fb1c427404f17475473f39f91c49/src/api/assets.go#L29

will not detect the correct ip when hidden behind a proxy.

We should check the X-Forwarded-For/HTTP_X_REAL_IP headers.

**Comment by chantra** [comment]
Assigning to @zfjagann there is already some code and FIXMEs about it

**Comment by zfjagann** [comment]
The code you're looking for is here:
https://github.com/facebook/augmented-traffic-control/blob/973c6bff1813fb1c427404f17475473f39f91c49/src/api/utils.go#L144

We just need to make `assets.go:29` use this and make the `GetClientAddr` function smarter.

**Comment by chantra** [comment]
Just like https://github.com/facebook/augmented-traffic-control/blob/master/atc/django-atc-api/atc_api/utils.py we should only allow headers to be set by allowed proxies.

**Comment by zfjagann** [comment]
Fixed by #200
