### ISSUE TITLE
Server js/css using http.FileServer

### ISSUE THREAD

**Issue by chantra** [facebook/augmented-traffic-control#198]
It will be more flexible for people to be able to specific a directory with static resources rather than packaging them directly in the binary.
While packaging directly in the binary makes deployment easier, it makes many other operations much harder.
For example, iterating on JS changes is much harder and requires atc_api to be rebuilt + restarted. People will be stuck with the UI shipped with the source, serving static files will make it easier to hack on it.
Also, currently we still need to push the the host that the ui should connect to (v4 + v6) in index.html but this should really just be a UI call to discover the endpoints. index will the be pretty dummy and only used to render on a client and let it pull the right JS/CSS

http://www.alexedwards.net/blog/serving-static-sites-with-go for serving files with golang, but that may be just pushed to a proxy instead.

**Comment by zfjagann** [comment]
Let's be careful here. I'm hesistant to make development easier at the expense of runtime complexity.

We can add an option to use a directory and `http.FileServer` instead of bundled static files, but I think it'd be best to leave bundled static files as the default behavior to make deployment easier.

**Comment by chantra** [comment]
after IRL discussion, we decided to still bundle the static resources in the generated binary and be able to provide a cmd line flag that will allow to override that with on disk resources.

**Comment by chantra** [comment]
this was fixed in https://github.com/facebook/augmented-traffic-control/commit/1f054177ba7dd4d5a5637e1e6e9d5ec6fd70c1c0 right?

**Comment by zfjagann** [comment]
Yes, thanks!
