### ISSUE TITLE
updating shaping fails

### ISSUE THREAD

**Issue by chantra** [facebook/augmented-traffic-control#221]
When updating an existing shaping, it currently fails because it seems the old shaping is not deleted before hand.

```
root@e58d9df24a68:/usr/src/myapp# 2015/12/13 00:09:59 Shaping group 1
2015/12/13 00:09:59 Error: Could not shape: Internal error processing shape_group: Could not shape lan(lan1) interface: Could not create htb class: file exists
```

**Comment by chantra** [comment]
#173 would fix this.

**Comment by zfjagann** [comment]
We can fix this more easily by deleting the shaping before applying a new shaping. I'll take care of this.

**Comment by chantra** [comment]
closing given that #223 landed
