### ISSUE TITLE
htb class setting fails on centos 6 (2.6.32 kernel)

### ISSUE THREAD

**Issue by chantra** [facebook/augmented-traffic-control#225]
As much as we should mainly support >= 3 kernels, I want this used case to be supported.

Currently, on 2.6.32, setting htb class fails with something along:
`'invalid argument'`

Comparing the code I wrote in https://github.com/vishvananda/netlink for HTB class with the `iproute2` code, we are not setting RTAB and CTAB so the fix would be to set those in https://github.com/vishvananda/netlink

Digging a bit further, this is where it fails in 2.6.32: 
http://lxr.free-electrons.com/source/net/sched/sch_htb.c?v=2.6.32#L1321
while on 3.10 it does not seem those are used anymore:
http://lxr.free-electrons.com/source/net/sched/sch_htb.c?v=3.10#L1332

but back to some extend in 3.12 http://lxr.free-electrons.com/source/net/sched/sch_htb.c?v=3.12#L1368 but it would not fail though.

Most of the code is already in the netlink code, so the fix should be quite simple.

**Comment by chantra** [comment]
cc @zfjagann

**Comment by chantra** [comment]
https://gist.github.com/chantra/fb5367768078790e5ec0 would get netlink's hb class working on 2.6.32

**Comment by zfjagann** [comment]
Awesome! Let's get this in.

**Comment by chantra** [comment]
Well, I need to work a bit more on that patch ATM, but we may want to locally use it.

**Comment by chantra** [comment]
I fixed it in the upstream netlink library. closing this now
