### ISSUE TITLE
Localhost Does not work

### ISSUE THREAD

**Issue by birdman2005** [facebook/augmented-traffic-control#226]
only ip works, and the mainpage cannot load the theme

**Comment by chantra** [comment]
@birdman2005 can you be more specific about the issue you are having? How are you shaping the devices? from what host?

Are you refering to #216 when you say that the theme cannot load?

**Comment by birdman2005** [comment]
@chantra nice work， the them problem are the same as #216 。and another problem is i can not open the main page by entering http://localhost:8000，but ip。

**Comment by chantra** [comment]
@birdman2005 you should not really open localhost:8000 as that will make you shape localhost which is not what you want. What you want is, from a device you want to shape, connect to http://atc_ip:8000 and shape it.

what does `netstat -lpnt` reports? Can you send the output to gist: https://gist.github.com/ and make the gist public.

**Comment by birdman2005** [comment]
@chantra @MiteshShah  i solved the theme problem by modify the base.html and i post thenetstat -lpnt on to gist

**Comment by chantra** [comment]
I guess this is the link to the gist: https://gist.github.com/birdman2005/a5e9741c709cea3d19c7

When you say you cannot connect to localhost:8000 where are you doing this? on the machine that runs atc?
There is no good reason for you to do this anyway (unless you are using the api). But given the netstat output, it should be working just fine, unless you are trying to access localhost:8000 from another machine, which is wrong given that the service is running on the atc hosts and not on any other machines in you network.

I believe this is not preventing you from getting atc to work though,

**Comment by chantra** [comment]
@birdman2005 do you still have the issue? it seems to me like everything is working as expected.

**Comment by chantra** [comment]
@birdman2005 I did not hear back from you. Hopefully, everything is working as expected. I will close this issue for now, feel free to open a new issue or hop in irc if you need more help.
