### ISSUE TITLE
Always told me the interfaces does not exist

### ISSUE THREAD

**Issue by ctriptest** [facebook/augmented-traffic-control#227]
Hello, chantra.
I'm a tester from China. Last week I have been learning how to build ATC platform, but I had some problems, I hope to get your help.

I have created the wifi AP within virtual machine(Ubuntu 15.10), but when I excuted the command below, the system always told me that one of the following interfaces does not exist.

command: sudo atcd --atcd-lan wlxe84e06333994 (the interfaces name is my USB WiFi AP name)

I don't know where is mistake, if you can help me?

**Comment by chantra** [comment]
Hi @ctriptest 
Can you send the actual command you are typing and error message.

For one, you are not providing the --atcd-wan command line flag. It will default to eth0, so if you dont have any eth0 on your system, the error is legit.

Please also provide the output of:
`ip a`
and
`ip r`
and copy that to a [gist](https://gist.github.com/) and provide the link to the gist.

**Comment by ctriptest** [comment]
Hi @chantra 
First, thanks for your response.

The Pic1 is my virtual machine's nerwork devices.
![ifconfig](https://cloud.githubusercontent.com/assets/16544057/12150468/e724d3f4-b4e4-11e5-8732-516bdaaa8921.jpg)

The Pic2 is the error message for this command (sudo atcd --atcd-wan eno16777736 --atcd-dont-drop-packet).
![atcd-wan](https://cloud.githubusercontent.com/assets/16544057/12150476/f2018628-b4e4-11e5-826f-dc4869a9e0d3.jpg)

The Pic3 is the error message for this command (sudo atcd --atcd-lan wlxe84e06333994 --atcd-dont-drop-packet)
![atcd-lan](https://cloud.githubusercontent.com/assets/16544057/12150485/f8a6eb6c-b4e4-11e5-82cf-5cb2ff9088ef.jpg)

gist link:<script src="https://gist.github.com/ctriptest/118cf265578281529c2f.js"></script>

**Comment by zfjagann** [comment]
Hi @ctriptest, please try running atcd using both the `--atcd-wan` and `--atcd-lan` options.
For example using your interfaces:

    sudo atcd --atcd-lan wlxe84e06333994 --atcd-wan eno16777736 --atcd-dont-drop-packet

**Comment by ctriptest** [comment]
Hi @zfjagann 
Then I try to run a new command, and I did not see an error message, but it always stay in the debug stage.
![atcd_try](https://cloud.githubusercontent.com/assets/16544057/12162380/2ce6fb4a-b53c-11e5-8706-ab1382cae079.jpg)

**Comment by chantra** [comment]
@ctriptest it is working as expected. This is not debug mode, just the fact that the process is in foreground.
You can use ` --daemon` to get the process to detach ( `--help` will tell you about the different options available).
You can use a daemonizer tool like runit, daemontool to daemonize the process for you or check https://github.com/facebook/augmented-traffic-control/blob/master/chef/atc/files/default/init.d/atcd.debian for an example init script.

**Comment by chantra** [comment]
In any cases, atc is working as expected as far as the logs are telling us.

**Comment by ctriptest** [comment]
@chantra & @zfjagann 
Thanks for your support again. I will continue to share any information to you.

**Comment by ctriptest** [comment]
@chantra & @zfjagann 
I have successfully deployed the ATC platform at my virtual machines, but I cannot find atc folder path, would you tell me the atc folder path? I want to import the the sample profiles.

The capture is the working monitor information of atc.
![atcd-running](https://cloud.githubusercontent.com/assets/16544057/12171787/9b5af6c6-b587-11e5-9907-83d639c1635a.jpg)

The capture is from my phone, it looks like it is a normal page?
![atcd_running_iphone6sp](https://cloud.githubusercontent.com/assets/16544057/12171917/88af813a-b588-11e5-948b-257d28b7b040.png)

**Comment by ctriptest** [comment]
@chantra 
Which directory I can find the log files? I want to see the data exchange information.
Thanks a lot!

**Comment by zfjagann** [comment]
This looks like #216 to me. I'm not sure what you mean by logging directory. Atcd is logging to your terminal unless you detached it.

You can see the HTTP transfer data by using a command line HTTP client like `curl`.
E.g. use this command:

    curl -i -L http://192.168.201.1:8000/

**Comment by chantra** [comment]
yes, this is definitely #216 . I wish upstream would release a new package.

**Comment by chantra** [comment]
upstream has just published the new package: https://pypi.python.org/pypi/django-bootstrap-themes/3.1.3 
upgrading django-bootstrap-themes will solve the css issue (you will need to restart the atc ui after that though)

**Comment by ctriptest** [comment]
@chantra & @zfjagann 
Thanks for your response, I will try it.
But, I want to know how to import sample profiles.
I think of the steps is below:
1. download utils package
2. directly to executed restore-profiles.sh
Is it correctly?

**Comment by chantra** [comment]
You will need to get the profiles from the git repository and run the command on the machine.




Sent via the Samsung Galaxy S® 6 edge, an AT&T 4G LTE smartphone

**Comment by ctriptest** [comment]
@chantra 
I have get the profiles (Path: atc@ubuntu:~/Desktop/augmented-traffic-control-master/utils$) and run the command (sudo ./restore-profiles.sh 192.168.201.1:8000) on the machine, but it failed. Error message is below:
./restore-profiles.sh: line 12: git: command not found
Could not add profile /utils/profiles/* (curl exit code 7)

Do you have any suggest for me that I try to solve the error message?

**Comment by chantra** [comment]
`./restore-profiles.sh: line 12: git: command not found`

you need to have `git` installed.

you do not need to run this using sudo

**Comment by ctriptest** [comment]
I have install git via the command (sudo apt-get install git), then I rerun the command (./restore-profiles.sh 192.168.201.1:8080).
But, I still see error message is below:
fatal: Not a git repository (or any of the parent directories): .git
Could not add profile /utils/profiles/* (curl exit code 7)

**Comment by chantra** [comment]
@ctriptest you needed to clone the repository. 
```
git clone https://github.com/facebook/augmented-traffic-control.git
cd augmented-traffic-control/utils
./restore-profiles.sh 192.168.201.1:8000
```

**Comment by ctriptest** [comment]
@chantra 
Thanks very much, for ubuntu & ATC, I am a new guys, so have more questions.

I have cloned repository by git clone, but I still could not add profile when I rerun the command (./restore-profiles.sh 192.168.201.1:8000)
![restore-profiles](https://cloud.githubusercontent.com/assets/16544057/12190427/62dc4d14-b603-11e5-8cf4-73c9b324869d.png)

**Comment by chantra** [comment]
@ctriptest is atcui listening on 192.168.201.1:8000 ? exit code 7 is `cannot connect`

gist the output of `netstat -lpnt` please

**Comment by ctriptest** [comment]
![image](https://cloud.githubusercontent.com/assets/16544057/12190642/fa92b57e-b605-11e5-9a40-3032ca330c10.png)

**Comment by ctriptest** [comment]
@chantra I've successfully imported sample profiles. Thanks for your great help.

For sample profiles, when will you add profiles for 4G LTE environment?

**Comment by chantra** [comment]
@ctriptest we are not aiming at maintaining a list of profiles. That being said, the goal is to emulate bad connectivity which is not what 4G is.

I will be closing this now as you successfully got set up.

**Comment by ctriptest** [comment]
@chantra & @zfjagann 
Thanks for your great help again.
Which way I can contiune to contant you when I found any probelm in the process of using the ATC, create another issue or email to you?
Would you please tell me the email of you.

**Comment by chantra** [comment]
@ctriptest open a new issue or rather come to #atcd in freenode.net  for support https://webchat.freenode.net/

**Comment by vedeshkumar** [comment]
Hi,

I am unable to see the profiles added. Please help

![screenshot from 2016-02-19 19 03 31](https://cloud.githubusercontent.com/assets/16402634/13177001/584ebf94-d73c-11e5-8d35-add2973ea655.png)

**Comment by zfjagann** [comment]
@vedeshkumar have you run the `restore-profiles.sh` script provided in the source path under `utils/`?

**Comment by vedeshkumar** [comment]
@zfjagann Yes i did run the restore-profiles.sh and it says added the profiles but still unable to see it.

Is there any document step by step where i can refer to see if i have made any mistake in the setup

**Comment by vedeshkumar** [comment]
Please help me to overcome this issue

**Comment by vedeshkumar** [comment]
@chantra This is how i have setup the ATC in Ubuntu desktop

1. Ubuntu desktop has 2 network ports
2. One is connected with LAN
3. In one of the terminal i started the "atcd" and in another terminal i started "python manage.py runserver 0.0.0.0:8000"

**Comment by chantra** [comment]
this is being continued in https://github.com/facebook/augmented-traffic-control/issues/240
