### ISSUE TITLE
The Bandwidth Limit is not correct

### ISSUE THREAD

**Issue by JiTeng** [facebook/augmented-traffic-control#228]
I set Bandwidth Limit 200 kbps and then I connect the AP with my android phone.But the network interrupts sometimes. In the beginning the wifi is ok, five minutes later it interrupts. Repeatedly.Could you tell me the reason. I am an App tester from China.

**Comment by agargiulo** [comment]
interrupts how? I mean, you're limiting your connection so things are bound to not like that.

**Comment by JiTeng** [comment]
I konw the reason. I use vmware. You should choose "Bridge Networking" then everything's running as expected. Thanks.

**Comment by chantra** [comment]
@JiTeng nice to see this is fixed and thanks for explaining the reason it was not behaving as expected.
