### ISSUE TITLE
Turn On failed (17, 'File exists')

### ISSUE THREAD

**Issue by LittlePeng** [facebook/augmented-traffic-control#239]
INFO:AtcdVService.AtcdLinuxShaper:Request startShaping TrafficControl(device=TrafficControlledDevice(controllingIP='10.10.100.211', controlledIP='10.10.100.211'), timeout=86400, settings=TrafficControlSetting(down=Shaping(loss=Loss(percentage=0.0, correlation=0.0), delay=Delay(delay=0, jitter=0, correlation=0.0), rate=11, iptables_options=[], corruption=Corruption(percentage=0.0, correlation=0.0), reorder=Reorder(percentage=0.0, correlation=0.0, gap=0)), up=Shaping(loss=Loss(percentage=0.0, correlation=0.0), delay=Delay(delay=0, jitter=0, correlation=0.0), rate=11, iptables_options=[], corruption=Corruption(percentage=0.0, correlation=0.0), reorder=Reorder(percentage=0.0, correlation=0.0, gap=0))))
INFO:AtcdVService.AtcdLinuxShaper:Shaping ip 10.10.100.211 on interface eth0
INFO:AtcdVService.AtcdLinuxShaper:create new HTB class on IFID eth0, classid 1:2,parent 1:0, rate 11kbits
INFO:AtcdVService.AtcdLinuxShaper:create new Netem qdisc on IFID eth0, parent 1:2, loss 0.0%, delay 0
INFO:AtcdVService.AtcdLinuxShaper:create new FW filter on IFID eth0, classid 1:2, handle 2, rate: 11kbits
INFO:AtcdVService.AtcdLinuxShaper:Running /sbin/iptables -t mangle -A FORWARD -s 10.10.100.211 -i eth0  -j MARK --set-mark 2
INFO:AtcdVService.AtcdLinuxShaper:Shaping ip 10.10.100.211 on interface eth0
INFO:AtcdVService.AtcdLinuxShaper:create new HTB class on IFID eth0, classid 1:2,parent 1:0, rate 11kbits

> ERROR:AtcdVService.AtcdLinuxShaper:adding HTB class on IFID eth0, mark 2, err: (17, 'File exists')

INFO:AtcdVService.AtcdLinuxShaper:Unshaping ip 10.10.100.211 on interface eth0
INFO:AtcdVService.AtcdLinuxShaper:Running /sbin/iptables -t mangle -D FORWARD -s 10.10.100.211 -i eth0  -j MARK --set-mark 2
INFO:AtcdVService.AtcdLinuxShaper:deleting filter on IFID eth0, handle 2
INFO:AtcdVService.AtcdLinuxShaper:deleting class on IFID eth0, classid 1:2

Ubuntu 14.04.3 LTS
Linux localhost 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by chantra** [comment]
@LittlePeng 
you are using eth0 for both `--atcd-lan` and `--atcd-wan`. Can you confirm?

atcd requirements is to have 2 separate interfaces.

**Comment by LittlePeng** [comment]
yes, I just use wrong eth0 for both --atcd-lan and --atcd-wan, thanks
