### ISSUE TITLE
Requesting help to setup facebook ATC

### ISSUE THREAD

**Issue by vedeshkumar** [facebook/augmented-traffic-control#240]
Hi ,

i am trying to configure ATC in my ubuntu desktop machine following the github doc. Can anyone please help to me set it up. I keep facing one or the other issue

--Vedesh

**Comment by zfjagann** [comment]
Hi @vedeshkumar, what issue are you having with ATC? If you could provide more information about what issue you are having, output from relevant commands, and the instructions you followed it would be very helpful. Thanks!

**Comment by vedeshkumar** [comment]
@zfjagann This is how i have setup the ATC in Ubuntu desktop

Ubuntu desktop has 2 network ports
One is connected with LAN
In one of the terminal i started the "atcd" and in another terminal i started "python manage.py runserver 0.0.0.0:8000"

Is this correct ?

**Comment by zfjagann** [comment]
That's correct in theory, but without the exact commands it's difficult to say for sure.

Did either of the commands fail, or print an error message?

**Comment by vedeshkumar** [comment]
2 days back i could able to see the below UI without any profiles
![584ebf94-d73c-11e5-8d35-add2973ea655](https://cloud.githubusercontent.com/assets/16402634/13233575/46072632-d9da-11e5-840b-6dddad255f28.png)

**Comment by vedeshkumar** [comment]
Now when i run atcd again it give following error

ERROR:sparts.tasks:Error creating task, AtcdNBServerTask
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/sparts/vtask.py", line 313, in init
t.initTask()
File "/usr/local/lib/python2.7/dist-packages/sparts/tasks/thrift.py", line 146, in initTask
self.server.prepare()
File "/usr/local/lib/python2.7/dist-packages/thrift/server/TNonblockingServer.py", line 254, in prepare
self.socket.listen()
File "/usr/local/lib/python2.7/dist-packages/thrift/transport/TSocket.py", line 173, in listen
self.handle.bind(res[4])
File "/usr/lib/python2.7/socket.py", line 224, in meth
return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use
INFO:AtcdVService.AtcdLinuxShaper:Calling initialize_shaping_system
INFO:AtcdVService.AtcdLinuxShaper:Running /sbin/iptables -t mangle -F FORWARD
INFO:AtcdVService.AtcdLinuxShaper:deleting root QDisc on eth1
INFO:AtcdVService.AtcdLinuxShaper:setting root qdisc on eth1
INFO:AtcdVService.AtcdLinuxShaper:deleting root QDisc on eth0
INFO:AtcdVService.AtcdLinuxShaper:setting root qdisc on eth0
INFO:AtcdVService.AtcdLinuxShaper:Restoring shaped connection from DB
INFO:AtcdVService.AtcdLinuxShaper:Request startShaping TrafficControl(device=TrafficControlledDevice(controllingIP='172.4.29.250', controlledIP='172.4.29.250'), timeout=83862.76753091812, settings=TrafficControlSetting(down=Shaping(loss=Loss(percentage=0.0, correlation=0.0), delay=Delay(delay=0, jitter=0, correlation=0.0), rate=None, iptables_options=[], corruption=Corruption(percentage=0.0, correlation=0.0), reorder=Reorder(percentage=0.0, correlation=0.0, gap=0)), up=Shaping(loss=Loss(percentage=0.0, correlation=0.0), delay=Delay(delay=0, jitter=0, correlation=0.0), rate=None, iptables_options=[], corruption=Corruption(percentage=0.0, correlation=0.0), reorder=Reorder(percentage=0.0, correlation=0.0, gap=0))))
INFO:AtcdVService.AtcdLinuxShaper:Shaping ip 172.4.29.250 on interface eth0
INFO:AtcdVService.AtcdLinuxShaper:create new HTB class on IFID eth0, classid 1:2,parent 1:0, rate 4194303kbits
INFO:AtcdVService.AtcdLinuxShaper:create new Netem qdisc on IFID eth0, parent 1:2, loss 0.0%, delay 0
INFO:AtcdVService.AtcdLinuxShaper:create new FW filter on IFID eth0, classid 1:2, handle 2, rate: Nonekbits
INFO:AtcdVService.AtcdLinuxShaper:Running /sbin/iptables -t mangle -A FORWARD -d 172.4.29.250 -i eth0 -j MARK --set-mark 2
INFO:AtcdVService.AtcdLinuxShaper:Shaping ip 172.4.29.250 on interface eth1
INFO:AtcdVService.AtcdLinuxShaper:create new HTB class on IFID eth1, classid 1:2,parent 1:0, rate 4194303kbits
INFO:AtcdVService.AtcdLinuxShaper:create new Netem qdisc on IFID eth1, parent 1:2, loss 0.0%, delay 0
INFO:AtcdVService.AtcdLinuxShaper:create new FW filter on IFID eth1, classid 1:2, handle 2, rate: Nonekbits
INFO:AtcdVService.AtcdLinuxShaper:Running /sbin/iptables -t mangle -A FORWARD -s 172.4.29.250 -i eth1 -j MARK --set-mark 2
ERROR:AtcdVService:Unexpected Exception during init
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/sparts/vservice.py", line 268, in _runloop
instance._createTasks()
File "/usr/local/lib/python2.7/dist-packages/sparts/vservice.py", line 167, in _createTasks
self.tasks.init()
File "/usr/local/lib/python2.7/dist-packages/sparts/vtask.py", line 332, in init
len(exceptions))
Exception: Unable to start service (1 task start errors)
INFO:AtcdVService:Received graceful shutdown request
DEBUG:AtcdVService:VService Active. Awaiting graceful shutdown.
INFO:AtcdVService:Waiting for tasks to shutdown gracefully...
DEBUG:AtcdVService:Waiting for to stop...
DEBUG:AtcdVService:Waiting for to stop...
DEBUG:AtcdVService:Waiting for to stop...
DEBUG:AtcdVService:Waiting for to stop...
INFO:AtcdVService:Instance shut down gracefully

**Comment by zfjagann** [comment]
Can you paste the command you ran (along with its arguments) as a comment, or use a [gist](https://gist.github.com/)?

**Comment by vedeshkumar** [comment]
In one of the terminal i started the "atcd" and in another terminal i started "python manage.py runserver "machine ip address":8000"

**Comment by zfjagann** [comment]
How did you start `atcd`? What arguments did you pass it?

**Comment by vedeshkumar** [comment]
no arguements.... just "atcd" in terminal

**Comment by zfjagann** [comment]
What's the output of `ip link`?

**Comment by vedeshkumar** [comment]
do u have skype id ? so that i can share my screen whenever you are free

**Comment by zfjagann** [comment]
It's be better if you could copy/paste the output of `ip link` into [gist](gist.github.com) and then paste the link into . Others might also have this same problem, and will be able to search github, find this issue, and use the same fix to solve their issue. :)

**Comment by vedeshkumar** [comment]
Currently i m at home.. once i reach office i will post the details.. By the way is there any video tutorial of how the setup has been done,, so i will try to replicate the setup by looking into it

**Comment by chantra** [comment]
ok, let's step back for a bit here.

@vedeshkumar I guess your issue is related to https://github.com/facebook/augmented-traffic-control/issues/227#issuecomment-186216145

What is the issue you are currently having? It used to be that you could not get the profile listed. Is this different now?

Going back to comment https://github.com/facebook/augmented-traffic-control/issues/240#issuecomment-187397095 
you are getting error: `error: [Errno 98] Address already in use`
this is because you already have an `atcd` instance running.

@vedeshkumar could you please provide the answers to my questions in https://github.com/facebook/augmented-traffic-control/issues/227#issuecomment-186670026

**Comment by vedeshkumar** [comment]
@chantra  i was not getting the profiles but from yesterday when i try to run atcd in terminal it keeps throwing the above error. i have restarted my machine by killing all the process running

**Comment by chantra** [comment]
@vedeshkumar 
so you have something that runs locally and listen on port 9090.

Can you confirm that no other `atcd` process is running (using ps aux and checking for atcd)
Can you put in a [gist](https://gist.github.com/) the output of `netstat -lpnt` (ran as root)

**Comment by vedesh** [comment]
Hi Everyone,

I have successfully installed ATC in my ubuntu desktop. i want to know how to use it and how to test the network

My Ubuntu desktop is connected with wifi and also with lan

Please help me in understanding how to use ATC

**Comment by vedesh** [comment]
Hi Everyone,

I have successfully installed ATC in my ubuntu desktop. i want to know how to use it and how to test the network

My Ubuntu desktop is connected with wifi and also with lan

Please help me in understanding how to use ATC

**Comment by mahadevprasad** [comment]
Hi Everyone,

I have successfully installed ATC in my ubuntu desktop. i want to know how to use it and how to test the network

My Ubuntu desktop is connected with wifi and also with lan

Please help me in understanding how to use ATC

**Comment by chantra** [comment]
@vedeshkumar any success?

@mahadevprasad could you please create a separate issue or jump on freenode, irc channel #atcd

**Comment by mahadevprasad** [comment]
@chantra i have created new issue with #243

**Comment by vedeshkumar** [comment]
@chantra , i have not worked on ATC for few days as i am busy with other works. Once i start working on it again will update the status

Thanks @chantra and @zfjagann

**Comment by chantra** [comment]
Hi @vedeshkumar 
I will close this for now. Whenever you are available to work on it again, please open a new issue and reference this one.
