### ISSUE TITLE
Weird things happen when ATC runs on my Ubuntu.

### ISSUE THREAD

**Issue by PanWangJ** [facebook/augmented-traffic-control#242]
My environment: Ubuntu 14.04 + Wireless USB dongle + ATC.

I had set up the entire ATC environment on my desktop quite a long time ago and everything is fine until yesterday. 

The problem is that whenever I runs ATC the devices that connected to the softAP find it very hard to connect to the Internet, even when my shaping profile is set to the "Cable" (comes with 6000 down rate and 1000 up rate). I can see that the latency setting is working as expected, just the connecting speed is abnormal.

If I turn off ATC, just to connect my devices to the softAP without any shaping, everything is fine again. I've used ATC for several months and never changed anything. I totally have no idea what would be the cause.

Quite frustrated by this problem, could anyone help me out?

**Comment by chantra** [comment]
Hi @PanWangJ,

I wonder if you used to use `--atcd-dont-drop-packets` before...

**Comment by PanWangJ** [comment]
@chantra Thanks for replying. I had never used to use the command you mentioned above. Do you mean I have to use the command to make it normal?

**Comment by chantra** [comment]
@PanWangJ 
well, no change happened in atc that would fix the issue you describe so there is no need to upgrade.

Have you tried using the `--atcd-dont-drop-packets` command line flag? does that work better for you?

**Comment by PanWangJ** [comment]
@chantra I tried to use the `--atcd-dont-drop-packets` when starting the **atcd**, but it gave me the `atcd: error: unrecognized arguments` warning.

The full command I use is:

    sudo atcd --atcd-wan eth0 --atcd-lan wlan1 --atcd-dont-drop-packets

What's going wrong here?

**Comment by chantra** [comment]
@PanWangJ so I guess you run a very old version of atc and it did not have this flag.
can you run `atcd -h` just to make sure I did not misspell it. If this is not available, you may want to update atcd and start using this flag.

That being said, I cannot find an explanation why it would have worked in the past and not now.

**Comment by PanWangJ** [comment]
@chantra I checked with `atcd -h` and can't find this flag, so I may as well update ATC to the latest version. Just hope updating ATC will solve this problem, I will let you know of any results. Thanks for your help.

**Comment by PanWangJ** [comment]
@chantra Managed to update ATC to 0.1.3, and add the flag `--atcd-dont-drop-packets`. Problem solved! Thanks! 

Ps. Could you kindly explain to me what does this flag actually mean? What will be the difference if I don't add this flag?

**Comment by chantra** [comment]
@PanWangJ the flag makes ATC buffer packets rather than drop them. I still dont understand why the behaviour would have changed though.

@PanWangJ  I will close this issue now since it seems your issue is solved, open a new issue if you have further problems.

**Comment by PanWangJ** [comment]
@chantra I have no idea why would this happened at all. Anyway, the problem is solved, thank you for your help.
