### ISSUE TITLE
Requesting help to understand how to use facebook ATC

### ISSUE THREAD

**Issue by mahadevprasad** [facebook/augmented-traffic-control#243]
Hi Everyone,

I have successfully installed ATC in my ubuntu desktop. i want to know how to use it and how to test the network

My Ubuntu desktop is connected with wifi and also with lan

Please help me in understanding how to use ATC

**Comment by chantra** [comment]
Hi @mahadevprasad 

the ubuntu desktop you are using, is it acting as a router? e.g the devices you want to shape the traffic for are connecting to this desktop wireless access point and their traffic is routed through?

Do you meet the requirements from http://facebook.github.io/augmented-traffic-control/docs/install.html ?

Once this is the case, you should be able to get devices to connect to http://<ip of your router>:8000/ , set the shaping you want and get going

**Comment by mahadevprasad** [comment]
@Chantal, ATCD is running on Ubuntu machine whIch is wifi enabled and i have connected my android device to that wifi and i am able to connect to http://:8000/

Now what should i do

**Comment by mahadevprasad** [comment]
@Chantra, ATCD is running on Ubuntu machine whIch is wifi enabled and i have connected my android device to that wifi and i am able to connect to http://:8000/

Now what should i do

**Comment by chantra** [comment]
@mahadevprasad you can play around with the interface, add latency and ask for the traffic to be shaped. then see that latency has been added.

**Comment by mahadevprasad** [comment]
@chantra , some more brief information can give please, like how exactly i can play around with the interface, add latency and ask for the traffic to be shaped. then see that latency has been added

**Comment by chantra** [comment]
@mahadevprasad can you send a screenshot of what interface you are seeing?

In the end, you want to limit the bandwidth on the up and down link and click turn on.

Use websites like speedtest or somnething to see that ping has latency added....

**Comment by chantra** [comment]
@mahadevprasad did you solve your issue?

While I understand the interface may not be the most intuitive, I think with a bit of fiddling around you should pretty much find out how to play with parameters.

**Comment by mahadevprasad** [comment]
@chantra apologies for late reply as i was out of station.

I tried the below steps to play with profiles
1. Accessed the url  "http://:8000/" in my android device
2. I was able to see device ip and token 
3. I entered the device ip and token in the ATCD running in ubuntu machine and authorized
4. Then i selected the profiles and clicked on "update shaping" button
5. Then i checked the net speed in the device using OOKLA Speed Test Application

Observation made:

When i selected 2g profile, the net uplink and downlink was around 8-9 mbps and the speed was almost same when i kept on selecting in different profiles

I could see almost same net speed even when i selected "No connectivity" profile as well

So i was surprised to see such results.

I wanted to know whether what i am doing is correct or not ?

**Comment by chantra** [comment]
@mahadevprasad 
Thanks for providing details about your issue.

Can you confirm that the device you are shaping the traffic for is **routed** through the ATC box.

Is the machine running atc acting as a router for your android device? Or is it just another computer on the network?
It is a requirement that the ATC machine acts as a router, failing to do so, ATC will not be able to handle and shape the packets from the devices.

**Comment by mahadevprasad** [comment]
@chantra, yes my ubuntu machine is having a wifi card installed and it is running as a router for my android device

**Comment by chantra** [comment]
ok, so another reason this could happen would be because you inverted wan and lan.

Can you let me know what is your wan and lan interface (and post a gist of `ip a`)
and also let me know how you started atc.

Logs from `atcd` upon shaping could also help.

**Comment by chantra** [comment]
@mahadevprasad 

What is the status here? Is your issue fixed? or do you still need assistance?

**Comment by mahadevprasad** [comment]
@chantra , Oh yes i still need assistance. i will give the details asked by you within couple of days

**Comment by mahadevprasad** [comment]
@chantra,

i have attached logs from atcd

I follow below steps to start atcd service 
Starting atcd service :
$ test -z $VIRTUAL_ENV && source ~/dev/atc/venv/bin/activate
$ sudo atcd

I followed below steps to start atcd demo ui
$ test -z $VIRTUAL_ENV && source ~/dev/atc/venv/bin/activate
$ cd ~/dev/atc/atcui
$ python manage.py runserver 10.42.0.1:8000

My lan and wan interface
equal@EDT-169:~$ ifconfig
eth0      Link encap:Ethernet  HWaddr d0:67:e5:01:89:6e  
          inet addr:192.168.1.3  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fe80::d267:e5ff:fe01:896e/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:48076 errors:0 dropped:0 overruns:0 frame:0
          TX packets:47531 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:46721221 (46.7 MB)  TX bytes:32160336 (32.1 MB)

eth1      Link encap:Ethernet  HWaddr 00:e0:4c:68:00:36  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:39473 errors:0 dropped:0 overruns:0 frame:0
          TX packets:39473 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:2810325 (2.8 MB)  TX bytes:2810325 (2.8 MB)

wlan0     Link encap:Ethernet  HWaddr 14:d6:4d:48:0a:b5  
          inet addr:10.42.0.1  Bcast:10.42.0.255  Mask:255.255.255.0
          inet6 addr: fe80::16d6:4dff:fe48:ab5/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:36253 errors:0 dropped:0 overruns:0 frame:0
          TX packets:29484 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:30512078 (30.5 MB)  TX bytes:26149312 (26.1 MB)



[logs from atcd.zip](https://github.com/facebook/augmented-traffic-control/files/173351/logs.from.atcd.zip)

**Comment by chantra** [comment]
@mahadevprasad
You need to specify which lan interface atcd should use.  Basically you should run `atcd --atcd-wan wlan0`
Refer to atcd help for more options.



Sent via the Samsung Galaxy S® 6 edge, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by mahadevprasad** [comment]
@chantra 
sudo atcd --atcd-wan wlan0 --atcd-lan eht0

is this way correct ?

**Comment by mahadevprasad** [comment]
@chantra,

Now i started atcd using the below command
sudo atcd --atcd-wan wlan0 --atcd-lan eht0

Now i have authorized my device and selected few profiles

When i test the speed, for download i could see few MBPS shown, but for upload the speed gradually start decreasing and suddenly it shows "Network communication issues"

What could be the reason ?

**Comment by chantra** [comment]
@mahadevprasad you may want to use the `--atcd-dont-drop-packets` option and see if that works better for you.

By default, the packets are being dropped when going above a bandwith, this option will buffer them.

I will close this issue now as atcd is now working for you.

**Comment by mahadevprasad** [comment]
@chantra ,

is this command is correct ?

sudo atcd --atcd-wan wlan0 --atcd-lan eth0 --atcd-dont-drop-packets

No profiles are working after using "--atcd-dont-drop-packets" option.. when i select any profile it gives "Network communication issues" or Speedtest app only crashes. Please help
