### ISSUE TITLE
why the settings do not work?

### ISSUE THREAD

**Issue by mgjnana** [facebook/augmented-traffic-control#245]
I use "this.linkState("settings").requestChange(settingData);"   in atc.js,  but I found the setting for  loss、reorder、corruption、delay  is not working. here is code（I set biger number for settings，but seems it’s do not work.too）:
   
Any one can help me? thx，wait online...

setCurrentShape: function(up,down){
        console.log('进入setCurrentShape  ----------------'+new Date().getTime());
        var upDelay = (up>0||down>0)?this.getRandomNum(100,200):0;
        var upLoss = (up>0||down>0)?this.getRandomNum(0,10):0;
        var upCorruption = (up>0||down>0)?this.getRandomNum(10,70):0;
        var upReOrder = (up>0||down>0)?this.getRandomNum(10,70):0;
        var downDelay = (up>0||down>0)?this.getRandomNum(100,200):0;
        var downLoss = (up>0||down>0)?this.getRandomNum(0,60):0;
        var downCorruption = (up>0||down>0)?this.getRandomNum(10,70):0;
        var downReOrder = (up>0||down>0)?this.getRandomNum(10,70):0;

        var settingData = this.getSetting(up,upDelay,upLoss,upCorruption,upReOrder,down,downDelay,downLoss,downCorruption,downReOrder);

        this.linkState("settings").requestChange(settingData);
    },

getSetting: function(upRate,upDelay,upLoss,upCorruption,upReOrder,downRate,downDelay,downLoss,downCorruption,downReOrder){
     var settingData = {
        'up': {
            'rate': upRate,
            'delay': {
                'delay': upDelay,
                'jitter': 0,
                'correlation': 0
            },
            'loss': {
                'percentage': upLoss,
                'correlation': 0
            },
            'reorder': {
                'percentage': upReOrder,
                'correlation': 0,
                'gap': 0
            },
            'corruption': {
                'percentage': upCorruption,
                'correlation': 0
            },
            'iptables_options': Array(),
        },
        'down': {
            'rate': downRate,
            'delay': {
                'delay': downDelay,
                'jitter': 0,
                'correlation': 0
            },
            'loss': {
                'percentage': downLoss,
                'correlation': 0
            },
            'reorder': {
                'percentage': downReOrder,
                'correlation': 0,
                'gap': 0
            },
            'corruption': {
                'percentage': downCorruption,
                'correlation': 0
            },
            'iptables_options': Array(),
        }
    };

    return settingData;
},

**Comment by mgjnana** [comment]
" this.state.current_settings " shows these settings is working ,at least the printing is my setting.

**Comment by zfjagann** [comment]
I'm not sure exactly what you're trying to do or why it's not working. Do you mind pasting the code into [gist](https://gist.github.com/). That'll make it a lot easier to read.

**Comment by mgjnana** [comment]
this setting is effective for mobile phone on the web page,but app(TCP,socket) have no effect. do I need connect to this particular WIFI and then visit the web page for flow control on this app's server?

here is  my atc.js:

/** @jsx React.DOM */
/**
 * Copyright (c) 2014, Facebook, Inc.
 * All rights reserved.
 *
 *  This source code is licensed under the BSD-style license found in the
 *  LICENSE file in the root directory of this source tree. An additional grant
 *  of patent rights can be found in the PATENTS file in the same directory.
 */

var ERROR_EXPIRY = 10000;
var atc_status = {
  FIRST: 0, 
  SECOND: 1,  
  THIRD: 2
};

var Atc = React.createClass({
  mixins: [RecursiveLinkStateMixin],
  getInitialState: function() {
    return {
      client: new AtcRestClient(this.props.endpoint),
      settings: new AtcSettings().getDefaultSettings(),
      current_settings: new AtcSettings().getDefaultSettings(),
      status: atc_status.FIRST,
      profiles: [],
      notifications: [],
      isSetInterval: false,  // timer
    };
  },
  notify: function(type, msg) {
    this.setState(function(state, props) {
      return {
        notifications: state.notifications.concat({
          expire_at: ERROR_EXPIRY + new Date().getTime(),
          message: msg,
          type: type,
        })
      };
    });
  },
  expireNotifications: function() {
    this.setState(function(state, props) {
      return {
        notifications: state.notifications.filter(function(item, idx, arr) {
            return item.expire_at >= new Date().getTime();
        })
      };
    })
  },
  componentDidMount: function() {
    this.getCurrentShaping();
    /** FIXME we are calling getCurrentShaping to make sure that
     * current_settings === settings.... let's be smarter than that.
     */
    this.getCurrentShaping();
    this.expiry_interval = setInterval(this.expireNotifications, 1000);
  },
  componentWillUnmount: function() {
    if (this.expiry_interval != null) {
      clearInterval(this.expiry_interval);
    }
  },
  handleClick: function(e) {
  console.log(JSON.stringify(this.state.status));
    if (e.type == "click") {
      if (this.state.status == atc_status.THIRD) {
        this.unsetShaping();
        if(this.state.isSetInterval) {
          clearInterval(this.intervalId);
          this.setState({
            isSetInterval: false,
            curNetType: null,
            net_detail_info: null
          });
          }
          if(timeoutId1) {
            clearTimout(this.timeoutId1);
          }
          if(timeoutId2) {
            clearTimout(this.timeoutId2);
          }
      } else if (this.state.status == atc_status.SECOND ) {
        this.setShaping();
        if(!this.state.isSetInterval) {
          this.setRegularWeakNetWork();
          this.intervalId = setInterval(this.setRegularWeakNetWork,6000);
          this.setState({
            isSetInterval: true
          });
        }
      }
  }
  },
  getSetting: function(upRate,upDelay,upLoss,upCorruption,upReOrder,downRate,downDelay,downLoss,downCorruption,downReOrder){
     var settingData = {
        'up': {
            'rate': upRate,
            'delay': {
                'delay': upDelay,
                'jitter': 0,
                'correlation': 0
            },
            'loss': {
                'percentage': upLoss,
                'correlation': 0
            },
            'reorder': {
                'percentage': upReOrder,
                'correlation': 0,
                'gap': 0
            },
            'corruption': {
                'percentage': upCorruption,
                'correlation': 0
            },
            'iptables_options': Array(),
        },
        'down': {
            'rate': downRate,
            'delay': {
                'delay': downDelay,
                'jitter': 0,
                'correlation': 0
            },
            'loss': {
                'percentage': downLoss,
                'correlation': 0
            },
            'reorder': {
                'percentage': downReOrder,
                'correlation': 0,
                'gap': 0
            },
            'corruption': {
                'percentage': downCorruption,
                'correlation': 0
            },
            'iptables_options': Array(),
        }
    };
    return settingData;
},

  setRegularWeakNetWork: function(){
    this.setState({
       curNetType: ""
    });
    var upMaxRate = this.getRandomNum(2, 16);
    var downMaxRate = this.getRandomNum(2, 18);
    this.setCurrentShape(upMaxRate,downMaxRate);
    var upMinRate = this.getRandomNum(0);
    var downMinRate = this.getRandomNum(0);
    if(this.timeoutId1){
        clearTimeout(this.timeoutId1);
    }
    this.setCurrentShape(upMinRate,downMinRate);
  },

  setCurrentShape: function(up,down){
        var upDelay = this.getRandomNum(50,600);
        var upLoss = this.getRandomNum(0,10);
        var upCorruption = this.getRandomNum(10,70);
        var upReOrder = this.getRandomNum(10,70);
        var downDelay = this.getRandomNum(50,600);
        var downLoss = this.getRandomNum(0,60);
        var downCorruption = this.getRandomNum(10,70);
        var downReOrder = this.getRandomNum(10,70);

// for UI display        this.setDetailInfo(up,down,upDelay,downDelay,upLoss,upCorruption,upReOrder,downLoss,downCorruption,downReOrder);
        console.log('up: ' + up + ' down:' + down);
        var settingData = this.getSetting(up,upDelay,upLoss,upCorruption,upReOrder,down,downDelay,downLoss,downCorruption,downReOrder);
        this.linkState("settings").requestChange(settingData);
    },

  setDetailInfo: function(up,down,upDelay,downDelay,upLoss,upCorruption,upReOrder,downLoss,downCorruption,downReOrder){
        console.log("come here");
        var upRateStr = up+" kb/s";
        var downRateStr = down+" kb/s";
        var upDelayStr = upDelay+" ms";
        var downDelayStr = downDelay+" ms";
        var net_detail_info = [
          ['upRate', upRateStr],
          ['downRate',downRateStr],
          ['upDelay', upDelayStr],
          ['upLoss',upLoss],
          ['upCorruption', upCorruption],
          ['upReOrder',upReOrder],
          ['downDelay', downDelayStr],
          ['downLoss', downLoss],
          ['downCorruption', downCorruption],
          ['downReorder',downReOrder]
        ];
        this.setState({
          net_detail_info: net_detail_info
        });
  },
  updateClick: function(e) {
    if (e.type == "click") {
      this.setShaping();
    }
  },
  getProfiles: function() {
    this.state.client.get_profiles(function (result) {
      if (result.status >= 200 && result.status < 300) {
        this.setState({
          profiles: result.json,
        });
      } else {
        this.error(result.json.detail);
        this.setState({
          profiles: [],
        });
      }
    }.bind(this));
  },
  getCurrentShaping: function() {
    this.state.client.getCurrentShaping(function (result) {
      if (result.status == 404) {
        this.setState({
          status: atc_status.SECOND,
          settings: new AtcSettings().getDefaultSettings(),
          current_settings: new AtcSettings().getDefaultSettings(),
        });
      } else if (result.status >= 200 && result.status < 300 && this.state.status == atc_status.FIRST) {
        this.setState({
          status: atc_status.SECOND,
          settings: result.json,
          current_settings: this.state.settings,
        });
      }else if (result.status >= 200 && result.status < 300  && this.state.status == atc_status.SECOND) {
        if(!this.state.isSetInterval) {
         this.setRegularWeakNetWork();
          this.intervalId = setInterval(this.setRegularWeakNetWork,6000);
          this.setState({
            isSetInterval: true
          });
        }
        this.setState({
          status: atc_status.THIRD,
          settings: result.json,
          current_settings: this.state.settings,
        });
      } else {
        this.error(result.json.detail);
        this.setState({
          status: atc_status.FIRST,
          settings: new AtcSettings().getDefaultSettings(),
        });
      }
    }.bind(this));
  },
  unsetShaping: function() {
    this.state.client.unshape(function (result) {
      if (result.status >= 200 && result.status < 300) {
        this.setState({
          status: atc_status.SECOND,
          settings: new AtcSettings().getDefaultSettings(),
          current_settings: new AtcSettings().getDefaultSettings(),
        });
      } else if (result.status >= 500) {
        this.notify("error", result.json.detail);
        this.setState({
          status: atc_status.FIRST,
        });
      }
    }.bind(this));
  },
  setShaping: function() {
    this.state.client.shape(function (result) {
      if (result.status >= 200 && result.status < 300) {
        this.setState({
          status: atc_status.THIRD,
          settings: result.json,
          current_settings: {down: this.state.settings.down, up: this.state.settings.up},
        });
      } else if (result.status == 400) {
        for (var key in result.json) {
          result.data[key].map(function(msg) {
            this.notify("error", key + ': ' + msg);
          }.bind(this));
        }
      } else if (result.status >= 500) {
        this.notify("error", result.json.detail);
        this.setState({
          status: atc_status.FIRST,
        });
      }
    }.bind(this), {down: this.state.settings.down, up: this.state.settings.up});
  },
  render: function () {
    link_state = this.linkState;
    var err_msg = "";
    return (
      <div>
        <div className="row" style={{marginBottom: '30px', marginTop: '40px' }} >
          <div id="shaping_buttons" className="col-md-12 text-center">
             <ShapingButton id="shaping_button" status={this.state.status} onClick={this.handleClick}  />
            {err_msg}
          </div>
        </div>
        <JSONView  json={this.state.net_detail_info} status={this.state.status} type={this.state.curNetType} label="Now:" />
      </div>
    )
  }
});

**Comment by zfjagann** [comment]
Glad it's fixed. Let us know if you need any more help. :smile:
