### ISSUE TITLE
ATC（augmented-traffic-control） cannot be used for TCP?

### ISSUE THREAD

**Issue by mgjnana** [facebook/augmented-traffic-control#246]
ATC（augmented-traffic-control） cannot be used for TCP?  It can only be used for HTTP testing？

**Comment by zfjagann** [comment]
So long as you correctly route your traffic through the machine running ATC, it can be used for any type of traffic including TCP or UDP. :)

**Comment by mgjnana** [comment]
Thank you for your reply. #。#

My question is this, I set up a ATC environment on a test machine，to achieve：let Android or IOS devices connected to the test machine with WiFi,then visit the atc_demo_ui and click the button to enter the setting environment(click can randomly set the parameters, mainly for the weak network test).
And now my problem is : after using a mobile phone click on the corresponding button, visit the web page in the browser will become very slow, but at least it is effective.But app does not play a role, speed is still fast（this test is mainly used in the app test environment,it use TCP.socket）.

Do you mean to say that：this app server need to connect to the WiFi,click on the corresponding button on the web page(the page is: demo_ui), this will be able to this app on the mobile phone for traffic control . is that it ?
