### ISSUE TITLE
Why up and down rates are set to 0 or can use socket contract?

### ISSUE THREAD

**Issue by mgjnana** [facebook/augmented-traffic-control#248]
Why up and down rates are set to 0 or can use socket contract?
 Is it set to 0 to use the default configuration? 
How can I set the rate of WiFi to 0 ?

**Comment by mgjnana** [comment]
I use Wechat test.

**Comment by mgjnana** [comment]
I use wechat test.

**Comment by chantra** [comment]
@mgjnana 0 is equivalent to unlimited. If you put a packet loss to 100%, you will effectively get 0 throughput.
