### ISSUE TITLE
Unable to shape profiles

### ISSUE THREAD

**Issue by mahadevprasad** [facebook/augmented-traffic-control#251]
@chantra, Referring to the issue #243 ,

Based on the discussion from #243, I tried the suggested approach of drop packet settings,
still observing the same behavior, there is not change in the upload and download speed with different profiles. Even with no connectivity I could see 7-8Mbps for upload and download.

For reference below is the list of commands executed for starting the services and also the machine where atc is configured is acting as the hotspot wifi virtual router.

sudo atcd --atcd-wan wlan0 --atcd-lan eth0 --atcd-dont-drop-packets

**Comment by chantra** [comment]
@mahadevprasad I am a bit lost here.

In https://github.com/facebook/augmented-traffic-control/issues/243#issuecomment-197716132 you say that you have no connectivity at all.

At least, from the command you are mentionning:
```
sudo atcd --atcd-wan wlan0 --atcd-lan eth0 --atcd-dont-drop-packets
```

You have most likely wan and lan reversed. You wan adapter is the one that connects you to the internet, your lan adapter is the one that connects you to your local network. Most likely `wlan0` is your lan so use:

```
sudo atcd --atcd-lan wlan0 --atcd-wan eth0 --atcd-dont-drop-packets
```

**Comment by chantra** [comment]
@mahadevprasad 

If this still fail, please run the script https://github.com/facebook/augmented-traffic-control/blob/master/utils/restore-profiles.sh when your device is being shaped and copy the output to a gist along with some relevant logs from /var/log/messages

**Comment by mahadevprasad** [comment]
@chantra , Sure will try and give the details

Can you please explain in detail how have u achieved ATC

**Comment by chantra** [comment]
@mahadevprasad 

I am not sure what you mean by `explain in detail how have u achieved ATC`

Can you clarify please.

**Comment by mahadevprasad** [comment]
@chantra, Let me clarify you the way i have setup ATC 

1. I have ubuntu machine which has wifi card installed and also Ethernet (LAN) cable connected
2. I have started atc demo ui by using below steps
     a. Opened the terminal
     b. entered i)  test -z $VIRTUAL_ENV && source ~/dev/atc/venv/bin/activate
                      ii)  cd ~/dev/atc/atcui
                      iii) python manage.py runserver 10.42.0.1.:8000
3. I have started atcd service by using below steps
     a. Opened one more terminal
     b. entered i)  test -z $VIRTUAL_ENV && source ~/dev/atc/venv/bin/activate  
                      ii)  sudo atcd --atcd-wan wlan0 --atcd-lan eth0 --atcd-dont-drop-packets
4. I have opened the browser in my ubuntu machine and i am accessing the below url
     "http://10.42.0.1:8000/atc_demo_ui/"
5.  Now my android device is connected to the wifi which is routed via ubuntu machine
6. I am accessing the same url in my android device as well
7. I could see my android device ip address and token under Authentication
8. I have entered the device ip address and token in the Authentication and authorized it
( i tried both ways by entering the ip address and token in the Authentication in the URL accessed in ubuntu machine as well as in the URL accessed in my android device)
9. Now i selected different profiles and clicked on Update shaping
10. Using speed test i am trying to check the speed

Result is : I am able to see around 7-8 MBPS for almost all profiles and even for "No connectivity profiles"

When i tried to reverse wlan0 and eth0, i could access the URL "http://10.42.0.1:8000/atc_demo_ui/"  in my android device

Is there anything i am doing wrong or missing anything

**Comment by chantra** [comment]
@mahadevprasad thanks for providing details on how you started atc.

> When i tried to reverse wlan0 and eth0, i could not access the URL "http://10.42.0.1:8000/atc_demo_ui/" in my android device

This should not happen, the UI (which runs the webservice) and atcd are 2 different thing and if `atcd` was not running, the UI should still load and return an error.

When you say you cannot access the URL "http://10.42.0.1:8000/atc_demo_ui/" , what do you mean?
is it refusing the connection? is it loading for ever? is your internet connection still working at this stage or you dont have any connectivity at all?
Do you see any errors in atcd logs? Any errors in the django logs?

What you are describing should work (when using the right wan and lan interface), so yes, you may be doing something wrong or missing something, but this is not obvious from what you are describing.
Please try to look for errors in the logs, this may highlight something.

**Comment by mahadevprasad** [comment]
@chantra,

My issue has been solved. There was an issue with my lan connectivity so my network shaping was not happening.

I want to know why 2 networks are required, i mean wlan0 and eth0.

I understand wlan0 is used to used to act as a router and so that my devices can connect to it. But whats the use of lan (eth0) ?

**Comment by chantra** [comment]
@mahadevprasad 
nice to hear your problem is solved.

> I want to know why 2 networks are required, i mean wlan0 and eth0.

Because routing involves at least 2 networks, wlan0 is connected to your local network (lan) and eth0 is what connects you to the internet (wan)
