### ISSUE TITLE
Shaping without requiring clients to visit the UI page?

### ISSUE THREAD

**Issue by csgrad** [facebook/augmented-traffic-control#254]
Was wondering if its possible to blanket apply a single shaping policy to all clients without them having to go to the UI page to for a requestToken?

I have ATC setup on a ddwrt router and right now have a nocatsplash redirect sending them to the UI page to enable the shaping for themselves, but I'd like to remove that step if possible.

**Comment by chantra** [comment]
@csgrad 
So there is no way to have people shaped by default but you can leverage the api on the router itself.

If you have a limited amount of clients, you could have each of them be assigned a fix ip and run a cron job on the ddwrt that shapes those ips on regular basis to ensure they are shaped.

Another possible way is to hook into you dhcpd server and do the shaping upon new lease, end of lease.... ddwrt seems to be using udhcpd, so you could leverage udhcpd's notify_file : http://manpages.ubuntu.com/manpages/trusty/man5/udhcpd.conf.5.html

if using dnsmasq, there is --dhcp-script http://linux.die.net/man/8/dnsmasq

I dont have the exact detail how those hooks work specifically, but this is something you could use and would nicely hook with the api.

If you get this working, I would be interested that you share it somewhere (github.io webpage, personal blog...) so other people can benefit from the work you have done.

Likewise, if you managed to package for dd-wrt or have a step by step instruction on how to install it, please share it so other people do not have to re-do the work.
Tks

**Comment by chantra** [comment]
So I took the time to look around you profile and ended up there :) : http://www.jasonernst.com/2016/04/04/turning-a-netgear-r7000-into-an-augmented-traffic-control-router/

Thanks!

**Comment by csgrad** [comment]
Ah thanks that's a good idea - I'll figure out that least bit and add it to the guide I've been working on!

**Comment by chantra** [comment]
@csgrad I hope the hints I gave you are helping. I will close this task for now but feel free to comment back with your discovery.

**Comment by chantra** [comment]
Had forgotten to actually close it. Hope you found a working solution.
