### ISSUE TITLE
Does weak network environment has a standard Mody?

### ISSUE THREAD

**Issue by mgjnana** [facebook/augmented-traffic-control#258]
As the title,If you want to set a standard weak network environment, which aspects should start from?

**Comment by chantra** [comment]
Hi @mgjnana 
Are you asking if it is possible to shape the traffic by default? If so, I provided some hints in https://github.com/facebook/augmented-traffic-control/issues/254

If not, I am not sure I understand the question.

**Comment by mgjnana** [comment]
no, I mean, Is there a standard to define a weak network?

**Comment by chantra** [comment]
there is no standard, but you may want to check https://github.com/facebook/augmented-traffic-control/blob/master/utils/restore-profiles.sh

**Comment by chantra** [comment]
this will set a bunch of network profiles for you.

**Comment by mgjnana** [comment]
If I want to define the criteria for a weak network, do you have any good advice, and what aspects should you start with?

**Comment by chantra** [comment]
start with the profiles provided in my previous comment and play with those to adjust to your needed. There is multiple ways in which network will be bad, from low throughput, packet loss, high latency....

**Comment by mgjnana** [comment]
This I can understand, but if I need a data support weak network standards, which should start with it? With this standard, we can confirm that the bandwidth or delay, respectively, to achieve the number of network is not available, similar to this. 
 now there is such a demand: use ATC , we can build the weak environment , but testers want to know network parameters respectively in how a data, UI see im does not connect or data refresh it is normal.
My question is whether to set the standard to start with, or to say that this is not feasible.

**Comment by chantra** [comment]
@mgjnana I am very sorry but I am having a hard time understanding what you are trying to achieve.

You are asking how the network parameters can be shown to the testers? You are saying the UI does not refresh. It should when you select to turn on/off shaping. Maybe a screenshot would help explaining your issue.
I am still not sure I really understand the issue though :s

**Comment by mgjnana** [comment]
how to set criteria for  weak network?..if they are practicable

**Comment by chantra** [comment]
@mgjnana sorry for the lack of updates, but I was away.

There is no rule of thumb on setting a weak network. I think you are talking about weak network as in weak signal?
Even 4G with a weak signal is pretty miserable. Both the quality of the signal and the type of network comes into play, as well as the underlying networks.
I dont have good values to give you ad would recommend that you start playing with some settings that you aim to have your application to support.

**Comment by mgjnana** [comment]
OK,I understand.
thanks for your replay :)
