### ISSUE TITLE
Are there other ways to set up a device network  status？

### ISSUE THREAD

**Issue by cryingDream94** [facebook/augmented-traffic-control#261]
I know you can set up the network status by ATC UI，Are there other ways to set up a device network  status？

**Comment by chantra** [comment]
@cryingDream94 
yes, you can do so by using the api directly: https://github.com/facebook/augmented-traffic-control/blob/master/atc/django-atc-api/README.md

Does that answer your question?

**Comment by cryingDream94** [comment]
@chantra 
Thank you very much.
I got a very strange question。My Android devices connected to ATC network.

When I input follow commands,it is 201CREATED :
➜  ~ adb shell
shell@cancro:/ $ curl -X POST -d '@/data/local/tmp/3G.json' -i -H 'Content-Type: application/json' -H 'Accept: application/json; indent=2' http://192.168.103.166:8000/api/v1/shape/
HTTP/1.0 201 CREATED
Date: Thu, 12 May 2016 05:48:08 GMT
Server: WSGIServer/0.1 Python/2.7.9
Vary: Accept, Cookie
X-Frame-Options: SAMEORIGIN
Content-Type: application/json; indent=2
Allow: GET, POST, DELETE, HEAD, OPTIONS

But when I input command，it shows like that：
➜  ~ adb shell curl -X POST -d '@/data/local/tmp/3G.json' -i -H 'Content-Type: application/json' -H 'Accept: application/json; indent=2' http://192.168.103.166:8000/api/v1/shape/
curl: (6) Couldn't resolve host 'application'
curl: (6) Couldn't resolve host 'application'
 
I don't know why adb shell and curl command together input not work?

**Comment by chantra** [comment]
@cryingDream94 this is because you are not escaping you command.

Try putting double quote around "curl ....... v1/shape/"

**Comment by cryingDream94** [comment]
Wow，thank you！My problem was solved。

**Comment by chantra** [comment]
@cryingDream94 happy to hear that. I understand your issue is solved now so I will close it.

**Comment by cryingDream94** [comment]
(⊙o⊙)…I thought I was a troublemaker，You are an angel！
O(∩_∩)O~~Thank you very much!!
