### ISSUE TITLE
Question on atcd with the dummy interface

### ISSUE THREAD

**Issue by kpachar** [facebook/augmented-traffic-control#274]
Hello,
I am trying to get ATC shape my traffic, but for some strange reason, I haven't been able to get it working. Could you please have a look at this setup, maybe I'm missing something in the configuration or atcd parameters?

```
                                             +------------------------------------------------------+
+---------------------+                      |                                      eth55           |
|                     |                      |          atcd --atcd-wan eth0 \    192.168.55.1      |
|                     |                      | eth0          --atcd-lan eth55                       |
|                     |                      |                                    192.168.55.2      |
|       192.168.56.104+----------------------+ 192.168.56.103                                       |
|                     |                      |                                    192.168.55.3      |
|                     |                      |                                                      |
+---------------------+                      +------------------------------------------------------+

```
Referring to the diagram above, the machine on the left (192.168.56.104) has a route set up to the 192.168.55.0/24 IPs on eth55 (dummy) that passes through its IP on eth0.
```
192.168.55.0/24 via 192.168.56.103 dev eth0
192.168.56.0/24 dev eth0  proto kernel  scope link  src 192.168.56.104
```
atcd starts up fine ([gist](https://gist.github.com/kpachar/322baa6cefe1e4b2e871fb89333d0737)) , but the traffic from 192.168.56.104 goes on at full speed to 192.168.55.*  regardless of what shaping parameters I set on atcd.

```
sudo iptables -t mangle -v -L
Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination
    0     0 MARK       all  --  eth0   any     anywhere             192.168.56.104       MARK set 0x3
    0     0 MARK       all  --  eth55  any     192.168.56.104       anywhere             MARK set 0x3

```

**Comment by smorad** [comment]
@kpachar If I'm reading this correctly, it appears that you set WAN to `eth0`, but then you connect from the client to the server's `eth0` device.

`--atcd-lan` should be the adapter your client is connecting to. `--atcd-wan` should be the device that connects to the internet.

You probably want the client (`192.168.56.104`) to connect to the `eth55` device on the server (`192.168.56.103`).

**Comment by smorad** [comment]
Additionally, the traffic will only be shaped AFTER it goes through the ATC server. When you send traffic, it gets shaped when the traffic bridges from LAN to WAN and vice-versa.

If you are sending traffic from the client to `192.168.55.1`, it will never go over the WAN, and will not be shaped.

Instead of sending data to `192.168.55.1` for testing, try using something on the WAN like `speedtest.net`.

**Comment by kpachar** [comment]
Thanks @smorad. That worked.

(I put atcd on a separate machine having two (not dummy) interfaces, each of which connect to a network between which there exists no route, and then configured iptables masquerade on that machine to route packets from one network to the other. While invoking atcd, --atcd-lan is set to the interface to the network on which the machine-that-has-the-ipaddress-equal-to-the-source-ipaddress-of-the-packets-that-are-to-be-mangled-by-atcd resides, and atcd-wan is the other interface.)
