### ISSUE TITLE
missing import in readme file

### ISSUE THREAD

**Issue by yossico** [facebook/augmented-traffic-control#275]
Hi
In the instructions of the Readme.md file of the project there is a list of changes required in the urls.py file. 
After doing those changes the project failed.
The reason was a missing import line in the url.py file
Please add this line to the change instructions:
from django.conf.urls import include
Thanks
Yossi

**Comment by smorad** [comment]
Thanks yossico! I'll put up a commit when I get a chance.

**Comment by smorad** [comment]
committed 7a85716
