### ISSUE TITLE
Is it possible for me to generate the token for a device I need to shape using an API?

### ISSUE THREAD

**Issue by VinnieM** [facebook/augmented-traffic-control#278]
Hi,
First of all thank you for such a great tool. We've been using ATC for the past couple of days and it's amazing. The question I have is pretty much against the documentation, is there a way I can generate the token for a mobile device from another machine using an API? E.G. http://192.168.2.130:8000/api/v1/token/[IP_of_mobile_device]. We were thinking of having the a complete test case which can be executed without having to manually get the token from the from the mobile device.

**Comment by chantra** [comment]
@VinnieM would using `--mode unsecure` when starting atcd solve your issue?

**Comment by VinnieM** [comment]
@chantra  Thanks a lot.... Worked like a charm....

**Comment by VinnieM** [comment]
Thanks a lot mate, it worked like a charm.

Cheers VM
Sent from a Phone running on a Linux Kernel On Wed, Jul 13, 2016 at 5:58 AM, chantra < notifications@github.com [notifications@github.com] > wrote:
@VinnieM [https://github.com/VinnieM] would using --mode unsecure when starting atcd solve your issue?
