### ISSUE TITLE
atc deploy well,but can't work

### ISSUE THREAD

**Issue by mikechengwei** [facebook/augmented-traffic-control#284]
hello.
i encountered a problem long long time...
atc service can't work. i select profile and click update shaping button. then i can't browser network.
my log is:
startShaping TrafficControl(device=TrafficControlledDevice(controllingIP='192.168.0.2', controlledIP='192.168.0.2'), timeout=86400, settings=TrafficControlSetting(down=Shaping(loss=Loss(percentage=0.0, correlation=0.0), delay=Delay(delay=350, jitter=0, correlation=0.0), rate=250, iptables_options=[], corruption=Corruption(percentage=0.0, correlation=0.0), reorder=Reorder(percentage=0.0, correlation=0.0, gap=0)), up=Shaping(loss=Loss(percentage=0.0, correlation=0.0), delay=Delay(delay=370, jitter=0, correlation=0.0), rate=200, iptables_options=[], corruption=Corruption(percentage=0.0, correlation=0.0), reorder=Reorder(percentage=0.0, correlation=0.0, gap=0))))
INFO:AtcdVService.AtcdLinuxShaper:Shaping ip 192.168.0.2 on interface eth0
INFO:AtcdVService.AtcdLinuxShaper:create new HTB class on IFID eth0, classid 1:3,parent 1:0, rate 200kbits
INFO:AtcdVService.AtcdLinuxShaper:create new Netem qdisc on IFID eth0, parent 1:3, loss 0.0%, delay 370000
INFO:AtcdVService.AtcdLinuxShaper:create new FW filter on IFID eth0, classid 1:3, handle 3, rate: 200kbits
INFO:AtcdVService.AtcdLinuxShaper:Running /sbin/iptables -t mangle -A FORWARD -d 192.168.0.2 -i eth0 -j MARK --set-mark 3
INFO:AtcdVService.AtcdLinuxShaper:Shaping ip 192.168.0.2 on interface wlan0
INFO:AtcdVService.AtcdLinuxShaper:create new HTB class on IFID wlan0, classid 1:3,parent 1:0, rate 250kbits
INFO:AtcdVService.AtcdLinuxShaper:create new Netem qdisc on IFID wlan0, parent 1:3, loss 0.0%, delay 350000
INFO:AtcdVService.AtcdLinuxShaper:create new FW filter on IFID wlan0, classid 1:3, handle 3, rate: 250kbits
INFO:AtcdVService.AtcdLinuxShaper:Running /sbin/iptables -t mangle -A FORWARD -s 192.168.0.2 -i wlan0 -j MARK --set-mark 3
INFO:AtcdVService.AtcdLinuxShaper:Unshaping ip 192.168.0.2 on interface eth0
INFO:AtcdVService.AtcdLinuxShaper:Running /sbin/iptables -t mangle -D FORWARD -d 192.168.0.2 -i eth0 -j MARK --set-mark 2
INFO:AtcdVService.AtcdLinuxShaper:deleting filter on IFID eth0, handle 2
INFO:AtcdVService.AtcdLinuxShaper:deleting class on IFID eth0, classid 1:2
INFO:AtcdVService.AtcdLinuxShaper:Unshaping ip 192.168.0.2 on interface wlan0
INFO:AtcdVService.AtcdLinuxShaper:Running /sbin/iptables -t mangle -D FORWARD -s 192.168.0.2 -i wlan0 -j MARK --set-mark 2
INFO:AtcdVService.AtcdLinuxShaper:deleting filter on IFID wlan0, handle 2
INFO:AtcdVService.AtcdLinuxShaper:deleting class on IFID wlan0, classid 1:2
INFO:AtcdVService.AtcdLinuxShaper:Request requestToken(192.168.0.2, 259200)
INFO:AtcdVService.AtcdLinuxShaper:Request requestToken(192.168.0.2, 259200)

please help help  me .

**Comment by chantra** [comment]
cc @smorad

**Comment by chantra** [comment]
@mikechengwei can you try using the extra flag: `--dont-drop-packets` when starting `ATCD` does that helps?

**Comment by mikechengwei** [comment]
It works.thanks!

**Comment by mikechengwei** [comment]
It works.thanks! @chantra

**Comment by chantra** [comment]
cool!
