### ISSUE TITLE
Unable to set ATC on Ubuntu

### ISSUE THREAD

**Issue by nikunj0123** [facebook/augmented-traffic-control#285]
I am not able to set ATC on Ubuntu. 

Followed mentioned steps from below url:-

http://facebook.github.io/augmented-traffic-control/docs/install.html

Please point me with the correct steps so that I can set up in my Ubuntu box.
<img width="1309" alt="screen shot 2016-08-02 at 2 56 57 pm" src="https://cloud.githubusercontent.com/assets/20096456/17438522/e10e604a-5b40-11e6-8ddd-0bd8a8485796.png">

**Comment by chantra** [comment]
cc @smorad 

@nikunj0123 can you try installing from master? There is a few updates that needs to be pushed to `pip` but for now, you will be better off installing from master.

**Comment by chantra** [comment]
@nikunj0123 did you get a chance to try installing from master?

**Comment by nikunj0123** [comment]
@chantra .Yes But was not able to install it. Can you please guide me with proper steps?

**Comment by chantra** [comment]
@nikunj0123 I have pushed version 0.1.4, you may want to give it a try.

**Comment by nikunj0123** [comment]
Sure. Thanks a lot. One more question does it support on MAC.

**Comment by chantra** [comment]
@nikunj0123 nope, this is IP based only.

**Comment by nikunj0123** [comment]
Okay. Can I have your gmail id please.

**Comment by nikunj0123** [comment]
Its fine I will try and will get in touch if I find any issue.

**Comment by chantra** [comment]
@nikunj0123 feel free to join #atcd irc channel on freenode.

**Comment by nikunj0123** [comment]
@chantra Thanks a lot.
