### ISSUE TITLE
Unable to create profiles - {"content":["Not a valid string."]}

### ISSUE THREAD

**Issue by jrmfreitas88** [facebook/augmented-traffic-control#287]
Hello,

I am not able to create profiles. Everything works fine, I am able to apply/remove the shaping policies however, every time I try to save a profile I get the following error (observed on both curl and wireshark traces).

**{"content":["Not a valid string."]}**

- Wireshark Trace:
![trace](https://cloud.githubusercontent.com/assets/15096532/17749240/b95227c6-64b4-11e6-82eb-99d50ec46349.png)

- ATC Demo UI Logs:
![profiles_error](https://cloud.githubusercontent.com/assets/15096532/17749266/d1ffb81a-64b4-11e6-849a-0ff3db971d7c.png)

This happens when using the atc_demo_ui or performing manual curl requests. I have also tried running the "restore-profiles.sh" scripts but, even though no errors are reported, still no profiles are added.

I have followed the installation instructions at "https://github.com/facebook/augmented-traffic-control":

1. Performed pip install;
2. Created new django project;
3. Updated the atcui/settings.py;
4. Updated the atcui/urls.py;
5. Started atcd daemon;
6. Started django atcdemoui.

- Additional notes:

Python Version = 2.7.9
Django Version = 1.8.3 (Same version as the docker image. I have previously tried with version 1.7.x but was having issues)

Looking forward for support.

Kind regards,

João

**Comment by gu-wei** [comment]
I have the same issue

**Comment by chantra** [comment]
cc @smorad

**Comment by chantra** [comment]
@gu-wei  @jrmfreitas88 can you please try https://github.com/chantra/augmented-traffic-control/tree/fix_287

**Comment by jrmfreitas88** [comment]
@chantra , @gu-wei , it works with fix_287. Thanks for the support :+1: 

Nevertheless, it only works with the zip version (https://github.com/chantra/augmented-traffic-control/archive/fix_287.zip).

For some reason the "git clone https://github.com/chantra/augmented-traffic-control.git" version is lacking some folders such as the "utils" and also some files are different. This is easy to spot by running the "diff" command on both sources.

**Comment by chantra** [comment]
@jrmfreitas88 
`git clone` would have put you on the master branch of my repo, which is very outdated as it did not push chantra/master in a while.
If you checkout the `fix_287` branch, it should be there.

**Comment by jrmfreitas88** [comment]
@chantra
Indeed! I just double checked it. Thanks once again.

**Comment by chantra** [comment]
pushing v0.1.5 to pypi.
