### ISSUE TITLE
shape error: adding NetEm qdisc on IFID vlan2, mark 2, err: (2, 'No such file or directory')

### ISSUE THREAD

**Issue by gu-wei** [facebook/augmented-traffic-control#292]
I set up the atc environment on DD-WRT(kernal Linux 3.10.102) on my Ausus RT-N66U. Everything works fine except when I start to shape a device. I got the error: **adding NetEm qdisc on IFID vlan2, mark 2, err: (2, 'No such file or directory')**.
Does ATC support running on DD-WRT? thank you very [much!]
![shape_error2](https://cloud.githubusercontent.com/assets/10619712/18022209/d64a2d26-6ba1-11e6-941c-bb47815f8f0d.png)

**Comment by smorad** [comment]
DD-WRT does run the full Linux kernel, so in theory DD-WRT should be supported.

https://github.com/facebook/augmented-traffic-control/blob/e4eab1fe6a8cf5acdf22e511ebad39f3c5ef5f61/atc/atcd/atcd/backends/linux.py#L424

It may be that the version of `tc` that ships with DD-WRT is too old. Which source did you install ATC from?

**Comment by gu-wei** [comment]
I followed instructions from: http://facebook.github.io/augmented-traffic-control/docs/install.html
and use pip to install the ATC

**Comment by chantra** [comment]
@gu-wei what is the output of ```ip a``` ? or `ifconfig` if the former is not available.

**Comment by chantra** [comment]
Actually, reading the logs, it seems this is because the `netem` module may not be compiled in the kernel. Can you check:
```
grep -i netem /boot/config-
```

**Comment by gu-wei** [comment]
thank you very much for helping me on this!

 1. output of **ip a**:
![ip-a](https://cloud.githubusercontent.com/assets/10619712/18060613/1ea92520-6dd4-11e6-9b95-53da5c3378d9.png)

2. output of **ifconfig**:
![ifconfig](https://cloud.githubusercontent.com/assets/10619712/18060630/33cc439c-6dd4-11e6-84b6-196bf383ce55.png)

3. there is no **/boot** in DD-WRT linux

**Comment by gu-wei** [comment]
I also post on the dd-wrt forum: http://www.dd-wrt.com/phpBB2/viewtopic.php?p=1044887#1044887
for the netem/tc issue in dd-wrt.  and I will keep updating on this.

**Comment by chantra** [comment]
@gu-wei 

We first need to asses if DD-WRT has the netem module compiled in. I have no access to dd-wrt so you may be on your own here but here are a few suggestions:

* `find /lib/modules/$(uname -r)/ -name '*netem*'`
* play with the tc command directly and see if you can set netem or not.

**Comment by chantra** [comment]
@gu-wei 
thanks for cross-posting to the dd-wrt forum. I think this is the issue here. Let us know if you manage to solve this.

**Comment by chantra** [comment]
@gu-wei 
from looking at https://downloads.openwrt.org/attitude_adjustment/12.09/ar71xx/generic/packages/
you need to install `kmod-netem`

Does that help?

**Comment by gu-wei** [comment]
@chantra your url  is for openwrt while i am using dd-wrt. here the bug I filed: http://www.dd-wrt.com/dd-wrtv2/bugtracker/view.php?id=4792
I may flash the router to use openwrt. thanks for the help.

**Comment by chantra** [comment]
@gu-wei the point is.. can you install `kmod-netem` on dd-wrt?

I will close this issue as there is not much that can be done from ATC side, please comment back here when you manage to get it running and explain how.
tks
