### ISSUE TITLE
I set up an enterprise's weak network simulation base ATC，but it not work。

### ISSUE THREAD

**Issue by HarrisonLin** [facebook/augmented-traffic-control#293]
**I set up an enterprise's weak network simulation base ATC，but it not work。**

Network topology：

![4](https://cloud.githubusercontent.com/assets/10679283/18039546/ace31876-6dd6-11e6-944a-07800ce541dd.png)

alpha  is my enterprise Network environment。

I should how to troubleshoot the problem？

Log：

INFO:AtcdVService.AtcdLinuxShaper:Request startShaping TrafficControl(device=TrafficControlledDevice(controllingIP='10.54.4.155', controlledIP='10.54.4.155'), timeout=86400, settings=TrafficControlSetting(down=Shaping(loss=Loss(percentage=2.0, correlation=0.0), delay=Delay(delay=650, jitter=0, correlation=0.0), rate=18, iptables_options=[], corruption=Corruption(percentage=0.0, correlation=0.0), reorder=Reorder(percentage=0.0, correlation=0.0, gap=0)), up=Shaping(loss=Loss(percentage=2.0, correlation=0.0), delay=Delay(delay=650, jitter=0, correlation=0.0), rate=18, iptables_options=[], corruption=Corruption(percentage=0.0, correlation=0.0), reorder=Reorder(percentage=0.0, correlation=0.0, gap=0))))
INFO:AtcdVService.AtcdLinuxShaper:Shaping ip 10.54.4.155 on interface eth0
INFO:AtcdVService.AtcdLinuxShaper:create new HTB class on IFID eth0, classid 1:2,parent 1:0, rate 18kbits
INFO:AtcdVService.AtcdLinuxShaper:create new Netem qdisc on IFID eth0, parent 1:2, loss 2.0%, delay 650000
INFO:AtcdVService.AtcdLinuxShaper:create new FW filter on IFID eth0, classid 1:2, handle 2, rate: 18kbits
INFO:AtcdVService.AtcdLinuxShaper:Running /sbin/iptables -t mangle -A FORWARD -d 10.54.4.155 -i eth0  -j MARK --set-mark 2
INFO:AtcdVService.AtcdLinuxShaper:Shaping ip 10.54.4.155 on interface eth1
INFO:AtcdVService.AtcdLinuxShaper:create new HTB class on IFID eth1, classid 1:2,parent 1:0, rate 18kbits
INFO:AtcdVService.AtcdLinuxShaper:create new Netem qdisc on IFID eth1, parent 1:2, loss 2.0%, delay 650000
INFO:AtcdVService.AtcdLinuxShaper:create new FW filter on IFID eth1, classid 1:2, handle 2, rate: 18kbits
INFO:AtcdVService.AtcdLinuxShaper:Running /sbin/iptables -t mangle -A FORWARD -s 10.54.4.155 -i eth1  -j MARK --set-mark 2
INFO:AtcdVService.AtcdLinuxShaper:Request stopShaping for ip 10.54.4.155
INFO:AtcdVService.AtcdLinuxShaper:Unshaping ip 10.54.4.155 on interface eth0
INFO:AtcdVService.AtcdLinuxShaper:Running /sbin/iptables -t mangle -D FORWARD -d 10.54.4.155 -i eth0  -j MARK --set-mark 2
INFO:AtcdVService.AtcdLinuxShaper:deleting filter on IFID eth0, handle 2
INFO:AtcdVService.AtcdLinuxShaper:deleting class on IFID eth0, classid 1:2
INFO:AtcdVService.AtcdLinuxShaper:Unshaping ip 10.54.4.155 on interface eth1
INFO:AtcdVService.AtcdLinuxShaper:Running /sbin/iptables -t mangle -D FORWARD -s 10.54.4.155 -i eth1  -j MARK --set-mark 2
INFO:AtcdVService.AtcdLinuxShaper:deleting filter on IFID eth1, handle 2
INFO:AtcdVService.AtcdLinuxShaper:deleting class on IFID eth1, classid 1:2

**Comment by smorad** [comment]
The logs look fine to me. What do you mean by not working? Is the daemon crashing, is traffic not being shaped?

**Comment by HarrisonLin** [comment]
traffic not being shaped。

**Comment by HarrisonLin** [comment]
i don`t know that is ip cause traffic not being shaped ？

devices connect alpha wifi ,   ip of devices  is :  10.54.0.1/16  ,  but connect network by 172.17.0.12/22.

**Comment by chantra** [comment]
@HarrisonLin how did you start atcd? It looks like you should be using `eth1` a WAN and `eth0` as LAN, but you are shaping with `--lan eth` --wan eth0`

**Comment by HarrisonLin** [comment]
**Previously configured successfully on My Ubuntu.（HotSpot-AP Mode is OK）**


But now I want to build it for the company。

I try using every mode，but traffic not being shaped.  

eth1 as WAN  eth0 as LAN.
eth1.54 as WAN eth0.54 as LAN
eth0 as WAN eth1 as LAN
eth0.54 as WAN eth1.54 as LAN

So I guess alpha-wifi and H3C switch configure is error？

Log：

(MeiliWeakNetwork) [root@localhost MeiliWeakNetwork]# **atcd --atcd-lan eth0 --atcd-wan eth1**

INFO:AtcdVService.AtcdNBServerTask:AtcdNBServerTask Server Started on 127.0.0.1:9090
INFO:AtcdVService.AtcdLinuxShaper:Calling initialize_shaping_system
INFO:AtcdVService.AtcdLinuxShaper:Running /sbin/iptables -t mangle -F FORWARD
INFO:AtcdVService.AtcdLinuxShaper:deleting root QDisc on eth0
INFO:AtcdVService.AtcdLinuxShaper:setting root qdisc on eth0
INFO:AtcdVService.AtcdLinuxShaper:deleting root QDisc on eth1
INFO:AtcdVService.AtcdLinuxShaper:setting root qdisc on eth1
INFO:AtcdVService.AtcdLinuxShaper:Restoring shaped connection from DB
DEBUG:AtcdVService:All tasks started
DEBUG:AtcdVService:VService Active.  Awaiting graceful shutdown.
INFO:AtcdVService.AtcdLinuxShaper:Request getCurrentShaping for ip 10.54.1.254

INFO:AtcdVService.AtcdLinuxShaper:Request startShaping TrafficControl(device=TrafficControlledDevice(controllingIP='10.54.1.254', controlledIP='10.54.1.254'), timeout=86400, settings=TrafficControlSetting(down=Shaping(loss=Loss(percentage=2.0, correlation=0.0), delay=Delay(delay=650, jitter=0, correlation=0.0), rate=18, iptables_options=[], corruption=Corruption(percentage=0.0, correlation=0.0), reorder=Reorder(percentage=0.0, correlation=0.0, gap=0)), up=Shaping(loss=Loss(percentage=2.0, correlation=0.0), delay=Delay(delay=650, jitter=0, correlation=0.0), rate=18, iptables_options=[], corruption=Corruption(percentage=0.0, correlation=0.0), reorder=Reorder(percentage=0.0, correlation=0.0, gap=0))))
INFO:AtcdVService.AtcdLinuxShaper:Shaping ip 10.54.1.254 on interface eth1
INFO:AtcdVService.AtcdLinuxShaper:create new HTB class on IFID eth1, classid 1:2,parent 1:0, rate 18kbits
INFO:AtcdVService.AtcdLinuxShaper:create new Netem qdisc on IFID eth1, parent 1:2, loss 2.0%, delay 650000
INFO:AtcdVService.AtcdLinuxShaper:create new FW filter on IFID eth1, classid 1:2, handle 2, rate: 18kbits
INFO:AtcdVService.AtcdLinuxShaper:Running /sbin/iptables -t mangle -A FORWARD -d 10.54.1.254 -i eth1  -j MARK --set-mark 2
INFO:AtcdVService.AtcdLinuxShaper:Shaping ip 10.54.1.254 on interface eth0
INFO:AtcdVService.AtcdLinuxShaper:create new HTB class on IFID eth0, classid 1:2,parent 1:0, rate 18kbits
INFO:AtcdVService.AtcdLinuxShaper:create new Netem qdisc on IFID eth0, parent 1:2, loss 2.0%, delay 650000
INFO:AtcdVService.AtcdLinuxShaper:create new FW filter on IFID eth0, classid 1:2, handle 2, rate: 18kbits
INFO:AtcdVService.AtcdLinuxShaper:Running /sbin/iptables -t mangle -A FORWARD -s 10.54.1.254 -i eth0  -j MARK --set-mark 2

**Comment by HarrisonLin** [comment]
![image](https://cloud.githubusercontent.com/assets/10679283/18078929/bf77c2da-6ec0-11e6-96d8-b8ff5bf4955d.png)

This is my design network structure。

My server Network card information

![wechatimg2](https://cloud.githubusercontent.com/assets/10679283/18078986/0a702e8a-6ec1-11e6-8005-b3411c1be798.jpeg)

bridge info

![wechatimg3](https://cloud.githubusercontent.com/assets/10679283/18079012/3133cc16-6ec1-11e6-9c3c-fb418fb71c7b.jpeg)

**Comment by chantra** [comment]
@HarrisonLin ATC works at layer 3. By bridging interfaces, you are bypassing ATC being a router and being able to act on packets.
Please remove the interfaces from the bridge and route between networks.

If you still have issues without using a bridge, please feel free to open a new issue. For now, I will close this task as your setup is not not meeting the requirements.

**Comment by HarrisonLin** [comment]
Now  I can`t use route mode ，because my company network structure can`t change.

ATC works at layer 3？ can`t support bridge?

ATC use tc  and iptables。  Linux tc works at layer 2， where layer set iptables mark ?

**Comment by chantra** [comment]
ATC set the marks in the FORWARD chain https://github.com/facebook/augmented-traffic-control/blob/master/atc/atcd/atcd/backends/linux.py#L364

**Comment by HarrisonLin** [comment]
all traffic entry root 。  did not enter class.  why？

![111](https://cloud.githubusercontent.com/assets/10679283/18113928/d9debab6-6f65-11e6-96fc-ca5700dd7087.jpg)

I don t know  why can t support bridge mode， I think should be ok

I want to understand it

**Comment by chantra** [comment]
@HarrisonLin 
When using a bridge, there is no routing happening. ATC **requires** the traffic to be routed through the host, not bridged. You may be able to get this working if you manage to get the packets mangled by iptables (and you should verify that some packets are being mangled using `iptables -t mangle -L -v -n`).
This is not a use case we do support though, so we can't really help you here other than giving you the few advises I have given you so far.
That being said, if you manage to get this running, please let us know so people may be able to benefit from the work you did to get this working.

**Comment by HarrisonLin** [comment]
@chantra 
OK，Thank you。

if it running , I will tell you the reasons.

**Comment by HarrisonLin** [comment]
Do the below changes can be running:

1、iptables rule change 
    iptables -A FORWARD -t mangle -s <client ip> -m physdev --physdev-in eth1 --physdev-out eth0 -j MARK --set-xmark 0x2/0xffffffff
   iptables -A FORWARD -t mangle -d <client ip> -m physdev --physdev-in eth0 --physdev-out eth1 -j MARK --set-xmark 0x2/0xffffffff

2、load netfilter module（iptables services）
   
3、enable netfilter in bridge
   echo 1 > /proc/sys/net/bridge/bridge-nf-call-iptables

![wechatimg4](https://cloud.githubusercontent.com/assets/10679283/18152940/79a7dab6-702c-11e6-9885-ab3af6ce84d0.jpeg)

So I need change ATC linux.py set_iptables code。

My project that use pip install ,  how to update it ？

**Comment by chantra** [comment]
@HarrisonLin 
Nice finding! You can pip install from source if that helps.

I assume you meant:
```
iptables -A FORWARD -t mangle -s 10.54.4.155/32 -m physdev --physdev-in eth1 --physdev-out eth0 -j MARK --set-xmark 0x2/0xffffffff
iptables -A FORWARD -t mangle -d 10.54.4.155/32 -m physdev --physdev-in eth0 --physdev-out eth1 -j MARK --set-xmark 0x2/0xffffffff
```

Alternatively, you can turn that in a pull request. I will be happy to review a diff that adds an option to run in bridged mode which is off by default.
