### ISSUE TITLE
Help needed setup ATC

### ISSUE THREAD

**Issue by Ashishjshetty** [facebook/augmented-traffic-control#294]
I have done the following:

1. started atcd , using following command:
` sudo atcd  --atcd-lan eth0 --atcd-wan wlan0`, get the following [output](https://gist.github.com/Ashishjshetty/7cfa2d81e644ec44e4faa247e33cb1a1):

   it wont work without parameters [output](https://gist.github.com/Ashishjshetty/3675f19cabd2a3159010f62d84937c0c)

2. after i start atcd successfully i run atc UI

3. start a wifi access point and connect a device and do speed test after shaping network on UI.

now i am able to shape it has no difference over network still get full speed.

Do let me know if you need any other output.

**Comment by chantra** [comment]
@Ashishjshetty 
It does not work without specifying the wan/lan parameters because it would default to `eth0` and `eth1`.

You are most likely reverting wlan0 and eth0. If you use eth0 to connect to the internet, etho is your **wan** interface. Use:
```
sudo atcd --atcd-wan eth0 --atcd-lan wlan0
```
instead.

Does this solve your problem?

**Comment by Ashishjshetty** [comment]
@chantra , Thanks for you prompt response, It doesn't solve the problem still see no changes to speed after shaping here is the [output](https://gist.github.com/Ashishjshetty/e9a1dba9dedddd9ab818703f5e6278f9) of atcd after shaping , the only change i made to shaping settings is set bandwidth to 10kbps both up and down link.

**Comment by chantra** [comment]
@Ashishjshetty Can you please answer the checklist provided when filling a new issue: https://github.com/facebook/augmented-traffic-control/issues/new

This should give details about your setting that will help in troubleshooting your issue.
tks

**Comment by Ashishjshetty** [comment]
**Meeting the requirements:**
**ATC** has a few requirements, this section is used to make sure the requirements are met. Until you can check all the boxes, **ATC** will not work on your system.
- [x] `atcd` runs on Linux
- [x] `atcd` has 2 physical interfaces
- [x] 1 that connects to the internet (WAN)
- [x] 1 that connects to the local network (LAN)
- [x] the traffic from the devices that are being shaped is routed through `atcd`
- [x] `atcd` sees the real IP of the devices (e.g there is no **NAT** on the LAN segment)

**Checking for special atcd options:**

In some cases, `atcd` default configuration may not be suitable for your system. Use:
```
atcd -h
```
do change those default to suit your setup.
For instance, if your lan interface is `wlan0`, you should start `atcd` using:
```
atcd --atcd-lan wlan0
```

**Steps to reproduce the issue:**
1. sudo atcd --atcd-wan eth0 --atcd-lan wlan0
2. start access-point for my device to connect to network
3. start UI server ,turn on.
4. shape network set uplink bandwidth to 10kbps,set down-link bandwidth to 10kbps and update.


**Describe the results you received:**
Connected mobile device to Access-point, did a speed test saw no change in speed , device gets full speed around 1.5 mbps.

**Describe the results you expected:**
I expected it to be 10kbps download speed and 10kbps upload speed. 


**Any additional information that you think is important:**
I want to test my application and see how it performs in low internet speeds. I am not sure where i am going wrong. The device is getting access to internet using my Access point , which is configured with atcd

**Dumping system info:**

[system-info](https://gist.github.com/Ashishjshetty/6ec0f63b3490e28c1d3ea6ec91e14b52)

**Comment by chantra** [comment]
Thanks @Ashishjshetty 

For some reason, the output of `iptables-save` is empty, which would explain why the traffic is not being shaped.

Can you check what happen when you run:
```
/sbin/iptables -t mangle -A FORWARD -d 192.168.1.101 -i eth0  -j MARK --set-mark 4
```

Manually. I believe this will fail with an error message because `iptables` may be somewhere else.
`which iptables` will tell you where. You should start ATC with the iptables option (available in help) and override the default.

The issue is that the return code from the iptables command is not checked:
https://github.com/facebook/augmented-traffic-control/blob/master/atc/atcd/atcd/backends/linux.py#L387

**Comment by Ashishjshetty** [comment]
Hi @chantra ,
They result is empty ie. no output. Is that normal?

**Comment by chantra** [comment]
nope, see the rest of my comment

**Comment by Ashishjshetty** [comment]
Yes my iptables location is same as you mentioned 'which iptables' outputs `/sbin/iptables` , now i ran atcd again using `sudo atcd --atcd-wan eth0 --atcd-lan wlan0 --atcd-iptables /sbin/iptables` still no success

**Comment by Ashishjshetty** [comment]
This is the output i get on console .[output](https://gist.github.com/Ashishjshetty/42b1181b05820fcfc66e3877ce78c998)

**Comment by chantra** [comment]
What was not normal was to have the output of `iptables-save` empty.. did you run the script as root? What is the output of `iptables-save` if you run it manually as root?

**Comment by Ashishjshetty** [comment]
Yes i ran the command using `sudo`, the output of `sudo iptables-save` is [here](https://gist.github.com/Ashishjshetty/1822795d4066987227d3836ddd3b4e4e)

**Comment by chantra** [comment]
@Ashishjshetty 
I am confused... iptables-save shows that the hosts that are shaped are in range 192.168.1.0/24, which is your WAN network, the network going to the internet. The devices that you want to shape should be in the wireless network (LAN), it is expected that when you shape a device, the mangle table shows ips in range 10.42.0.0/24 .

The devices should be connected to the wireless network AND only the wireless network, if they are also connected to a wired network (mainly on 192.168.1.0/24), the devices will use this as the primary network.

What kind of device are you trying to shape, can you show me the ip setting of one of them? (ip address and routing).

**Comment by Ashishjshetty** [comment]
@chantra ,
Ok i will just give you a brief idea of my setup and what i am trying to do. May be that will help. I have a laptop that is connected to Ethernet cable that i am using as the source of internet, and i intend to create a access-point that i can connect my android phone to use internet. Now my main intent is to shape the internet connection going to my phone using my laptop's access-point and test my mobile app.  Now the steps i took are:

1. start a accesspoint

2. start atcd using following command `sudo atcd --atcd-wan eth0 --atcd-lan wlan0` .[output](https://gist.github.com/Ashishjshetty/1451e573558c3c5c46dae3fddf87a95e)

3. start atc GUI `python manage.py runserver 0.0.0.0:8000`

4. shape atc usiing GUI `UPLINK 10kbps and DOWNLINK 10kbps`.

5. connect my mobile device to the laptop access-point and my mobile device ip address is `10.42.0.25`.

6. Do a speed test. which results to no change in internet speed i am still getting full speed       

Output of iptables-save [here](https://gist.github.com/Ashishjshetty/c70de14ac6627718b005f4dd1c10889c)

Now i don't think there is anything wrong with ATC, I think may have i missed something. I ran everything again and have posted fresh outputs. If there is any other output you need do let me know.

**Comment by chantra** [comment]
@Ashishjshetty you need to initiate the shaping from the mobile device. Shaping is done per device and we use the ip of the device connecting to ATC ui to find out what ip to shape.

**Comment by Ashishjshetty** [comment]
@chantra Thanks a lot for all the help, I have been struggling with this for a few days. I may have missed it in documentation.
