### ISSUE TITLE
Unable to run vagrant up trusty

### ISSUE THREAD

**Issue by cabahug2** [facebook/augmented-traffic-control#300]
I downloaded zip files vagrant-berkshelf and vagrant-omnibus from Github and manually installed them (gem build name.gemspec then vagrant plugin install name.gem). When I try to run vagrant up trusty from chef/atc, I get the following errors:

Unknown configuration section 'berkshelf'.
Unknown configuration section 'omnibus'.

vagrant plugin list gives:
vagrant-berkshelf (5.0.0)
vagrant-libvirt (0.0.26, system)
vagrant-omnibus (1.5.0)

I verified that the plugins were indeed installed by checking that their gemspecs and .gems were in
~/.vagrant.d/gems/specifications/ and ~/.vagrant.d/gems/gems/ 

Any idea what I could be doing wrong?

**Comment by chantra** [comment]
Hi,
This is pretty much a vagrant or vagrant plug-in issue. I don't have good advice to give you put searching for help on those specific projects.

**Comment by chantra** [comment]
@cabahug2 did you manage to fix your problem? I will close this issue for now as this is not a atc issue per se.
