### ISSUE TITLE
Turn on 'Cable' profile could not access any website, testing the network connecting is 0.1kb/s

### ISSUE THREAD

**Issue by AskForHelppp** [facebook/augmented-traffic-control#302]
I set up the ATC in my ubuntu14.04. And use one android device to connect the wifi.
I download the exciting profile form  Github, and turn on "Cable" profile from the mobile.
Found it could not connect any website and when I testing the network connect, it says 0.1kb for download. 
Before I turn on the profile, I can access the website.

`
INFO:AtcdVService.AtcdLinuxShaper:Request startShaping TrafficControl(device=TrafficControlledDevice(controllingIP='192.168.0.100', controlledIP='192.168.0.100'), timeout=86400, settings=TrafficControlSetting(down=Shaping(loss=Loss(percentage=0.0, correlation=0.0), delay=Delay(delay=2, jitter=0, correlation=0.0), rate=6000, iptables_options=[], corruption=Corruption(percentage=0.0, correlation=0.0), reorder=Reorder(percentage=0.0, correlation=0.0, gap=0)), up=Shaping(loss=Loss(percentage=0.0, correlation=0.0), delay=Delay(delay=2, jitter=0, correlation=0.0), rate=1000, iptables_options=[], corruption=Corruption(percentage=0.0, correlation=0.0), reorder=Reorder(percentage=0.0, correlation=0.0, gap=0))))
INFO:AtcdVService.AtcdLinuxShaper:Shaping ip 192.168.0.100 on interface eth0
INFO:AtcdVService.AtcdLinuxShaper:create new HTB class on IFID eth0, classid 1:2,parent 1:0, rate 1000kbits
INFO:AtcdVService.AtcdLinuxShaper:create new Netem qdisc on IFID eth0, parent 1:2, loss 0.0%, delay 2000
INFO:AtcdVService.AtcdLinuxShaper:create new FW filter on IFID eth0, classid 1:2, handle 2, rate: 1000kbits
INFO:AtcdVService.AtcdLinuxShaper:Running /sbin/iptables -t mangle -A FORWARD -d 192.168.0.100 -i eth0  -j MARK --set-mark 2
INFO:AtcdVService.AtcdLinuxShaper:Shaping ip 192.168.0.100 on interface wlan0
INFO:AtcdVService.AtcdLinuxShaper:create new HTB class on IFID wlan0, classid 1:2,parent 1:0, rate 6000kbits
INFO:AtcdVService.AtcdLinuxShaper:create new Netem qdisc on IFID wlan0, parent 1:2, loss 0.0%, delay 2000
INFO:AtcdVService.AtcdLinuxShaper:create new FW filter on IFID wlan0, classid 1:2, handle 2, rate: 6000kbits
INFO:AtcdVService.AtcdLinuxShaper:Running /sbin/iptables -t mangle -A FORWARD -s 192.168.0.100 -i wlan0  -j MARK --set-mark 2
INFO:AtcdVService.AtcdLinuxShaper:Request requestToken(127.0.0.1, 259200)
INFO:AtcdVService.AtcdLinuxShaper:Request requestToken(192.168.0.100, 259200)
INFO:AtcdVService.AtcdLinuxShaper:Request requestToken(127.0.0.1, 259200)
INFO:AtcdVService.AtcdLinuxShaper:Request requestToken(192.168.0.100, 259200)
`

Does anyone else met the same problem. Anyone can help?

More Detail info:

1. Environment:
    - vm:ubuntu14.04
    - hostapd: v2.1
    - dhcpd: 4.2.4
    - django: 1.10
    - Python: 2.7
2. Setting:
    - atc@atc-virtual-machine:~/atcui$ ifconfig
       eth0:      
             Link encap:Ethernet  HWaddr 00:0c:29:2d:c1:d1  
             inet addr:192.168.174.129  Bcast:192.168.174.255  Mask:255.255.255.0
             inet6 addr: fe80::20c:29ff:fe2d:c1d1/64 Scope:Link
             UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
             RX packets:27056 errors:0 dropped:0 overruns:0 frame:0
             TX packets:13486 errors:0 dropped:0 overruns:0 carrier:0
             collisions:0 txqueuelen:1000 
             RX bytes:25847947 (25.8 MB)  TX bytes:2117805 (2.1 MB)

       lo
          Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:1671 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1671 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:154253 (154.2 KB)  TX bytes:154253 (154.2 KB)

      wlan0
          Link encap:Ethernet  HWaddr 38:83:45:18:cd:43  
          inet addr:192.168.0.1  Bcast:192.168.0.255  Mask:255.255.255.0
          inet6 addr: fe80::3a83:45ff:fe18:cd43/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:2684 errors:0 dropped:0 overruns:0 frame:0
          TX packets:3154 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:257983 (257.9 KB)  TX bytes:3371757 (3.3 MB)

    - Changing in the dhcp file:
        subnet 192.168.0.0 netmask 255.255.255.0
        {
            range 192.168.0.100 192.168.0.200;
            option routers 192.168.0.1;
            option domain-name-servers 192.168.174.2;
        }

    - File of hostapd.conf:
        interface=wlan0
        driver=nl80211
        ssid=ATC
        hw_mode=g
        channel=10
        macaddr_acl=0
        auth_algs=3
        wpa=2
        wpa_passphrase=123456789
        wpa_key_mgmt=WPA-PSK
        wpa_pairwise=TKIP CCMP
        rsn_pairwise=TKIP CCMP

    - The command:
        ifconfig wlan0 192.168.0.1 netmask 255.255.255.0
        bash -c "echo 1 >/proc/sys/net/ipv4/ip_forward"
        iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
        hostapd -B /etc/hostapd/hostapd.conf

**Comment by smorad** [comment]
What do you have set for your `--atcd-wan` and `--atcd-lan` interfaces?

**Comment by chantra** [comment]
@AskForHelppp can you try using `--atcd-dont-drop-packets` command with atcd. Does that help?

**Comment by AskForHelppp** [comment]
@smorad  I set: atcd --atcd-wan eth0 --atcd-lan wlan0

**Comment by AskForHelppp** [comment]
@chantra --atcd-dont-drop-packets this command makes it work.  I checked some closed issue found the same error. 
Next time I should go through all the closed issue to see if already got some solution. Thanks!
