### ISSUE TITLE
Does Augmented traffic control supports on Windows system or MacOSX ?

### ISSUE THREAD

**Issue by kavithaks** [facebook/augmented-traffic-control#320]
**Meeting the requirements:**
**ATC** has a few requirements, this section is used to make sure the requirements are met. Until you can check all the boxes, **ATC** will not work on your system.
- [ ] `atcd` runs on Linux
- [ ] `atcd` has 2 physical interfaces
 - [ ] 1 that connects to the internet (WAN)
 - [ ] 1 that connects to the local network (LAN)
- [ ] the traffic from the devices that are being shaped is routed through `atcd`
- [ ] `atcd` sees the real IP of the devices (e.g there is no **NAT** on the LAN segment)

**Checking for special atcd options:**

In some cases, `atcd` default configuration may not be suitable for your system. Use:
```
atcd -h
```
do change those default to suit your setup.
For instance, if your lan interface is `wlan0`, you should start `atcd` using:
```
atcd --atcd-lan wlan0
```

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Any additional information that you think is important:**

**Dumping system info:**

While this may not be required in many cases, providing the following information will help us better understand your setup.

**NOTE**: before putting the output on gist, please check its content is fine to be publically available

Run https://github.com/facebook/augmented-traffic-control/blob/master/utils/dump_system_info.sh and upload the content of the logs to [https://gist.github.com/](gist)

```
curl https://raw.githubusercontent.com/facebook/augmented-traffic-control/master/utils/dump_system_info.sh | bash -s -
```

This default to using `eth0` and `eth1` for `wan` and `lan` respectively. If you are using other interfaces (let say eth0 and wlan0 respectively), use:
```
curl https://raw.githubusercontent.com/facebook/augmented-traffic-control/master/utils/dump_system_info.sh | bash -s -  eth0 wlan0
```

**Comment by chantra** [comment]
Hi @kavithaks 
We do not plan to support running ATC on anything but Linux, one of the main reason being that the traffic shaping is performed by the underlying kernel and there is no uniform API cross platforms. That being said, the code was made in a way that one could potentially add support.

Also, ATC may run on Linux, but any type of client can get their traffic shaped by ATC.
