### ISSUE TITLE
ATC is not running，how can i do？

### ISSUE THREAD

**Issue by xmznmn** [facebook/augmented-traffic-control#348]
hi，all
when i run：
sudo python /home/pirates/augmented-traffic-control/atcui/manage.py runserver 0.0.0.0:8000
the issue is：
System check identified no issues (0 silenced).
December 11, 2017 - 09:24:32
Django version 1.11.7, using settings 'atcui.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
No handlers could be found for logger "thrift.transport.TSocket"
atcdClient: TTransportException: Could not connect to any of [('127.0.0.1', 9090)]
[11/Dec/2017 09:24:32] "GET /api/v1/token/ HTTP/1.1" 502 46
atcdClient: TTransportException: Could not connect to any of [('127.0.0.1', 9090)]

**Comment by xmznmn** [comment]
i also run the python 2.7
this is my Network card information：
br0       Link encap:Ethernet  HWaddr 08:57:00:bd:4d:8d  
          inet addr:10.230.75.24  Bcast:10.230.75.255  Mask:255.255.255.0
          inet6 addr: fe80::1a03:73ff:fe2f:ccba/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:9324 errors:0 dropped:2 overruns:0 frame:0
          TX packets:2715 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:1429797 (1.4 MB)  TX bytes:197719 (197.7 KB)

enp0s25   Link encap:Ethernet  HWaddr 18:03:73:2f:cc:ba  
          inet addr:10.230.75.39  Bcast:10.230.75.255  Mask:255.255.255.0
          inet6 addr: fe80::1a03:73ff:fe2f:ccba/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:24131 errors:0 dropped:90 overruns:0 frame:0
          TX packets:16427 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:9777933 (9.7 MB)  TX bytes:2008804 (2.0 MB)
          Interrupt:20 Memory:e1a00000-e1a20000 

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:414 errors:0 dropped:0 overruns:0 frame:0
          TX packets:414 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:29879 (29.8 KB)  TX bytes:29879 (29.8 KB)

wlp2s0    Link encap:Ethernet  HWaddr 08:57:00:bd:4d:8d  
          inet6 addr: fe80::a57:ff:febd:4d8d/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:9734 errors:0 dropped:0 overruns:0 frame:0
          TX packets:14854 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:1448266 (1.4 MB)  TX bytes:8694214 (8.6 MB)

**Comment by chantra** [comment]
@xmznmn you need to run `atcd`, see https://github.com/facebook/augmented-traffic-control#atcd

**Comment by xmznmn** [comment]
and i run atcd is "atcd --atcd-lan wlp2s0 --atcd-wan enp0s25",but atc is not running
thanks for help
