### ISSUE TITLE
Use rest_framework.views.APIView in atc-profile-storage

### ISSUE THREAD

**Issue by chantra** [facebook/augmented-traffic-control#49]
By subclassing APIView in atc-profile-storage, instead of getting raw json when browsing to the endpoint, we would be able to get a View that let the user GET/POST/DELETE to the endpoint just like with /api/v1/shape (see screenshot)
It proves to be pretty handy when troubleshooting or fiddling with values rather than having to fallback to curl.
![screenshot from 2015-03-22 22 58 20](https://cloud.githubusercontent.com/assets/24572/6774970/fd8150ce-d0e6-11e4-8cb2-2f27a752f758.png)

**Comment by facebook-github-bot-7** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by chantra** [comment]
closing as wontfix given that we are moving toward the golang version.
