### ISSUE TITLE
Ship with some pre-configured profiles

### ISSUE THREAD

**Issue by patcon** [facebook/augmented-traffic-control#56]
For those just jumping in, would be nice to have some pre-sets based on some real network conditions. Some people just want to start testing their applications, and would rather not research connectivity on problem-networks :)

Great tool, and thanks!

**Comment by patcon** [comment]
Possibly helpful http://www.speedguide.net/faq/what-are-the-actual-speeds-of-gprs-edge-umts-hspa-366

**Comment by patcon** [comment]
@zfjagann mentioned in IRC that he would look into providing some sample profiles. Also, he mentioned some info was in the blog post screenshots (though not much):

https://code.facebook.com/posts/1561127100804165/augmented-traffic-control-a-tool-to-simulate-network-conditions/

**Comment by zfjagann** [comment]
There are also some sample profiles in the screenshot on [the website](http://facebook.github.io/augmented-traffic-control/), but again, not very helpful.
