### ISSUE TITLE
atcd should use upstart script

### ISSUE THREAD

**Issue by zfjagann** [facebook/augmented-traffic-control#58]
We switch atcui to use upstart a while ago (bff9f730), but never upgraded atcd.

**Comment by facebook-github-bot-7** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by chantra** [comment]
closing as wontfix given that we are moving toward the golang version and we are retiring chef deployment atm.
