### ISSUE TITLE
Can't create profiles in Firefox

### ISSUE THREAD

**Issue by patcon** [facebook/augmented-traffic-control#59]
![FF profile creation error screenshot](https://i.imgur.com/gn9wsti.png)

When trying to create any profile in FF, I get a form validation error. Works find for Chrome (which was how I got the "slow network" that appears in the screenshot).

FF 36.0.1 (Ubuntu 14.04) host, running in vagrant "trusty" box at tag v0.1.0

**Comment by patcon** [comment]
thanks! :+1:

**Comment by zfjagann** [comment]
yep. good find!
