### ISSUE TITLE
Website needs to describe what ATC would be used for

### ISSUE THREAD

**Issue by richb-hanover** [facebook/augmented-traffic-control#61]
The website (both github and http://facebook.github.io/augmented-traffic-control/) need to have a single sentence that describes what it's useful for. The following sentence provides a motivation for ATC, and could be inserted after the first sentence of the facebook.github.io page:

Developers can use ATC to test their application across varying network conditions, easily emulating high speed, mobile, and even severely impaired networks. Aspects that can be controlled by ATC include:

**Comment by chantra** [comment]
@richb-hanover Thank you for the feedback.
Thats right, that the description is not really descriptive :) I will fix this.
