### ISSUE TITLE
Insatll sparts\fb303\contents.py error

### ISSUE THREAD

**Issue by cjy56789** [facebook/augmented-traffic-control#66]
OS: Windows 7 64 bit
Python Version:3.4.3(64bit)
If installing actd, always say can't copy sparts\fb303\contents.py to C;\Users\%username%\.... etc
failed error code is 1

**Comment by chantra** [comment]
Hi @cjy56789 ,
thank you for reporting this. Unfortunately, neither windows, nor python 3 are supported.
While you should be able to get the web interface to work on windows providing that you use python 2.7, there is no chance you can run `atcd` on windows.

Tks
closing as dup of #65
