### ISSUE TITLE
I  do not kown how to use it ,is there any guide ？

### ISSUE THREAD

**Issue by yelinqing** [facebook/augmented-traffic-control#72]

**Comment by dinny** [comment]
There's a well documented user guide in the home directory. Have you ever read README.md?

**Comment by yelinqing** [comment]
I  have read  README.md. But I don't kow how to use it  with my app

**Comment by chantra** [comment]
I think we need to make a better job at providing a getting started page.
Did you read http://facebook.github.io/augmented-traffic-control/docs/install.html ? To you meet the requirements (Linux on a routing device....)?

Can you give more details about your setup?

**Comment by zfjagann** [comment]
Hi @yelinqing,

I'm going to close this issue since we've done a lot of work in the past week to improve documentation.

If the documentation is still confusing, or incomplete please reopen this issue or create a new one.

Thanks!
