### ISSUE TITLE
Ubuntu 13.04 couldn't creat a profile in local ATC UI page.

### ISSUE THREAD

**Issue by boxerxing** [facebook/augmented-traffic-control#73]
"You must give this new profile a name." always show. and I could not be luanch ATC with "sudo atcd" , my PC connect to internet with lan (IP is 10.57.37.11) I want to luanch ATC server and config a demo profile to test. please give me some detail run commend example.

**Comment by zfjagann** [comment]
Hi @boxerxing,

Please take a look at the installation instructions here on [our website](http://facebook.github.io/augmented-traffic-control/docs/install.html). If those are confusing or incomplete please let us know and we'll fix them.

Thanks for the feedback!

**Comment by zfjagann** [comment]
If you're having issues with the ATCUI specifically it would be helpful to know what platform you are using (Operating system and browser version). Thanks.

**Comment by boxerxing** [comment]
@zfjagann my OS is Ubuntu 13.04 with firefox browser

**Comment by zfjagann** [comment]
We just pushed version 0.1.1 which contains a fix for #59 a bug which affected firefox. Please update your atc and the `You must give this new profile a name` should not happen again.

What error happens when you run `sudo atcd`? Does it crash with a stack trace, or is something else going on?

**Comment by zfjagann** [comment]
I'm going to close this since I havne't heard anything about it for a while. Please re-open if you're still having issues.
