### ISSUE TITLE
Come up with a list of diagnostising steps

### ISSUE THREAD

**Issue by chantra** [facebook/augmented-traffic-control#75]
We are getting reports back about people having issues installing ATC partly because we did not do a good job at highlighting the requirements, but also, when we have a report, we have little actionable item.

Having a consistent list of info we need would help in getting better signal on what may be wrong, we could also flag directly if the host is suitable to run `atcd`....

**Comment by wwewwt** [comment]
Ubuntu 12.04  desktop
Thinkpad x220 
eth0 (internet) , wlan0(used hostapd to create a Soft-AP)

**Comment by zfjagann** [comment]
For bugs in the UI/API it'd be helpful for people to submit their `settings.py` and `urls.py`

We should also probably recommend people make use of [gists](https://gist.github.com/) for large files. Having copy/pasta in our issues is really difficult to read.

**Comment by chantra** [comment]
5763ebf4a65428ee96c8f3c471c42680e40c4953 adds a script to dump some information. This will give us info about people system.
So far we mainly have add questions around atcd and its config rather than the ui part.

Calling this close for now.
