### ISSUE TITLE
Error when installing via pip

### ISSUE THREAD

**Issue by codingstyle** [facebook/augmented-traffic-control#77]
Hi,

Installation hangs with atc_thrift when I try to install packages with pip on Ubuntu 13.10.

Here is the log :

```
Downloading/unpacking atc-thrift
  Downloading atc_thrift-0.1.0.tar.gz
  Running setup.py egg_info for package atc-thrift
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/tmp/pip_build_root/atc-thrift/setup.py", line 16, in <module>
        readme = open('README.md', 'r')
    IOError: [Errno 2] No such file or directory: 'README.md'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/tmp/pip_build_root/atc-thrift/setup.py", line 16, in <module>

    readme = open('README.md', 'r')

IOError: [Errno 2] No such file or directory: 'README.md'
```

It looks like README.md is required but not present in the package.

Cheers,
Chris

**Comment by zfjagann** [comment]
Which platform are you install atc-thrift on? In particular, the version of pip and python you're running would  be helpful.

**Comment by chantra** [comment]
I could repro on ubuntu 13.10. It does not seem to use the wheel package.

I will fix this.
@codingstyle In the meantime, you can install from source.

**Comment by chantra** [comment]
It seems it would be sufficient to add the readme in MANIFEST.in

**Comment by chantra** [comment]
@codingstyle This will make it into 0.1.1 which I believe we will get out soon once we have piggy backed a few other issues that went through the net.
In the meantime, installing from source using the following command from the root of the repository:
```
pip install atc/atc_thrift/ atc/atcd/ atc/django-atc-api/ atc/django-atc-demo-ui/ atc/django-atc-profile-storage/
```

should work.
