### ISSUE TITLE
what is this problem? "darwin backend is not implemented!"

### ISSUE THREAD

**Issue by kimjungyeon** [facebook/augmented-traffic-control#82]
i try until this readme
test -z $VIRTUAL_ENV && source ~/dev/atc/venv/bin/activate
sudo atcd

but it didnt work!
how can i solve this problem?? saveme!!

**Comment by KaptenJansson** [comment]
I guess you are trying to run it on Mac OS? Only Linux is [supported](http://facebook.github.io/augmented-traffic-control/).

**Comment by zfjagann** [comment]
Hi @kimjungyeon:

Currently ATC makes use of iproute2, which is a linux-only tool. In the future we may consider implementing BSD/OSX support, but for the time being ATC will only run on a linux system.

Thanks!

**Comment by kimjungyeon** [comment]
@KaptenJansson , @zfjagann thank you so much! God bless you!!!!  :-)
