### ISSUE TITLE
I have successfully insteaded ATC,But how to use ATC to test my app?

### ISSUE THREAD

**Issue by wwewwt** [facebook/augmented-traffic-control#83]
I can see    http://localhost:8000/atc_demo_ui/ .

Can you help me how to use ATC to test my app?
How to building a Wi-Fi network that could be set to different simulation speeds by the engineers using it?

**Comment by wwewwt** [comment]
I have a Notebook  which has two Network Interface Cards,One is wireless ,the other is Wired.
If I want to test my android app,I think the steps are:

1.Install a linux system in my notebook
2.My app connect to notebook through wireless (WIFI).
3.My notebook connect to internet through  a network cable.
4.Install ATC in my notebook and use my app to set the profile.

Is that all right?    Thank you very much!

**Comment by chantra** [comment]
Hi @wwewwt 

You will need to make sure your notebook acts as a router. What that will entail is roughly:
- your laptop will need to forward packets
- you will (most likely) need to set up natting on the wired interface
- you may need to set up a DHCP server that will distribute IP to your wireless devices (or could set static ips)
- set atc on the router and then get the devices to connect to http://ip.of.the.router.wireless.interface/atc_demo_ui/

**Comment by chantra** [comment]
Also, you may want to use virtual machines for this. It is technically possible to attach your wireless adapter to a VM and set up router in the VM.

**Comment by wwewwt** [comment]
hi @chantra 
Thank you,I have run ATC in my laptop successfully and set the network correctly

But I have meet a problem when I browser "atc_demo_ui":
When I use my mobile browser such as chrome and firfox,after I click the "Select" button,I can't click the "Turn On" button.

**Comment by wwewwt** [comment]
I debug the web in firefox

POST http://192.168.1.1:8000/api/v1/shape/    400 BAD REQUEST

{"detail":"{'down': {'rate': [u'A valid integer is required.']}, 'up': {'rate': [u'A valid integer is required.']}}"}

but I have Post the "down" and "up"  param.

**Comment by chantra** [comment]
@wwewwt what values did you enter for *bandwidth*?

**Comment by wwewwt** [comment]
@chantra   

aha,sorry,I have fixed the problem,the bandwidth must be an integer,not a float.

**Comment by chantra** [comment]
@wwewwt I am happy to hear that this is working for you now.

The demo UI is pretty minimalist and I believe we should have made a better job at surfacing the error messages.

**Comment by wwewwt** [comment]
@chantra  
Thank you for you guidance  :-)
The ATC is  powerful and userful.


The news about Facebook ATC :"Facebook opting instead for a WiFi network traffic control to simulate the data communication in Brazil, India, Nigeria and the Philippines, the low speed 2G cellular networks"

Do you know what are these profiles about Brazil, India, Nigeria and the Philippines, the low speed 2G cellular networks?

**Comment by chantra** [comment]
@wwewwt While I do not have specific values to share, during F8, we also open-sourced

https://github.com/facebook/network-connection-class/

You may find https://github.com/facebook/network-connection-class/blob/master/connectionclass/src/main/java/com/facebook/network/connectionclass/ConnectionQuality.java interesting to get and idea of connection class  ranges.

**Comment by zfjagann** [comment]
@wwewwt: We are working on adding pre-defined profiles to ATC (#56). These will resemble the nation-based profiles shown in the screenshot.
