### ISSUE TITLE
atcd bails out on the first run

### ISSUE THREAD

**Issue by borepstein** [facebook/augmented-traffic-control#85]
Hello all,

I installed the software on my CentOS 6 VM and everything seems to be fine except that atcd would not run. I get the following:

[root@atc-gw ~]# gem install rubocop
ERROR:  Error installing rubocop:
	rainbow requires Ruby version >= 1.9.2.
[root@atc-gw ~]# atcd
Traceback (most recent call last):
  File "/usr/local/bin/atcd", line 12, in <module>
    from atcd.scripts import runner
  File "/usr/local/lib/python3.4/site-packages/atcd/scripts/runner.py", line 19, in <module>
    from atcd.AtcdDeviceTimeoutTask import AtcdDeviceTimeoutTask
  File "/usr/local/lib/python3.4/site-packages/atcd/AtcdDeviceTimeoutTask.py", line 10, in <module>
    from atcd.AtcdThriftHandlerTask import AtcdThriftHandlerTask
  File "/usr/local/lib/python3.4/site-packages/atcd/AtcdThriftHandlerTask.py", line 25, in <module>
    from atc_thrift import Atcd
  File "/usr/local/lib/python3.4/site-packages/atc_thrift/Atcd.py", line 583
    except TrafficControlException, failure:
                                  ^
SyntaxError: invalid syntax
[root@atc-gw ~]# 

Has  anybody seen this? Any idea as to what the cause could be?

Thanks.

Boris.

**Comment by chantra** [comment]
Hi @borepstein 
As per [1], ATC currently only support python 2.7. While we could port atc code itself to python 3, currently the python thrift binding only support python 2.X

[1]: http://facebook.github.io/augmented-traffic-control/docs/install.html

**Comment by borepstein** [comment]
Hello @chantra

Thanks for your response. I have Python version 2.6 and 3.4 installed.

It looks like the installation command:

pip install atc_thrift atcd django-atc-api django-atc-demo-ui
django-atc-profile-storage

does not run under python 2. So do I need to install using python 3 but
then run it using python 2?

Cheers,

Boris.

**Comment by chantra** [comment]
Hi @borepstein 
> It looks like the installation command:
> pip install atc_thrift atcd django-atc-api django-atc-demo-ui
django-atc-profile-storage
> does not run under python 2. So do I need to install using python 3 but
then run it using python 2?

In that case, you will have multiple `pip` version installed. For instance, on a host that has python 2.6 and python 2.7 installed, you would have pip-2.6 and pip-2.7 with pip symlinking to one of the 2.
In that case, you should make sure that you use the right pip version when installing.
When using `virtualenv`, the right python interpreter can be specified with `-p` option as in:
```
virtualenv -p python2.7 myvenv
```

Going back to ATC requirements, we only support **python 2.7** currently. You may want to try python 2.6, but this is most likely not going to work without tweaking things.
