### ISSUE TITLE
issue with speed limitation

### ISSUE THREAD

**Issue by ohorodnichuk** [facebook/augmented-traffic-control#86]
Hi,
I have succesfully installed ATC on Debian and it partially works.
When I try to configure traffic loss, corruption, delay etc. All works well and I can see it thought cli command: 

`tc qdisc show`

`qdisc htb 1: dev eth0 root refcnt 2 r2q 10 default 0 direct_packets_stat 282697`
`qdisc netem 8019: dev eth0 parent 1:2 limit 1000`
`qdisc netem 801f: dev eth0 parent 1:3 limit 1000 delay 100.0ms loss 1% reorder 1% corrupt 1% gap 1`
`qdisc htb 1: dev eth1 root refcnt 2 r2q 10 default 0 direct_packets_stat 181`
`qdisc netem 801a: dev eth1 parent 1:2 limit 1000`
`qdisc netem 8020: dev eth1 parent 1:3 limit 1000 delay 100.0ms loss 1% reorder 1% corrupt 1% gap 1`

You can see limit 1000
Limit always is 1000, no matter what I choose like uplink or downlink.

Can somebody help me with this problem?

**Comment by chantra** [comment]
@ohorodnichuk the bandwidth limit is set by the class:
use:
`tc class show dev eth0`
`tc class show dev eth1`

replace eth0 and eth1  with your up/down links

**Comment by ohorodnichuk** [comment]
O! Thanks! I see... 
for eth0
`class htb 1:3 root leaf 804c: prio 0 rate 12000bit ceil 12000bit burst 1599b cburst 1599b`
`class netem 804c:1 parent 804c:`

and the same for eth1

But Speedtest shows me the result which absolutely does not correspond to what I set.
I want to limit the network speed to 0.1mbit/s (12kbps `kilobytes` as I understand from `tc` manual). In speedtest I have got 0.38 - 0.44mbit/s download and network issue when upload.

**Comment by ohorodnichuk** [comment]
Bug maybe?
But I can't investigate it.

When I choose 12kbps only for uplink or downlink as a result a got:
`class htb 1:2 root leaf 8061: prio 0 rate 4194Mbit ceil 4194Mbit burst 1048b cburst 1048b`

4194Mbit?

**Comment by chantra** [comment]
Hi,
Could you send the relevant content from atcd logs (/var/log/daemon.log on Debian iirc,you may need to check other files if not there) and put that in a pastebin. 
The limit of 4g means that there is no limit (you have set the bandwith to 0 or null).
Speedtest are pretty hard to rely on, mainly with low bandwith and potential packet loss/corruption. A test should be performed with only the gateway in the middle.

**Comment by borepstein** [comment]
Just wanted to chime in.

We seem to be having a similar experience. Strangely enough, after we were able to get results consistent with the throughput set.

One differentiating factor - potentially - was that at first I was the only one playing with it but then I let others try their hand at it. But afterwards it was never the same - the speed, even when set to 80000 Kbit/s = 10 MB/s it still transmits at no more than 20 KB/s = 160 Kbit/s. Once you turn shaping off it transmits fine (in our case, many MB/s).

Also noteworthy is the fact that latency controls seem to work just fine.

Just reporting this in hopes this helps troubleshoot the issue.

Cheers,

Boris.

**Comment by chantra** [comment]
@borepstein are people accessing ATC through a natting device? making them all look like they come from the same IP?
ATC would not know about that and anybody setting new settings will make all devices behind the same IP being shaped.

**Comment by ohorodnichuk** [comment]
And for example:
`{"up":{"rate":"100","delay":{"delay":0,"jitter":0,"correlation":0},"loss":{"percentage":0,"correlation":0},"reorder":{"percentage":0,"correlation":0,"gap":0},"corruption":{"percentage":0,"correlation":0},"iptables_options":[]},"down":{"rate":"100","delay":{"delay":0,"jitter":0,"correlation":0},"loss":{"percentage":0,"correlation":0},"reorder":{"percentage":0,"correlation":0,"gap":0},"corruption":{"percentage":0,"correlation":0},"iptables_options":[]}}`

`root@atc:~# tc class show dev eth1`
`class htb 1:2 root leaf 800c: prio 0 rate 100000bit ceil 100000bit burst 1600b cburst 1600b `
`class netem 800c:1 parent 800c: `
`root@atc:~# tc class show dev eth0`
`class htb 1:2 root leaf 800b: prio 0 rate 100000bit ceil 100000bit burst 1600b cburst 1600b `
`class netem 800b:1 parent 800b: `

Speedtest shows me: DOWN-3.5Mbit/s / UP-0.25 Mbit/s

**Comment by borepstein** [comment]
I have a question: the tagging that iptables does to tc to designate packets for a certain queue - is that equivalent to VLAN tagging? Do the packets destined to go out to the world go out tagged? If so, could that confuse the networking equipment involved - such as switches, etc.?

Boris.

**Comment by ohorodnichuk** [comment]
No, this is internal linux kernel logic. Maybe in "kernel" some tags are present. But outbound traffic goes without changes / additions.

**Comment by borepstein** [comment]
Additional info, possibly relevant to this issue.

I discovered the following today. Unreasonably slow - if not hung - transmission results only when two conditions are met:

1) ATCD is running;

2) somewhere down the line NAT takes place.

It seems this may have to do with packet marking introduced by ATCD. Is that possible? Is there a way to unmark packets downstream from the ATCD server? 

Boris.

**Comment by borepstein** [comment]
Yes, there does appear to be a conflict between iptables marking of packets and NAT (MASQ). See this for details:

http://lists.centos.org/pipermail/centos/2015-April/151245.html

**Comment by chantra** [comment]
@borepstein you are referring to can be found here: http://lists.netfilter.org/pipermail/netfilter/2000-November/006089.html
For testing purpose you could add an extra layer of routing (e.g ATC routes through another host that does the natting), this way that would rule out the nat/marking conflict.
Or depending on your setup, you can simply route the traffic to the `lan` network to route though the `atc`. This will really vary depending your network, but here is 1 potential setup:
- atc's wan interface is in bridge mode and the next hop nats the traffic, in this case you will need to tell the next hop to route your atc lan subnet via the atc's wan ip ( and stop natting)

**Comment by borepstein** [comment]
@chantra

Thanks, I have tried this but the marks don't go anywhere - and since there
are places downstream where NATing occurs looks like we still got a problem.

Boris.

**Comment by chantra** [comment]
The mark is internal to the host only.

**Comment by borepstein** [comment]
Well, given the consequences I am seeing - i.e., severe degradation past
wherever the NATing gateway is, even if it is a hop or two removed from the
ATCD gateway - I find it hard to believe that the content of the IP packets
is not altered somehow. Question is, how - and how to remedy this situation.

Cheers,

Boris.

**Comment by chantra** [comment]
@borepstein I guess I do not have any quick solution to how to remedy this.
We will try to repro when we get time for it, in the meantime, I would suggest you fiddle a bit with the settings to find something that you feel representative of what you want to test.

**Comment by borepstein** [comment]
@chantra

Don't worry, I fully understand - this is a tricky one.

What kind of setup do you guys use internally, by the way?

I am working on it, hopefully will have more data and/or thoughts before
too long.

Cheers,

Boris.

**Comment by borepstein** [comment]
@chantra

Additionally, see this:

"iptables has a method called fwmark, which can be used to add a mark to packages, a mark that can survive routing across interfaces.
First, this makes packages marked with 6, to be processed by the 1:30 class
tc filter add dev eth0 protocol ip parent 1: prio 1 handle 6 fw flowid 1:30 
This sets that mark 6, using iptables
iptables -A PREROUTING -t mangle -i eth0 -j MARK --set-mark 6
You can then use the regular way of iptables to match packages and then use fwmark to mark them."

Source: https://wiki.archlinux.org/index.php/Advanced_traffic_control

So yes, marks are inserted into packets and can indeed travel down the line which matches perfectly with what I am observing.

So the questions still is, how to get rid of them once they have been used for the intended purpose.

Boris.

**Comment by chantra** [comment]
well, it survives routing across interfaces.... not across hosts.
My point is that the packets going out of the ATC box are not marked.

We are indeed marking packets on the WAN interface to shape them on the LAN interface, and packets on the LAN interface to be shaped on the WAN interface.

I seriously  doubt the marks make it out of the box, I dont really see where they would fit in the IP stack anyway. If there were, it would mean that something along the way also needs to handle those marks.

**Comment by chantra** [comment]
The setup we have is a router inline (no natting at the ATC level).

**Comment by chantra** [comment]
Ok, so I have been doing some iperf test and can confirm that we indeed get the throttling rate we expect.
UDP iperf has been reporting the right bandwidth. Using TCP, the rate will become pretty low as there is a lof of packet dropped and retransmission ... happening. 

you could use chantra/augmented-traffic-control@8961db07784a9a30283414e66c33768e64519870 and start atcd with:
```
atcd --atcd-dont_drop_packets
```
And packets will be queued on the ATC device instead of being dropped. This will have the effect on having packets queueing up and getting out the atc router at the throttling rate.

**Comment by borepstein** [comment]
@chantra

Thank you very much! We will do that and report back.

Additionally, I have done some research and can confirm that the marks
(iptables --set-mark) do not indeed leave the machine that they are used
on, i.e., the ATCD server. And yes, indeed what you are saying makes
perfect sense as latency settings and ICMP transmissions match what is
expected, speedwise, whereas TCP goes in bursts and is generally slow that
would certainly correspond to the picture you are describing.

**Comment by borepstein** [comment]
@chantra

Thanks again for all your help.

So just to be sure - you were saying that ATCD itself - not the kernel - would drop the packets. Because one idea of mine was to try and tune up the kernel - in case it was the kernel responsible.

**Comment by borepstein** [comment]
@chantra,

I just tried running this new code and got the following:

(venv)[atc@atc-gw ~]$ sudo /home/atc/dev/atc/venv/bin/atcd
--atcd_dont_drop_packets
usage: atcd [-h] [--daemon] [--dryrun] [--kill] [--level LEVEL]
            [--logfile LOGFILE] [--pidfile PIDFILE]
            [--tasks [TASK [TASK ...]]] [--status] [--thrift-host HOST]
            [--thrift-threads N] [--thrift-port PORT]
            [--sqlite-max-items SQLITE_MAX_ITEMS] [--sqlite-file
SQLITE_FILE]
            [--atcd-burst-size BURST_SIZE] [--atcd-fresh-start]
            [--atcd-iptables IPTABLES] [--atcd-lan LAN]
            [--atcd-mode {secure,unsecure}] [--atcd-pcap-dir PCAP_DIR]
            [--atcd-pcap-url-base PCAP_URL_BASE] [--atcd-tcpdump TCPDUMP]
            [--atcd-wan WAN] [--AtcdDeviceTimeoutTask-interval SECONDS]
atcd: error: unrecognized arguments: --atcd_dont_drop_packets
(venv)[atc@atc-gw ~]$

The code - the two files on the branch - does not seem to contain the
actual string for the option: --atcd-dont_drop_packets I played a bit with
the string (changing "-" to "_" and vice versa) but no luck so far. Is
there a piece to this I am missing by any chance?

Also, I have one more question. Was it the ATCD code itself that was
dropping the packets or was it the kernel? In case it is the kernel could
we perhaps look at some kernel options too? is so - any thoughts on what
they would be?

Cheers,

Boris.

**Comment by chantra** [comment]
@borepstein 
> So just to be sure - you were saying that ATCD itself - not the kernel - would drop the packets. Because one idea of mine was to try and tune up the kernel - in case it was the kernel responsible.

Well, this is the kernel that does the heavy work here. ATCD is only instructing it how to do it by setting new TC values over netlink.

> The code - the two files on the branch - does not seem to contain the
actual string for the option: --atcd-dont_drop_packets I played a bit with
the string (changing "-" to "_" and vice versa) but no luck so far. Is
there a piece to this I am missing by any chance?

Sorry, my bad, it should be `--atcd-dont-drop-packets`. Now you are most likely running the old version because it got installed through pip. You should install the new version.
```
pip uninstall atcd
pip install /path/to/atcd/
```
should help.

**Comment by borepstein** [comment]
@chantra

Thanks.

I just did that - full deinstallation, full reinstallation and still get
the following:

(venv)[atc@atc-gw ~]$ sudo ~/dev/atc/venv/bin/atcd --daemon
--atcd-dont-drop-packets
usage: atcd [-h] [--daemon] [--dryrun] [--kill] [--level LEVEL]
            [--logfile LOGFILE] [--pidfile PIDFILE]
            [--tasks [TASK [TASK ...]]] [--status] [--thrift-host HOST]
            [--thrift-threads N] [--thrift-port PORT]
            [--sqlite-max-items SQLITE_MAX_ITEMS] [--sqlite-file
SQLITE_FILE]
            [--atcd-burst-size BURST_SIZE] [--atcd-fresh-start]
            [--atcd-iptables IPTABLES] [--atcd-lan LAN]
            [--atcd-mode {secure,unsecure}] [--atcd-pcap-dir PCAP_DIR]
            [--atcd-pcap-url-base PCAP_URL_BASE] [--atcd-tcpdump TCPDUMP]
            [--atcd-wan WAN] [--AtcdDeviceTimeoutTask-interval SECONDS]
atcd: error: unrecognized arguments: --atcd-dont-drop-packets

Is it possible you didn't fully commit all the changes?

Boris.

**Comment by borepstein** [comment]
Just did another reinstallation including clearing out the whole atcd
directory ( .../venv/lib/python2.7/site-packages/atcd ). Then searched
for 'atcd-dont-drop-packets'
in my home directory:

find . -type f -exec grep -l atcd-dont-drop-packets {} \;

and found nothing.

Just FYI.

Cheers,

Boris.

**Comment by chantra** [comment]
@borepstein 
I did not commit it, it is on my personal branch: https://github.com/chantra/augmented-traffic-control/tree/no_drop

**Comment by borepstein** [comment]
@chantra

OK, I got it, cool.

What's the installation procedure I should follow to install it from that
branch?

Thanks.

Boris.

**Comment by borepstein** [comment]
@chantra 

I figured out the installation procedure.

So I did some testing and it looks like the branched version does indeed contain the fix. IMO, ATCD should never drop packets so this ought to be the mainstay behaviour - but this is just my opinion:)

Thank you very much for all your help.

Cheers,

Boris.

**Comment by chantra** [comment]
@borepstein 
Well, typically, some buffers would eventually fill up and drop packets. I agree that we have some rather arbitrary values here and there is room for improvement here. We had a task to make the dropping configurable which in essence is somewhat what the diff I linked here does.
I am going to revive this and folow up in a separate task.

I believe this task is somewhat resolved or at least alternate solution are provided. I will close it for now.

**Comment by borepstein** [comment]
@chantra

I agree that you can close the task.

If you don't mind me asking: how was the issue addressed? What was it that
you did that caused the ATCD server to stop dropping those packets?

Boris.

**Comment by chantra** [comment]
well, the way we set up the policy when going above the limited rate is changed to queue instead of droping.

**Comment by borepstein** [comment]
OK, makes sense.

Where is the policy set?

**Comment by chantra** [comment]
@borepstein  The policy is set in https://github.com/facebook/augmented-traffic-control/blob/c61493388b3c3738db0b9ad6943cee65451178f1/atc/atcd/atcd/backends/linux.py#L322

**Comment by borepstein** [comment]
@chantra

Thanks.

So this is the default policy, right?

And what is dropped is excess packets in the tc accounting/control queues,
correct?

Boris.
