### ISSUE TITLE
Can you share the default "atcd" passphrase?

### ISSUE THREAD

**Issue by nitint007** [facebook/augmented-traffic-control#87]
I am stuck on "sudo atcd" step where it asks for "passphrase".
I tried with "system" and my system password too but it says "command not allowed".

Though the sudo is working fine, it seems to be an issue of atcd.

Can anyone please assist here?

**Comment by ohorodnichuk** [comment]
I have run atcd without passphrase
I think that this "passphrase" is your user password (ubuntu/debian style) 

Try to run it from root
`sudo su`
`atcd --daemon`
and read `atcd --help` will be useful

**Comment by chantra** [comment]
@nitint007 what OS are you running?

provided that you did not install `atc` in a virtualenv, the commands provided by @ohorodnichuk should work.

Regarding sudo, as @ohorodnichuk mentioned, this is the passphrase of your user.

**Comment by chantra** [comment]
I will close this as this is more an issue in using sudo for you specific OS. `atcd` will not ask for your passphrase.
