### ISSUE TITLE
fall back to sysvinit init scripts if no other (known) init system found

### ISSUE THREAD

**Issue by zfjagann** [facebook/augmented-traffic-control#9]
Right now we print a warning in chef if chef does not understand the init system in use.

We should probably fall back to using sysvinit configs instead so that we at least have something that works on some systems, rather than throwing up our hands in defeat.

Pros of doing this:
- Provides something that works on nearly all platforms (virtually everything except systemd systems)
- Provides a template for how to run our service which end-users can adapt for their situation.

Cons of doing this:
- May provide confusion if the sysvinit task doesn't work, rather than illustrating the actual problem (that we don't know which init system to use). 

The sysvinit configs for `atcui` can be pulled from history:
https://github.com/facebook/augmented-traffic-control/tree/3fa1cb284fc6dea951b7695a179d91aaea6783d1/chef/atc/files/default/init.d

**Comment by facebook-github-bot-7** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by chantra** [comment]
closing as wontfix given that we are moving toward the golang version and we are retiring chef provisioning.
