### ISSUE TITLE
ERROR:sparts.tasks:Error creating task, AtcdLinuxShaper

### ISSUE THREAD

**Issue by sunhao111999** [facebook/augmented-traffic-control#91]
hi all:

   when run atcd with ubuntu 14.04, i get this error:

```
INFO:AtcdVService.AtcdNBServerTask:AtcdNBServerTask Server Started on 127.0.0.1:9090
CRITICAL:AtcdVService.AtcdLinuxShaper:One of the following interfaces does not exist: eth1, eth0
ERROR:sparts.tasks:Error creating task, AtcdLinuxShaper
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sparts/vtask.py", line 313, in init
    t.initTask()
  File "/usr/local/lib/python2.7/dist-packages/atcd/backends/linux.py", line 48, in initTask
    super(AtcdLinuxShaper, self).initTask()
  File "/usr/local/lib/python2.7/dist-packages/atcd/AtcdThriftHandlerTask.py", line 220, in initTask
    self._links_lookup()
  File "/usr/local/lib/python2.7/dist-packages/atcd/backends/linux.py", line 65, in _links_lookup
    raise Exception(msg)
Exception: One of the following interfaces does not exist: eth1, eth0
ERROR:AtcdVService:Unexpected Exception during init
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sparts/vservice.py", line 268, in _runloop
    instance._createTasks()
  File "/usr/local/lib/python2.7/dist-packages/sparts/vservice.py", line 167, in _createTasks
    self.tasks.init()
  File "/usr/local/lib/python2.7/dist-packages/sparts/vtask.py", line 332, in init
    len(exceptions))
Exception: Unable to start service (1 task start errors)
INFO:AtcdVService:Received graceful shutdown request
DEBUG:AtcdVService:VService Active.  Awaiting graceful shutdown.
INFO:AtcdVService:Waiting for tasks to shutdown gracefully...
DEBUG:AtcdVService:Waiting for <atcd.AtcdDeviceTimeoutTask.AtcdDeviceTimeoutTask object at 0x7faa9b613a50> to stop...
DEBUG:AtcdVService:Waiting for <atcd.backends.linux.AtcdLinuxShaper object at 0x7faa9b613d50> to stop...
DEBUG:AtcdVService:Waiting for <atcd.AtcdDBQueueTask.AtcdDBQueueTask object at 0x7faa9b613e10> to stop...
DEBUG:AtcdVService:Waiting for <atcd.AtcdThriftHandlerTask.AtcdNBServerTask object at 0x7faa9b613ed0> to stop...
INFO:AtcdVService:Instance shut down gracefully

```

please help!

**Comment by agargiulo** [comment]
You need two network interfaces to run atcd. It's telling you that one of `eth0` or `eth1` doesn't exist on your system.

**Comment by zfjagann** [comment]
The error message of interest is this line (a little above half-way down):

    Exception: One of the following interfaces does not exist: eth1, eth0

As @agargiulo mentioned, you need two interfaces to run ATC. The names `eth0` and `eth1` are the defaults.  To change them modify the `ATCD_WAN` and `ATCD_LAN` values in `/etc/default/atcd`.

**Comment by zfjagann** [comment]
Also, if your machine only has a single physical NIC, you can create a virtual NIC fairly easily in most linux systems. The steps for doing so a largely distro-specific, so I won't go into it here, but it is certainly possible. :)

For example, the Arch Wiki contains a wonderful [guide](https://wiki.archlinux.org/index.php/VLAN) describing how to do this on an [Arch Linux](http://archlinux.org/) system.

**Comment by sunhao111999** [comment]
@agargiulo  @zfjagann Thanks

**Comment by nickylin** [comment]
@zfjagann  hi when i start the atcd, also said "Exception: One of the following interfaces does not exist: eth1, eth0"
but how can i create another interface in linux ? and now i have create one interface call ra0 with miwifi

**Comment by nickylin** [comment]
this is my ip info:
root@ubuntu:/home/cxxxDownloads/mt7601u-master# ifconfig
eth0      Link encap:Ethernet  HWaddr 00:0c:29:4e:51:9a  
          inet addr:192.168.30.129  Bcast:192.168.30.255  Mask:255.255.255.0
          inet6 addr: fe80::20c:29ff:fe4e:519a/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:6290 errors:0 dropped:0 overruns:0 frame:0
          TX packets:4302 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:4281344 (4.2 MB)  TX bytes:574111 (574.1 KB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:1342 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1342 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:130583 (130.5 KB)  TX bytes:130583 (130.5 KB)

ra0       Link encap:Ethernet  HWaddr 64:09:80:62:38:ea  
          inet addr:192.168.199.1  Bcast:192.168.199.255  Mask:255.255.255.0
          inet6 addr: fe80::6609:80ff:fe62:38ea/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:18343 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:440472 (440.4 KB)  TX bytes:260 (260.0 B)

**Comment by chantra** [comment]
@nickylin as per the documentation (or *atcd -h* 's help) use --atcd-wan and/or --atcd-lan to adapt to your setup.

**Comment by mikechengwei** [comment]
hello,i have a problem. 
i had do ：
'killall atcd'
kill port 9090 and 8080
but the error can't solve
Exception: Unable to start service (1 task start errors)
INFO:AtcdVService:Received graceful shutdown request
DEBUG:AtcdVService:VService Active.  Awaiting graceful shutdown.
INFO:AtcdVService:Waiting for tasks to shutdown gracefully...
DEBUG:AtcdVService:Waiting for <atcd.AtcdDeviceTimeoutTask.AtcdDeviceTimeoutTask object at 0x7efce28f3910> to stop...
DEBUG:AtcdVService:Waiting for <atcd.backends.linux.AtcdLinuxShaper object at 0x7efce28f3710> to stop...
DEBUG:AtcdVService:Waiting for <atcd.AtcdDBQueueTask.AtcdDBQueueTask object at 0x7efce28f3690> to stop...
DEBUG:AtcdVService:Waiting for <atcd.AtcdThriftHandlerTask.AtcdNBServerTask object at 0x7efce28f3610> to stop...
INFO:AtcdVService:Instance shut down gracefully
