### ISSUE TITLE
do i have to build failover gateway?

### ISSUE THREAD

**Issue by kimjungyeon** [facebook/augmented-traffic-control#94]
if i got this spec, can i make the atcd environment?
1. one linux laptop (not include VM)
2. one network card

my idea is like this

1. connect a cable to my laptop from internet sharer(like anygate)
2. and then make laptop to wifi access point
3. build atcd on laptop
4. on smartphone, access the wifi (2.) and use ATC

**Comment by chantra** [comment]
Hi @kimjungyeon 
Yes that should be fine, make sure your wifi adapter can do AP mode, that you authorized forwarding packets and that you nat the traffic going out through the wired interface.

**Comment by kimjungyeon** [comment]
@chantra thanks for your help!!! :-)
